### ISSUE TITLE
Doesn't handle indexed format strings

### ISSUE THREAD

**Issue by ethanhs** [asottile/pyupgrade#134]
The following code which I tried to reduce (which I had no idea was possible):
```python
thing = {'a': 1, 'b': 2}
print('{0[a]} and {0[b]}'.format(thing))
```
leads to 
```
Traceback (most recent call last):
  File "/home/ethan/venv/bin/pyupgrade", line 10, in <module>
    sys.exit(main())
  File "/home/ethan/venv/lib/python3.7/site-packages/pyupgrade.py", line 1396, in main
    ret |= fix_file(filename, args)
  File "/home/ethan/venv/lib/python3.7/site-packages/pyupgrade.py", line 1372, in fix_file
    contents_text = _fix_fstrings(contents_text)
  File "/home/ethan/venv/lib/python3.7/site-packages/pyupgrade.py", line 1348, in _fix_fstrings
    tokens[i] = token._replace(src=_to_fstring(token.src, node))
  File "/home/ethan/venv/lib/python3.7/site-packages/pyupgrade.py", line 1310, in _to_fstring
    name = ''.join((params[k or str(i)], dot, rest))
KeyError: '0[a]'
```

This is a very esoteric format string usage, but 🤷‍♂️

**Comment by asottile** [comment]
indeed, a bit of an oversight.  oddly enough I thought far enough ahead to support dotted names but not brackets

**Comment by merwok** [comment]
Just a note that may be useful:

`format` uses a mini-language where keys for item access are not quoted, but f-strings contain real, arbitrary expressions and require quotes.

```python
>>> info = {"name": "Alice", "age": 36}
>>> "{0[name]} is {0[age]}".format(info)
'Alice is 36'
>>> f"{info[name]} is {info[age]}"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'name' is not defined
>>> f"{info['name']} is {info['age']}"
'Alice is 36'
```

**Comment by asottile** [comment]
for now I'm going to make this not-crash, can always follow up with improving this to rewrite those as well.

There's a couple other cases where the fstring rewriter is timid -- patch incoming!

**Comment by asottile** [comment]
Note to future self, there's weird things that are legal / illegal:

```pycon
>>> '{[0]}'.format([1, 2, 3])
1
>>> '{["]}'.format({'"': 'hi'})
'hi'
>>> '{[0]}'.format({'0': 'hi'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 0
>>> '{[\u2603]}'.format({'\u2603': 'hi'})
'hi'
```

**Comment by merwok** [comment]
```python
>>> '{[0]}'.format([1, 2, 3])
1
```

Makes sense if one remembers that numbered placeholders are optional, this is equivalent to `'{0[0]}'.format(list)`.


The other two are both caused by the fact that placeholders are custom mini-language, not Python.  There is attribute access or item access depending on dot or bracket, and for items things in brackets are always strings:
https://www.python.org/dev/peps/pep-3101/#simple-and-compound-field-names

The `'{[0]}'.format({'0': 'hi'})` example shows a blind spot in the spec though.
There is no mention that an item key that looks like an integer will be parsed as such, and not as a string.  I’m looking at docs and tickets and can’t find so far where that is defined!

**Comment by asottile** [comment]
Ah yeah I'm familiar with the behavior, but I always need to double check. The hints there for future me are I'd have to:
- check for backslashes (not allowed in fstring) 
- check for quotes (can only nest the opposite) 
- check for integers (indexing) 

Though yeah you're right, I can't find the integer thing anywhere :S

**Comment by merwok** [comment]
Let’s see if experts answer! https://bugs.python.org/issue7951#msg340877
