### ISSUE TITLE
py3-plus: .encode('utf-8') → .encode() & .decode('utf-8') → .decode()

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#138]
In Python 3, the first positional argument to `.encode()` and `.decode()` defaults to `'utf-8'`. This was not the case with Python 2:

https://docs.python.org/3/library/stdtypes.html#str.encode
https://docs.python.org/3/library/stdtypes.html#bytes.decode

As this is the most common value passed, there could be a transform to simplify the calls to just `.encode()` or `.decode()` (without the first positional argument). This could help clean up and simplify modern Python code by removing noise.

**Comment by asottile** [comment]
hmm github must have lost my comment I had typed something out but it's gone

I'm not sure this rewrite is safe in all cases, since an arbitrary object could implement `decode` / `encode` to have different semantics

for instance `webob.Request` has a `decode` method

**Comment by mxr** [comment]
Is it worth doing when the receiver is a string literal?

**Comment by asottile** [comment]
I think the only case that could safely be rewritten is for literals and `.encode()`

```python
"unicode text☃".encode('UTF-8')   # "unicode text☃".encode()
"ascii text".encode('UTF-8')             # b"ascii text"
```

**Comment by mxr** [comment]
I see. Why can't `b'asd'.decode('UTF-8')` be safely transformed? Can pyupgrade try to execute the decoding & only apply the transformation if decoding doesn't raise?

**Comment by asottile** [comment]
it can, but like, who would write that

**Comment by WSLUser** [comment]
Will this work if pyupgrade has already been used (along with modernize and/or futurize)?

**Comment by asottile** [comment]
> Will this work if pyupgrade has already been used (along with modernize and/or futurize)?

Could you elaborate? `pyupgrade` is idempotent and doesn't have an opinion on other tools that are used

**Comment by WSLUser** [comment]
I mean if I ran pyupgrade for a script already, will it run through and successfully make the changes using this new addition for the same script?

**Comment by asottile** [comment]
yes, however this particular feature has not been released yet

**Comment by WSLUser** [comment]
Ah, I saw the docs were updated and assumed it was available as a beta at least on PyPi.

**Comment by asottile** [comment]
not yet, I want to finish up a PR first -- you can try the latest from git however `pip install git+https://github.com/asottile/pyupgrade` (or via pre-commit `pre-commit try-repo https://github.com/asottile/pyupgrade` (to just try) or if you have it already configured `pre-commit autoupdate --repo https://github.com/asottile/pyupgrade --bleeding-edge`)

**Comment by asottile** [comment]
I believe this one is as "done" as it can be -- closing this out
