### ISSUE TITLE
py3.3+: IOError (and others) -> OSError

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#141]
In Python 3.3+ the following exceptions are now simple aliases of `OSError`: `IOError`, `EnvironmentError`, `WindowsError`, `mmap.error`, `socket.error` and `select.error`.

The aliases have been removed from the documented hierarchy: https://docs.python.org/3/library/exceptions.html#exception-hierarchy

I think pyupgrade should rewrite these aliases as the canonical `OSError`.

References:

https://docs.python.org/3/whatsnew/3.3.html#pep-3151-reworking-the-os-and-io-exception-hierarchy

https://docs.python.org/3/library/exceptions.html#OSError

**Comment by asottile** [comment]
@mxr did some work on this (that just got released) (replacing just the plain aliases for now)

Another thing that would be nice to have (noticed while trying this on `pytest`):

(special case the `except` block type tuple)

```python
try:
    ...
except (IOError, OSError):    # except OSError:
    ...
```

**Comment by mxr** [comment]
I was hacking on that a bit today but there are a ton of fun cases

```
except (IOError, OSError):				# except OSError:
except(IOError, OSError):				# except OSError:
except(IOError,):						# except OSError:
except (IOError, KeyError, OSError):	# except (OSError, KeyError): (how do we even choose the right order)
```

etc

**Comment by asottile** [comment]
those all seem correct to me, I don't think ordering is important for the last one

**Comment by mxr** [comment]
Anything else left for this ticket?

**Comment by asottile** [comment]
I don't think so, I might make a second pass where `pyupgrade` properly knows what things are global or reassinged or what-not so we can cover calls as well as just the `except` / `raise` blocks that we have higher confidence about
