### ISSUE TITLE
TokenError

### ISSUE THREAD

**Issue by thisch** [asottile/pyupgrade#145]
Thank you very much for writing this tool!!

I want to run pyupgrade over a project that probably still contains code that raises a syntax error when imported in a python3 interpreter.

``pyupgrade --py36-plus`` outputs is the following in a python3.7 conda env:

```
filename1.py
filename2.py
Traceback (most recent call last):
  File "/home/thomas/miniconda/envs/py37/bin/pyupgrade", line 10, in <module>
    sys.exit(main())
  File "/home/thomas/miniconda/envs/py37/lib/python3.7/site-packages/pyupgrade.py", line 1428, in main
    ret |= fix_file(filename, args)
  File "/home/thomas/miniconda/envs/py37/lib/python3.7/site-packages/pyupgrade.py", line 1397, in fix_file
    contents_text = _fix_format_literals(contents_text)
  File "/home/thomas/miniconda/envs/py37/lib/python3.7/site-packages/pyupgrade.py", line 107, in _fix_format_literals
    tokens = src_to_tokens(contents_text)
  File "/home/thomas/miniconda/envs/py37/lib/python3.7/site-packages/tokenize_rt.py", line 44, in src_to_tokens
    ) in tokenize.generate_tokens(tokenize_target.readline):
  File "/home/thomas/miniconda/envs/py37/lib/python3.7/tokenize.py", line 579, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (350, 0))
```

Unfortunately this exception is not very helpful, since it doesn't really tell me which file lead to this exception. Note that filename2.py is not the  culprit, because it doesn't have a line with number 350.

IMO pyupgrade should avoid showning tracebacks by defaults, but instead output filename+linum of the faulty files.

Tested it with

```
(py37) > $ conda list pyupgrade                                                                                 [±master ●●]
# packages in environment at /home/thomas/miniconda/envs/py37:
#
# Name                    Version                   Build  Channel
pyupgrade                 1.17.0                     py_0    conda-forge
```

BTW pyupgrade doesn't have a `--version` cli flag.

**Comment by asottile** [comment]
hmm indeed, most of the fixers do guard against this but I guess this one got missed

**Comment by asottile** [comment]
can you share the contents of the file?

**Comment by asottile** [comment]
my guess is it's this: https://bugs.python.org/issue2180

**Comment by thisch** [comment]
I can't share the code but I'll try to find out which file is causing this issue and post a minimal example.

**Comment by thisch** [comment]
```
def bar():
    a = ['a', 'b', 'c' , 'd']
    columnnames = pd.MultiIndex.from_tuples(
        list(product(['k', 'l'], a))
```

**Comment by asottile** [comment]
try with master?

**Comment by thisch** [comment]
Yes the commit on master fixed it! Thx

**Comment by asottile** [comment]
awesome -- thanks for the report!  I'll be making a release later (with the fix for #144 as well)

**Comment by thisch** [comment]
You're welcome! I have to thank you for fixing it ;)

**Comment by thisch** [comment]
FYI when running black over the codebase the output is as expected:

```
reformatted f1.py
reformatted f2.py
error: cannot format f3.py: Cannot parse: 128:4:     targets = rescale([target for (target, _, _) in data]
reformatted f4.py
All done! 💥 💔 💥
3 files reformatted, 14 files left unchanged, 1 file failed to reformat.
```

**Comment by asottile** [comment]
1.17.1 is released with this fix now btw
