### ISSUE TITLE
--py3-plus: io.open => open

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#148]

**Comment by asottile** [comment]
maybe even `codecs.open` if the api is compatible

**Comment by mxr** [comment]
Looks like the arg order is slightly different

https://docs.python.org/3.7/library/io.html#io.open

> ```
> io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
>  ```

https://docs.python.org/3.7/library/codecs.html#codecs.open

> ```
> codecs.open(filename, mode='r', encoding=None, errors='strict', buffering=1)
> ```

Maybe it's still possible in some circumstances?

**Comment by merwok** [comment]
I think the objects returned by codecs.open and io.open have further incompatibilities.

IMO this is a manual upgrade.  A dev can use `codecs.open` for 2.7 and 3.x, then switch to `io.open` explicitly.  Renaming to `open` is a small step when going 3.x-only.
