### ISSUE TITLE
Support use on directories

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#150]
In all my uses of `pyupgrade`, I want to apply it to every Python file in the repo - in general, some directory.  `pyupgrade $(find . -name '*.py')` works OK on \*nix systems, but I'd be happier if I could just write `pyupgrade .` and have it work on Windows too!

Personally I'd prefer to follow Black and flake8 (etc) by having recursive-by-default for directories, but if not a `-r`/`--recursive` flag is also fairly common.

**Comment by asottile** [comment]
see #40 #46 https://github.com/asottile/add-trailing-comma/pull/51 https://github.com/asottile/add-trailing-comma/issues/59 https://github.com/asottile/reorder_python_imports/pull/76
