### ISSUE TITLE
Rewrite `if PY2:` blocks in `--py3-plus`

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#152]
Ideally handle these different cases:

```python
# input
from six import PY2
if PY2:
   x = 5
else:
   x = 6
# output
x = 6
```

But also for

```python
sys.version_info[0] == 2
sys.version_info < (3,)
```
etc.

- [x] `six.PY2`
- [x] `six.PY3`
- [x] `not six.PY2`
- [x] `not six.PY3`
- [ ] `sys.version_info >= (3,)`
- [ ] `sys.version_info < (3,)`
- [ ] `sys.version_info[0] == 2`
- [ ] `sys.version_info[0] == 3`

**Comment by hugovk** [comment]
Good idea. `six.PY3` next?

**Comment by asottile** [comment]
yeah it's WIP because I also want to handle `six.PY3` / `if sys.version_info ...` and maybe even a couple others
