### ISSUE TITLE
Some additional pyupgrade cases

### ISSUE THREAD

**Issue by mitzkia** [asottile/pyupgrade#163]
Hi, 
In my python project I should support both Python2 and Python3 versions. Because of this there are few cases where I should use Python2 form (they are stronger).
My question is:
- Are the following cases valuable in case of pyupgrade (for now it did not find them as a possible upgrade)? 
- If not I would like to understand which upgrade cases are related for pyupgrade

1, open()
- Python2 did not support to use open() with Path() object
- I should use this form: `open(str(file_path), mode)`
- when I remove str() casting python reports:
```
TypeError: coercing to Unicode: need string or buffer, PosixPath found
```
- expected behavior: pyupgrade could find the possible upgrade
from: `open(str(file_path), mode)` to `open(file_path, mode)`

2, shutil.copy()
- Python2 did not support to use shutil.copy() with Path() objects
- I should use this form: `shutil.copy(str(src_file_path), str(dst_dir))`
- expected behavior: pyupgrade could find the possible upgrade
from: `shutil.copy(str(src_file_path), str(dst_dir))` to `shutil.copy((src_file_path), (dst_dir))`

Thanks

**Comment by asottile** [comment]
pyupgrade doesn't know the types of anything so it can't really infer those sorts of upgrades. If it were possible to detect those cases they would be `--py3-plus` only fixes.

But in all likelihood, pyupgrade will never be able to know the types of things well enough to reformat those without the possibility of introducing bugs

**Comment by mitzkia** [comment]
Thanks for the answer. With this I understand why it will not work or not intended here.

**Comment by asottile** [comment]
cheers -- thanks for the issue :tada:
