### ISSUE TITLE
Skip set literal conversion

### ISSUE THREAD

**Issue by ikamensh** [asottile/pyupgrade#200]
Regarding transformation:
set(x for x in y)    # {x for x in y}

I think in some cases it decreases the readability because to understand the type person needs to search for ':' in the body of the literal / expression. 

Consider longer expression: 
set( [ (my_obj.abra, my_obj.foo[123]) for my_obj in some_iterable] ) 
vs 
{(my_obj.abra, my_obj.foo[123]) for my_obj in some_iterable}

Is there a flag to disable this?

**Comment by asottile** [comment]
the tool is opinionated and will not have such an option

note also that the call to `set(generator)` or `set(listcomp)` is considerably slower
