### ISSUE TITLE
pyupgrade transform docstring to raw string

### ISSUE THREAD

**Issue by gma2th** [asottile/pyupgrade#204]
Docstrings with symbols get transformed to raw strings. Is it possible to deactivate invalid escape sequences for docstrings? 
For now I forked the project and add an option to deactivate invalid escape sequences. https://github.com/asottile/pyupgrade/compare/master...gma2th:master

**Comment by asottile** [comment]
It absolutely *MUST* fix those, they will become syntax errors in newer versions of python (3.9+) -- even docstrings -- disabling the option is a very bad idea
