### ISSUE TITLE
Replace subprocess.call with subprocess.run(...).returncode

### ISSUE THREAD

**Issue by verhovsky** [asottile/pyupgrade#205]
https://docs.python.org/3/library/subprocess.html#subprocess.call

**Comment by asottile** [comment]
`subprocess.{call,check_call,check_output}` are not deprecated

**Comment by verhovsky** [comment]
Neither is % formatting but I get your point.

**Comment by asottile** [comment]
% formatting is "old style", and has problems solved by f-strings / .format() -- so yes there is a reason to upgrade those

there is no reason to change call / check_call / check_output
