### ISSUE TITLE
Add --check option

### ISSUE THREAD

**Issue by decaz** [asottile/pyupgrade#210]
It would be nice to have such an option when in place changes are unwanted.

**Comment by asottile** [comment]
(I can't find the dupe at the moment, but there is one somewhere) -- sorry I'm not interested in supporting this option -- thanks for the issue nonetheless!

**Comment by impredicative** [comment]
@asottile I'm seeing a lot of lot of reasonable user requests in this repo that you've closed for no good reason other than they don't suit your whim. Why did you even make this project open source? A `--check` flag would obviously be useful for static analysis purposes as a part of a testing script.

**Comment by asottile** [comment]
> I'm seeing a lot of lot of reasonable user requests in this repo that you've closed for no good reason other than they don't suit your whim. Why did you even make this project open source? 

first off, happy holidays -- glad you found the project useful.

please be respectful
