### ISSUE TITLE
Rewrite six.int2byte

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#211]
> **six.int2byte(i)**
>
> Converts _i_ to a byte. _i_ must be in `range(0, 256)`. This is equivalent to `chr()` in Python 2 and `bytes((i,))` in Python 3.

https://six.readthedocs.io/#six.int2byte

**Comment by asottile** [comment]
it [requires an import](https://github.com/benjaminp/six/blob/aa4e90bcd7b7bc13a71dfaebcb2021f4caaa8432/six.py#L632) so it was not implemented

**Comment by hugovk** [comment]
Aha, so the six docs says it's equivalent to `bytes((i,))` but behind the scenes it really does `struct.Struct(">B").pack`, and so pyupgrade is playing it safe by not rewriting to `bytes((i,))`.

Fair enough, thanks!

**Comment by asottile** [comment]
if they're actually the same it could rewrite it 🤷‍♂ if you want to do the research to prove they're equivalent and then implement it then by all means :) -- it's a one line change in the `SIX_...` mapping

**Comment by hugovk** [comment]
Well, this passes :)

```python
import struct

for i in range(256):
    assert struct.Struct(">B").pack(i) == bytes((i,))
print("Done")
```

See PR #212.

**Comment by asottile** [comment]
cool, are they the same in the exceptional cases too?
