### ISSUE TITLE
'yield from' rewrite unsafe when looping variable is referenced later

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#216]
Consider the example code:

```py
def foo(it):
    item = None
    for item in it:
        yield item
    print("Last item", item)
```

With `--py3-plus`, this is transformed to:

```py
def foo(it):
    item = None
    yield from it
    print("Last item", item)
```

But these are not equivalent. The line `print("Last item", item)` now always prints `None` rather than the last item of the passed iterable. 

This was discovered in more-itertools:

https://github.com/erikrose/more-itertools/blob/8d860c355a1dd900e3a9c5fe1303ddf5a778452f/more_itertools/more.py#L1206-L1223

**Comment by asottile** [comment]
wow, gross :S

**Comment by atugushev** [comment]
@asottile do you have any thoughts/hints on how to fix this? I'd be happy to help.

**Comment by asottile** [comment]
it's going to be a little tricky, but not impossible -- basically the ast visitor needs to check if the loop variable(s) are referenced after the loop -- you might find some prior art from `flake8-bugbear` which has a lint check for this

**Comment by atugushev** [comment]
@asottile 

> B007: Loop control variable not used within the loop body. If this is intended, start the name with an underscore.

Do you mean B007?

**Comment by asottile** [comment]
hmmm maybe I'm misremembering and it's some other plugin 🤔

**Comment by jdufresne** [comment]
Perhaps you're thinking of this discussion? https://github.com/PyCQA/flake8-bugbear/issues/68

Seems I keep bumping into this, ha!

**Comment by atugushev** [comment]
> Perhaps you're thinking of this discussion? [PyCQA/flake8-bugbear#68](https://github.com/PyCQA/flake8-bugbear/issues/68)

@jdufresne, so, I was right 😅

> it's going to be a little tricky, but not impossible -- basically the ast visitor needs to check if the loop variable(s) are referenced after the loop -- you might find some prior art from `flake8-bugbear` which has a lint check for this

@asottile, seems doable with `ast`. I see two cases, reformat if one of the sentences is true:

1. variable(s) hasn't been referenced after the loop
1. variable(s) has been reassigned after the loop

Anything else?

**Comment by asottile** [comment]
I'd just implement 1. and not bother with 2.

**Comment by atugushev** [comment]
I've tried to fix this in #220. Please, review it if you have time 🧐

**Comment by leos** [comment]
Until this is fixed, would it make sense to release an update of `pyupgrade` that stops doing this rewrite? I'd like to run `pyupgrade` across an entire codebase and it feels riskier to do with known issues like this.

**Comment by asottile** [comment]
even with this bug it's very safe -- pyflakes or any other such linter looking for undefined variables will report an issue

**Comment by asottile** [comment]
(the thing this is guarding against is also an extremely rare coding pattern)

**Comment by asottile** [comment]
I've picked up work again on this in #286 -- it's getting there but needs more scope handling
