### ISSUE TITLE
Delete empty lines and empty comment lines after "coding" comment

### ISSUE THREAD

**Issue by verhovsky** [asottile/pyupgrade#219]
Stuff like this

```python
# -*- coding: utf-8 -*-
#  
# This is a Python script that does foo.
```

gets turned into

```python
# 
# This is a Python script that does foo.
```

`pyupgrade` should also remove any lines that are empty, or any lines that have an empty comment.

**Comment by asottile** [comment]
it would have to always do that which isn't really in spirit of the tool (the line below is unrelated ). true blank lines are already handled

**Comment by asottile** [comment]
maybe I didn't explain that so great -- `pyupgrade` would need to always do such rewrites to have stable outcomes so independent of the coding pragma it would need to remove that line which would be undesirable

maybe someone likes starting their files with:

```
#
# I am important
#
```

**Comment by verhovsky** [comment]
That change turns

```python
# coding: utf-8
# 
# I am important
# 
```

into

```python
# I am important
# 
```

and

```
# coding: utf-8
#
#
# I am important
# 
```

into 

```python
#
# I am important
# 
```

and so on. You could delete all blank comments in a `for` loop, but that seems a bit much.

```
#
# coding: utf-8
```

stays the same.


```
#
# I am important
#
```

also stays the same.

Maybe I don't understand what you mean by "stable outcomes". I can imagine that deleting an extra line based on the value of a previous line could cause problems, but I can't actually think of a concrete case. 

I guess you mean what if someone starts all of their code with a leading blank comment except for one file where the put a `# coding: utf-8` comment before the leading blank comment. I would guess the people who just put it there because of the coding comment outnumber those people like 10-1, but if you disagree feel free to reject the pull request.

**Comment by asottile** [comment]
yeah I closed this meaning "I don't want this implemented" -- sorry
