### ISSUE TITLE
autodetect need for "--py3-plus" and "--py36-plus"

### ISSUE THREAD

**Issue by graingert** [asottile/pyupgrade#222]
similar to black's autodetection, if a source file is already syntactically invalid in Py2 upgrade wholly to `--py3-plus`, if a source file is already syntactically invalid in py3.5 upgrade it to `--py36-plus`

**Comment by asottile** [comment]
it originally did this, but it was difficult (and slow) to do so.  I don't want to do this as well as it's easy to _accidentally_ introduce specific syntax and then oops there goes your whole file!

**Comment by graingert** [comment]
> it originally did this, but it was difficult (and slow) to do so. I don't want to do this as well as it's easy to _accidentally_ introduce specific syntax and then oops there goes your whole file!

That's just part of the fun of black-on-save, goodbye `u` prefixes

**Comment by asottile** [comment]
yeah the biggest problem with it is you need to rescan every file making the best case at least twice as slow) - but also the surprise accidental rewrite
