### ISSUE TITLE
Combine --py*-plus options into single --target-version option

### ISSUE THREAD

**Issue by jendrikseipp** [asottile/pyupgrade#226]
I just found this great tool and plan to revamp my codebases with it. The current option design requires a new option per new Python version, which is less than ideal, I think. In my opinion, combining all `--py*-plus` options into a single `--target-version` option would make usage and probably the code easier. The black formatter made the same change (`--py36` -> `--target-version`).

**Comment by asottile** [comment]
it doesn't simplify anything and I don't particularly care what black does

this doesn't make things simpler so I'm going to close it -- thanks for the issue nonetheless
