### ISSUE TITLE
Remove parentheses from @functools.lru_cache() when upgrading to Python 3.8

### ISSUE THREAD

**Issue by verhovsky** [asottile/pyupgrade#229]
https://docs.python.org/library/functools.html#functools.lru_cache

In Python 3.7 you need to write `@lru_cache()`, in 3.8 you can just do `@lru_cache` without the parentheses. See https://bugs.python.org/issue36772

pyupgrade could remove the unnecessary parens for this and other decorators in the stdlib. 

If someone monkey-patches `lru_cache` in their code with an implementation that doesn't handle not having parens this would break their code.

**Comment by asottile** [comment]
sound fine!  I don't expect any to be mocking lru_cache so this should be mostly good -- it will require a `--py38-plus` option but that's no big deal
