### ISSUE TITLE
`OSError` aliases can lead to duplicate entries in `except` clause

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#232]
Hypothesis currently contains a block like the following:

```python
try: ...
except (OSError, IOError, TypeError): ...
```

and while that's not great, `pyupgrade --py3-plus` replaces it with `(OSError, OSError, TypeError)`.  I've just fixed this up manually, but it would be nice if `pyupgrade` rendered this as `(OSError, TypeError)` instead :slightly_smiling_face:

**Comment by mxr** [comment]
I believe this was done in 3c5c9aac3e4d75536ecdca882c8aa79fcc0ea645. Can you clarify which pyupgrade version you're using?

```console
$ pip freeze | grep pyupgrade
pyupgrade==1.25.2
$ pyupgrade --py3-plus -
try: ...
except (OSError, IOError, TypeError): ...
^D
try: ...
except (OSError, TypeError): ...
```

**Comment by Zac-HD** [comment]
:man_facepalming:, 1.21 - apparently my toxenv had gone seriously stale.  Thanks for the quick response!
