### ISSUE TITLE
Replace `from mock import` with `from unittest.mock import`

### ISSUE THREAD

**Issue by verhovsky** [asottile/pyupgrade#233]
https://docs.python.org/library/unittest.mock.html it was added in 3.3 as `unittest.mock` and backported to 2 as `mock`. Some codebases that used to be Python 2, still have `pip install mock` and `import mock` or `from mock import Mock` when they could forgo the install and do `from unittest.mock import Mock`.

**Comment by asottile** [comment]
this is planned at least, there's some progress that's been made here: https://github.com/asottile/reorder_python_imports/issues/80 and here https://github.com/asottile/reorder_python_imports/pull/99

**Comment by mxr** [comment]
Taking a stab at this this weekend
