### ISSUE TITLE
Remove redundant `__ne__` functions

### ISSUE THREAD

**Issue by chris-rands** [asottile/pyupgrade#235]
Thanks for this nice tool. In Python 3, you don't need to implement `__ne__` normally, it will default to the inverse of `__eq__`. Therefore, porting code to Python 3, you could remove `__ne__` functions within classes that only merely invert the `__eq__` results. Could this be implemented here?

**Comment by asottile** [comment]
`__ne__` is still a separate hook as one _could_ implement a more efficient inequality check, so I don't think this is a valid rewrite -- thoughts?

```python
class C:
    def __ne__(self, other):
        print('__ne__')
        return False

    def __eq__(self, other):
        print('__eq__')
        return True


C() == C()
C() != C()

OUTPUT = '''\
__eq__
__ne__
'''
```

**Comment by chris-rands** [comment]
Thanks, yes, agreed, I would not rewrite that. I guess I was thinking of cases where `__ne__` is directly implemented as `not self == other` or `not self.__eq__(other)`. These are the most common cases in my limited experience

**Comment by asottile** [comment]
oh I guess it could be rewritten if it is exactly one of those two yeah

**Comment by asottile** [comment]
so I came up with a case where it results in changed behaviour 🤔 

```python
import pytest


class C:
    def __init__(self, x):
        self.x = x

    def __eq__(self, other):
        print('C.__eq__')
        if not isinstance(other, type(self)):
            return NotImplemented
        return self.x == other.x

    def __ne__(self, other):
        print('C.__ne__')
        ret = self == other
        if ret is NotImplemented:
            return NotImplemented
        else:
            return not ret

class C_fixed:
    def __init__(self, x):
        self.x = x

    def __eq__(self, other):
        print('C.__eq__')
        if not isinstance(other, type(self)):
            return NotImplemented
        return self.x == other.x


class D:
    def __init__(self, x):
        self.x = x

    def __eq__(self, other):
        print('D.__eq__')
        return self.x == other.x

    def __ne__(self, other):
        print('D.__ne__')
        return type(self) != type(other) or self.x != other.x


C_CLS = pytest.mark.parametrize('c_cls', (C, C_fixed))


@C_CLS
def test_eq(c_cls, capsys):
    assert (c_cls(1) == c_cls(1)) is True
    assert (c_cls(1) == c_cls(2)) is False


@C_CLS
def test_eq_D(c_cls, capsys):
    assert (c_cls(1) == D(1)) is True
    assert (c_cls(1) == D(2)) is False


@C_CLS
def test_ne_D(c_cls, capsys):
    assert (c_cls(1) != D(1)) is False
    assert (c_cls(1) != D(2)) is True

@C_CLS
def test_ne(c_cls):
    assert (c_cls(1) != c_cls(1)) is False
    assert (c_cls(1) != c_cls(2)) is True
```

also it turns out, a "correct" implementation of `__ne__` would have to be of the form:

```python
def __ne__(self, o):
    ret = self == o
    if ret is NotImplemented:
        return ret
    else:
        return not ret
```

which, can result in many different forms `(__eq__ vs ==, eschewing the else, is vs ==, etc. etc.)` -- it's a lot to check for

I'm starting to think that maybe this isn't feasible :/

**Comment by chris-rands** [comment]
Thanks, i guess the `NotImplemented` use makes it a special case

Conservatively, one could only change cases where the tokens are exactly in the form `not self == other` or `not self.__eq__(other)`. However, if you think it's not worth the effort then I understand

To give some practical context, I recently helped upgrade a large code-base (>100 classes) for Python 3. There were ~20 cases where `__ne__` was defined and about half of these are the exact form I mentioned above. So, this was easy to change manually

**Comment by asottile** [comment]
the problem with `not self == other` (beyond a correctness issue) is that changes behaviour even more because of this:

```python
C() == 1  # TypeError: not comparable
C() != 1  # False  (`not NotImplemented`) => becomes `TypeError`
```

**Comment by chris-rands** [comment]
Should we close this then?

**Comment by asottile** [comment]
agreed -- thanks for the issue though!  definitely something to look out for manually while porting code to py3
