### ISSUE TITLE
six: ensure_str / ensure_binary / ensure_text of a literal string

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#236]
while we generally can't fix the ensure_* variants, we can for string literals (as we're already doing for `str('...')` for example)

**Comment by thisch** [comment]
Would it be possible to add support for `ensure_*` removal if `pyupgrade` could infer the type of the parameter passed to `ensure_*`?

**Comment by asottile** [comment]
pyupgrade doesn't do any type inference beyond literals -- it's a hard problem

**Comment by thisch** [comment]
too bad! Thx for the quick answer! And using a different library for that, e.g. pylint/mypy,.., that can infer types, is probably still hard, right?

**Comment by asottile** [comment]
neither mypy nor pylint expose their type inference as a library -- plus they're both dog-slow

**Comment by thisch** [comment]
Didn't know that they don't expose their type inference as a lib. IMO the fact that they are slow is not a disqualifier.

**Comment by asottile** [comment]
ok well it is
