### ISSUE TITLE
Possible bug `"/\N{SNOWMAN}".encode("utf-8")` -> `br"/\N{SNOWMAN}"`

### ISSUE THREAD

**Issue by pgjones** [asottile/pyupgrade#241]
Taken from running pyupgrade on Werkzeug's test suite. I think this is the wrong behavior as `"/\N{SNOWMAN}".encode("utf-8")` != `br"/\N{SNOWMAN}"` and therefore this tools should not convert the former to the latter.

**Comment by asottile** [comment]
indeed, this looks like a bug with the string literal converter CC @mxr -- should be an easy fix though :)

**Comment by asottile** [comment]
thanks for the report!  this has been fixed in v1.25.3

**Comment by pgjones** [comment]
Thanks, that was quick!

**Comment by mxr** [comment]
Thanks for the tag and the fix!
