### ISSUE TITLE
Replace open(file, "rU") with open(file)?

### ISSUE THREAD

**Issue by chris-rands** [asottile/pyupgrade#249]
"U" (universal newlines) `mode` was deprecated in Python 3.4 and the `newline=None` argument handles it instead. The default mode is `"r"` anyway

**Comment by chris-rands** [comment]
Thank you!

**Comment by asottile** [comment]
missed some -- added those in #265

**Comment by tacerus** [comment]
> The default mode is "r" anyway

I understand the removal of `U`, but what is the rationale behind removing `r`? Yes, it is not needed, but shouldn't "Explicit is better than implicit." be a valid enough argument to accept it being used?

**Comment by asottile** [comment]
because one way to do things and that's the way I chose
