### ISSUE TITLE
Replace "x and y or z" with "y if x else z"

### ISSUE THREAD

**Issue by davidism** [asottile/pyupgrade#253]
It would be nice to replace the old "fake" ternary expression with the real thing.

In: `value = x and y or z`
Out: `value = y if x else z`

**Comment by davidism** [comment]
Not sure if this is possible to detect safely, since it relies on understanding the intention of the expression and whether it's used in a boolean context.

**Comment by asottile** [comment]
I don't think this is a safe rewrite -- there are cases which do not resolve the same:

```pycon
>>> True and None or 1
1
>>> None if True else 1
>>> 
```

-- that is, the rewrite is only valid if `y` is guaranteed to be truthy

**Comment by davidism** [comment]
I guess that's sort of the point of switching in the first place, to avoid those types of errors. Maybe this is more appropriate as a flake8 plugin? Maybe it already is a flake8 plugin?

**Comment by asottile** [comment]
yeah I agree probably makes more sense as a flake8 plugin -- I don't know of one that does this already though :thinking:

**Comment by asottile** [comment]
thanks for the issue by the way!

**Comment by mbertheau** [comment]
Pylint has this.
