### ISSUE TITLE
Feature request: dry-run option

### ISSUE THREAD

**Issue by SWu** [asottile/pyupgrade#258]
Would it be possible to add an option that doesn't modify any files in-place, but instead just prints a diff of what would have changed and exits 1?

**Comment by asottile** [comment]
Duplicate #210

**Comment by abompard** [comment]
I would like to ask you to reconsider accepting this feature. I'm interested in bringing pyupgrade to my team's tox checks, but bringing in a new tool that changes the code they write is too big of a step. It would make adoption easier for me if I could add a tox test that just reports on files needing upgrades, at least for now.

**Comment by asottile** [comment]
you can always `git checkout -- .`
