### ISSUE TITLE
Not clear how to specify something should be ignored

### ISSUE THREAD

**Issue by AdamWill** [asottile/pyupgrade#266]
So, I sent a [PR for virtualenv](https://github.com/pypa/virtualenv/pull/1651) to fix this code:

    if sys.version_info < (2, 7):
        print("ERROR: {}".format(sys.exc_info()[1]))
        print("ERROR: this script requires Python 2.7 or greater.")
        sys.exit(101)

obviously that code should use `{0}`, not `{}`. But...my pull request fails their CI, because their CI runs `pyupgrade`, and `pyupgrade` complains that the `{0}` should be `{}`...

clearly in this case we need to be able to tell pyupgrade to ignore this line, but I cannot see how to do that. I don't see it in the README or in the code. If there's a way, can it be made more prominent? If there isn't a way...can we have a way? :)

**Comment by asottile** [comment]
there is not, nor will there be -- if you need to exclude a file something utilize [`exclude:`](https://pre-commit.com/#pre-commit-configyaml---hooks)

in this particular case you can also:

```python
msg = ...
print(msg.format(...))
```

**Comment by asottile** [comment]
and just a language tip for you in the future, you'll get much better mileage on issues if you avoid words like "clearly" and "obviously"

**Comment by AdamWill** [comment]
tip for you: maybe don't condescend at people who are trying to help? If you don't want to add this feature, fine (though it is pretty standard for linter-type tools). But no need to snipe at me. It *is* clear that code explicitly intended to be run only when the Python version is less than 2.7 can't possibly use the `{}` syntax, because that syntax *does not work* before 2.7. So I don't think it's reasonable to call me out for using the word.
