### ISSUE TITLE
[PEP526] Upgrade variable type annotations

### ISSUE THREAD

**Issue by leo-dur** [asottile/pyupgrade#272]
Starting from py3.6 python supports a new syntax for variable type annotations (cf [PEP526](https://www.python.org/dev/peps/pep-0526/)).

Former syntax:
```python
a = 23  # type: Optional[int]
```

New syntax:
```python
a: Optional[int] = 23
```

It would be nice that `pyupgrade` upgrade the former syntax to the new one.
Is there any plan to add this feature to `pyupgrade`?

**Comment by asottile** [comment]
there's better tools for this that already exist, for example [retype](https://pypi.org/project/retype/)

I've thought about duplicating their work, but it seems better to just suggest their tool instead -- plus that rewrite would extremely difficult :)

**Comment by leo-dur** [comment]
Thanks for the suggestion.

I've succesfully updated my codebase using [com2ann](https://github.com/ilevkivskyi/com2ann)

**Comment by asottile** [comment]
ah nice, I've heard good things about that one as well :)
