### ISSUE TITLE
f-string roadmap?

### ISSUE THREAD

**Issue by alok** [asottile/pyupgrade#28]
You mention that f-string support was planned in the README, and I'm just curious if you had a rough idea of when that might be.

Big fan of the project by the way.

**Comment by asottile** [comment]
I haven't started working on it yet, unfortunately.

My plan is to start with simple replacements, ones that are unlikely to break other linters:

```python
'foo {}'.format(bar)  # f'foo {bar}'  ## no linebreaks, strictly *shortens* the line
'foo {bar}'.format(bar=bar) # f'foo {bar}'  ## same
# maybe simple attribute accesses
'foo {}'.format(bar.baz)  # f'foo {bar.baz}'
```

And then expand from there!

My current WIP is implementing `%` formatting, where I'll likely be able to reuse some of the logic for f-strings: https://github.com/asottile/pyupgrade/tree/percent_format

But unsurprisingly, I have _copious_ amounts of freetime ;) (sarcasm) so I haven't really had much time to work on either of those adventures.
