### ISSUE TITLE
Perform rewrite of format literals containing \N escapes

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#280]
#279 prevents the crash / incorrect behaviour from #278, but this should be supported -- shouldn't be too difficult but will likely need to reimplement the format string parsing (the stdlib one doesn't notice these escape sequences, probably because they're gone by that point of the parser)

The current behaviours that should be fixed:

1. % format: `'\N{snowman} %s' % (a,)` should become `'\N{snowman} {}'.format(a)`
2. f-string: `'\N{snowman} {}'.format(a)` should become `f'\N{snowman} {a}'`

**Comment by peterjc** [comment]
To anyone else wondering if the second example is wrong, with a literal ``{snowman}`` inside an f-string, the examples all do this:

```pycon
>>> a = "melts"
>>> '\N{snowman} %s' % (a,)
'☃ melts'
>>> '\N{snowman} {}'.format(a)
'☃ melts'
>>> f'\N{snowman} {a}'
'☃ melts'
```

The escape sequence ``\N{name}`` means the character in the Unicode database https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

But nowadays you could just write ☃ directly in the Python code:

```python
>>> a = "melts"
>>> f'☃ {a}'
```

I guess pyupgrade isn't going to replace escaped emoji with literal emoji, is it?

**Comment by asottile** [comment]
there are situations where that is undesirable:

```pycon
>>> '\N{GREEK CAPITAL LETTER ALPHA}' == 'A'
False
>>> 'Α' == 'A'
False
```
