### ISSUE TITLE
encoding parameter to json.loads has been ignored and removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [asottile/pyupgrade#282]
Passing encoding parameter to `json.loads` and `json.load` has been ignored in Python 3 and removed in Python 3.9 . It makes sense for the following transformations to be done as part of python-3 only transformations. I have a fork where I have made an attempt : https://github.com/tirkarthi/pyupgrade/commit/ac89265a83292d68184a5a1995459eb3ad492482 . I just wanted to open an issue to see if it's a good idea for inclusion to open a PR.

```diff
-json.loads(json.dumps({"a": 1}), encoding="utf-8")
+json.loads(json.dumps({"a": 1}))'
```

CPython issue : https://bugs.python.org/issue39377

**Comment by asottile** [comment]
cool patch!  though I'm not sure it really fits with the theme of this tool which is mostly around improved syntax 🤔

**Comment by tirkarthi** [comment]
There were code around removing U in open mode for python 3 and hence the idea. Of course, I would be okay with closing this if it adds more scope than the original idea behind the library.

**Comment by asottile** [comment]
hmmm yeah that one was kinda borderline, I don't really want to go down the slippery slope of handling every parameter deprecation in python.
