### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [asottile/pyupgrade#287]
Can i use this project with `~=` operator?
 
```
pyupgrade~=2.1.0
```

Does it follow [Semantic versioning](https://semver.org)?

**Comment by asottile** [comment]
it depends on what you mean by semantic versioning as there is no public programmatic api and the command line interface is stable

if you look at the release history it should be pretty straightforward to derive what versioning scheme is used

depending on your interpretation of semantic versioning, any change in behaviour (every release for pyupgrade!) would be a breaking change -- but I take a more loose interpretation in that adding new syntax rewriting features is a feature release and fixing bugs in syntax rewriting is a bugfix release

**Comment by asottile** [comment]
and please do not send a PR editing the README indicating that as you've done with a bunch of other projects.  nobody needs that

**Comment by alvassin** [comment]
No problem.  From my point it is a good point to explain how to do deal with breaking changes to make it clear to your users. 

This is done by python developers for example - they have clear process. The same thing have popular libraries, [e.g. aiohttp](https://aiohttp.readthedocs.io/en/stable/faq.html#id10), [aio-pika](https://aio-pika.readthedocs.io/en/latest/#versioning), [alembic and sqlalchemy](https://www.sqlalchemy.org/download.html) and many others.

What versioning do you use? There is no information about it. No information in README. No information in CHANGELOG. I don't think that watching all your commits is a good idea. Of course, you are developer - it can be clear for you, but not to the others.

I've asked such a question and made a PR - because this question is often raises between colleagues - which module is following semver, and which not.

**Comment by asottile** [comment]
what you're doing is borderline spam to inflate your contributions -- if a version is >1 and does not look like a date you can assume it is semver

**Comment by alvassin** [comment]
> what you're doing is borderline spam to inflate your contributions
Hah, I don't need that.

>  if a version is >1 and does not look like a date you can assume it is semver
Nope. You did not get the idea of the semver then.

**Comment by asottile** [comment]
this is spam, stop it

![Capture32](https://user-images.githubusercontent.com/1810591/80124710-7dead100-8545-11ea-94fa-016e6b9f0f9d.PNG)
