### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by RevolutionTech** [asottile/pyupgrade#300]
Does this project have a changelog or release notes?

Maybe I just haven't looked in the right place but I haven't been able to find either. Because of that I find myself reading through the commits whenever I upgrade `pyupgrade` in my projects.

If you aren't writing release notes yet, it would be greatly appreciated if you started authoring these as you make user-facing changes. Thanks for your consideration!

**Comment by asottile** [comment]
I make sure the commit messages are good before merging so you can look at https://github.com/asottile/pyupgrade/commits/master
