### ISSUE TITLE
py3-plus: Suggested rewrite: x.__class__ → type(x)

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#309]
In Python 2, the `__class__` attribute is commonly used to handle both new style and old style classes as `type()` works differently depending on how the class was defined. Python 3 only has new style classes, so it is safe to always use `type()`. As the builtin `len()` is normally preferred over calling `__len__()`, I think the builtin `type()` should also be preferred over `__class__`.

Example input:

```py
class A:
    pass

a = A()
print(a.__class__.__name__)
```

Example output:

```py
class A:
    pass

a = A()
print(type(a).__name__)
```

This is merely a suggestion, please feel to close if not desired.

**Comment by asottile** [comment]
unfortunately [they can have different results](https://www.youtube.com/watch?v=6rAIttnm3Fs) so I don't think this one is safely rewritable :( (despite it being a good idea!)
