### ISSUE TITLE
Rewrite dict(a=b) as {'a': b}?

### ISSUE THREAD

**Issue by alok** [asottile/pyupgrade#31]
Is this supported? If not, could it be?

**Comment by asottile** [comment]
> Is this supported?

Nope! the README details all of the supported operations

> If not, could it be?

It doesn't really fit in with the spirit of `pyupgrade`: "automatically upgrade syntax for newer versions of the language."

In fact, the `dict` builtin was introduced (I think?) in `python2.3` (in some ways making it _newer_ than the dictionary literal syntax).  I don't have access to `python2.1` or `python2.2` but [`python2.0`](https://github.com/asottile/ancient-pythons) doesn't have it and [`python2.3`](https://github.com/deadsnakes/python2.3) does.

That said, I agree that `dict(...)` is generally worse than the literal -- it just doesn't really fit with this tool.

**Comment by asottile** [comment]
Thanks for the issue!

**Comment by mxr** [comment]
@alok I'm using https://pypi.org/project/flake8-comprehensions/ to avoid `dict(...)` although it won't fix your code automatically
