### ISSUE TITLE
Rewrite merge dictionaries

### ISSUE THREAD

**Issue by ad-m** [asottile/pyupgrade#321]
In Python 3.9 or greater (see  PEP-584):

```python
x = {"a":1}
y = {"b":2}
z = x | y
```

In Python 3.5 or greater:

```python
x = {"a":1}
y = {"b":2}
z = {**x, **y}
```

In Python 3.4 or greater:

```python
x = {"a":1}
y = {"b":2}
z = dict(**x, **y)
```

**Comment by asottile** [comment]
indeed!  I had hinted at this in https://github.com/asottile/pyupgrade/issues/228#issuecomment-563119081 but forgot to create an issue for it

**Comment by spookylukey** [comment]
For anyone else like me looking for what happened to this feature, it got removed due to #522 (but also not properly removed due to #536)
