### ISSUE TITLE
Feature request: Add rule for `raise new_exception from old`

### ISSUE THREAD

**Issue by cool-RR** [asottile/pyupgrade#325]
See my [blog post here](https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with).

It would be cool to add a rule to pyupgrade to automatically change this: 

```python
try:
  whatever()
except KeyError:
  raise ValueError('whatever')
```

Into this: 

```python
try:
  whatever()
except KeyError as e:
  raise ValueError('whatever') from e
```

The logic for the AST analysis can be found here: https://github.com/PyCQA/pylint/pull/3695/files#diff-64faa1ebda97badbee8edfd8df8f0fd4R352

**Comment by asottile** [comment]
this isn't in the spirit of the tool
