### ISSUE TITLE
format string with string literal left as-is

### ISSUE THREAD

**Issue by janosh** [asottile/pyupgrade#333]
If you pass `--py36-plus`,

```py
string = "test"
print("{}".format(string))
```
is reformatted to

```py
string = "test"
print(f"{string}")
```

I was therefore expecting

```py
print("{}".format("test"))
```

be reformatted to

```py
print("test")
```

but it's left as is. Is that intentional?

**Comment by janosh** [comment]
This is using v2.7.2.

**Comment by asottile** [comment]
from [the readme](https://github.com/asottile/pyupgrade#f-strings)

> note: pyupgrade is intentionally timid and will not create an f-string if it would make the expression longer or if the substitution parameters are anything but simple names or dotted names (as this can decrease readability).

strings are particularly problematic as they can cause quoting issues, and realistically nobody would use a literal string in a `.format(...)` call (what would be the point?)

**Comment by janosh** [comment]
Thanks for the quick response.
