### ISSUE TITLE
Convert f-strings back to .format()

### ISSUE THREAD

**Issue by smurfix** [asottile/pyupgrade#334]
I have a problem with a large code base that requires translation. Translation and f-strings don't mix well.

Thus I'd like a way to take an f-string and convert it back to a .format()ed expression, ideally with an option to encapsulate the string in `_("…")`.

**Comment by asottile** [comment]
https://github.com/asottile/future-fstrings

**Comment by smurfix** [comment]
Ah. Nice. Thanks for the link.
