### ISSUE TITLE
Do not convert .format() to f-string if wrapped in gettext

### ISSUE THREAD

**Issue by mrname** [asottile/pyupgrade#341]
Currently, f-strings cannot be used for strings that are wrapped in `gettext` (i.e. `_()`). Thus, in these situations, the strings MUST use `.format` instead of f-strings regardless of the python version. The expected behavior here is that strings wrapped in a call to `gettext` should not be upgraded from `.format` to f-strings.

**Comment by asottile** [comment]
`.format(...)` doesn't work for gettext either, your string can't be properly localized since it is dynamic

**Comment by asottile** [comment]
(closing since this is invalid **and** you didn't provide an example)

**Comment by mrname** [comment]
Thanks @asottile you are correct. I was using `babel` which was successfully compiling the strings with `.format` (as opposed to f-strings which actually fail to compile), but neglected to realize that the results are still non-functional despite no exceptions 👍

**Comment by asottile** [comment]
yeah babel also picks up garbage like `_(foo['bar'])` -- it's [not the most clever about things](https://github.com/python-babel/babel/issues/415) there sadly

at a previous employer I wrote a linter for this, but that's lost to closed source now
