### ISSUE TITLE
Python 2-specific special methods

### ISSUE THREAD

**Issue by verhovsky** [asottile/pyupgrade#342]
```python
class A:
    def __unicode__(self):
        return "some string"
```

could become 

```python
class A:
    def __str__(self):
        return "some string"
```

though that's not a safe transformation, since `__str__` in Python 2 is what `__bytes__` is for Python 3.

Searching for "`__`" in https://docs.python.org/3/whatsnew/3.0.html, it seems like `__cmp__`, `__getslice__`, `__setslice__`, `__delslice__`, `__oct__` and `__hex__`, `__members__`, `__methods__` could be completely removed and `__nonzero__` can be renamed to `__bool__`. This won't be safe if a method is being used in the implementation of some other method that won't be removed.

Maybe pyupgrade should warn about them, but I guess that's a job for a linter rule.

**Comment by asottile** [comment]
this isn't intended to replace 2to3
