### ISSUE TITLE
Add a flag for disabling rules

### ISSUE THREAD

**Issue by moshe** [asottile/pyupgrade#345]
Hi @asottile  👋
There is any plan to add a flag to pyupgrade to ignore some fixers?
I really want to use this tool but I want to disable one rule

Thanks,
Moshe

**Comment by asottile** [comment]
could you describe your use case? so far the only disable options are for things which can break code

**Comment by moshe** [comment]
Yes, I want to disable the namedtuple rewrite: `typing.NamedTuple / typing.TypedDict py36+ syntax`. Sometimes I find writing namedtuple in a single line more useful and readable. especially for namedtuples with a low amount of properties

**Comment by asottile** [comment]
nah

**Comment by moshe** [comment]
ooook

**Comment by asottile** [comment]
feel free to fork, I'm not going to maintain opinions
