### ISSUE TITLE
Feature request: Add command line option to supress f-string conversion

### ISSUE THREAD

**Issue by PhilippSelenium** [asottile/pyupgrade#351]
https://github.com/asottile/pyupgrade#f-strings

I would like to apply certain fixes step by step or leave them out at all.

Maybe
```
--keep-format
```

**Comment by PhilippSelenium** [comment]
sorry I saw that I can get the desired result by using
```
--py36-plus
```

**Comment by asottile** [comment]
you have to opt in to f-strings so... don't do that?
