### ISSUE TITLE
super() rewrite isn't done inside list comprehension 

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#352]
Example input:

```py
class A:
    def one(self):
        return [super(A, self).other() for _ in range(3)]
```

Expected output:

```py
class A:
    def one(self):
        return [super().other() for _ in range(3)]
```

Actual: no change

This was discovered in real life code:

https://github.com/FactoryBoy/factory_boy/blob/b205a19787f2eb9927beae4def01acc5d8f9c45c/factory/declarations.py#L719-L722

(Arguably, the author should factor `super()` out of the loop. Had pyupgrade modified this line it would have been highlighted.)

**Comment by asottile** [comment]
you're about to learn something :)

`super()` does not work in comprehensions
