### ISSUE TITLE
Do not replace % formatting if it requires escaping curly braces

### ISSUE THREAD

**Issue by ThiefMaster** [asottile/pyupgrade#354]
For example, this snippet:

```python
def convert_link_to_latex(instr):
    dom = html5parser.fragment_fromstring(instr)
    return '\\href{%s}{%s}' % (latex_escape(dom.get('href'), ignore_math=True), dom.text)
```

gets converted to this abomination:

```python
def convert_link_to_latex(instr):
    dom = html5parser.fragment_fromstring(instr)
    return '\\href{{{}}}{{{}}}'.format(latex_escape(dom.get('href'), ignore_math=True), dom.text)
```

I think we can all agree that this is much worse than the original. 

While there's `--keep-percent-format`, I generally do want to avoid percent formatting, but it seems reasonable that it should avoid making a change if it requires escaping (just like code formatters generally use the string quoting style that requires as little quote escaping inside the string as possible).

**Comment by asottile** [comment]
while the string is slightly longer, I don't think this is worse than mixing string formatting styles

**Comment by ThiefMaster** [comment]
IMO you need to look thrice to see how many curly braces you actually get in the end...
