### ISSUE TITLE
Provide better options to integrate with CI

### ISSUE THREAD

**Issue by ThiefMaster** [asottile/pyupgrade#356]
There's a non-zero exit code if something was changed (according to https://github.com/asottile/pyupgrade/issues/310#issuecomment-630282643), but when running multiple tools (isort, flake8, etc.) then getting files modified in-place is a huge mess because any command that runs later will then act on already-modified code.

Having a `--check` option that prevents files from being written and maybe even a `--diff` option that prints a diff of what would be changed would help with this a lot.

I wouldn't mind sending a PR for this, but before spending time on this I'd like to know if this will actually get accepted. :)

In case you wonder why I want to run this in CI: A pre-commit hook is great, but only when people use it. Sometimes you get PRs from people who don't bother setting up a proper development environment so they never run the pre-commit hooks. So I'd like CI to fail in such cases.

**Comment by asottile** [comment]
use `pre-commit run --all-files --show-diff-on-failure`

please search the issue tracker next time: #310 #210 (and many more)
