### ISSUE TITLE
Like 2to3, pyupgrade breaks proper python2 code

### ISSUE THREAD

**Issue by perkinslr** [asottile/pyupgrade#357]
Consider the following, valid python2 program.

    a = 'some bytes'
    b = u'some unicode string'
    c = b'some bytes too'

    print(a)
    print(b)
    print(c)

Our data types are `str`, `unicode`, `str`.  

After running `pyupgrade`, this becomes

    a = 'some bytes'
    b = 'some unicode string'
    c = b'some bytes too'

    print(a)
    print(b)
    print(c)

And our data types are now `unicode`, `unicode`, `bytes` (I've replaced `str` with `unicode` here to be more clear that the datatype of `a` has **changed**, `str` in python3 is the `unicode` type from python2).  Note that, post conversion, it is **impossible** to reconstruct the original program by tooling, it must be done by hand (in practice, it must be restored from backup).

Consider if this tried to send `a` and `c` to a network socket.

Most python2 programs did not type-prefix byte string constants (the `b''` prefix was added in python2.6, 12 years ago, but much legacy python2 code is older than that, and using the `b''` prefix didn't catch on until much later).  

While `pyupgrade` makes broken python2 programs *function* under python3, it is totally useless for lifting (or even assisting the lifting of) serious python2 programs.  (Especially any that dealt with networking or other areas where the distinction between unicode and bytes was carefully maintained).

Given that the core python team royally whiffed on getting us a code lifting tool (as the title says, 2to3 does the same thing, in exactly the same way, despite some of us raising a fuss about it), it's be super neat if this tool got it right.  Assume the initial programmer was competent.  If you're asked to lift a garbage program, don't feel bad about generating garbage output.  If you're asked to lift a valid program *don't break it*.

**Comment by hugovk** [comment]
Are you running pyupgrade with one of the `--py3*` switches?

```
  --py3-plus, --py3-only
  --py36-plus
  --py37-plus
  --py38-plus
```
They will produce Python 3 code and remove Python 2 stuff.

When I run pyupgrade on the initial code with no switches, nothing is changed.

See https://github.com/asottile/pyupgrade#unicode-literals.

**Comment by asottile** [comment]
@perkinslr you're wrong, it doesn't change that file:

```console
$ cat t.py 
a = 'some bytes'
b = u'some unicode string'
c = b'some bytes too'

print(a)
print(b)
print(c)
$ pyupgrade t.py
$ cat t.py 
a = 'some bytes'
b = u'some unicode string'
c = b'some bytes too'

print(a)
print(b)
print(c)
```

unless you explicitly tell it "I'm done with python 2":

```console
$ pyupgrade --py3-plus t.py
Rewriting t.py
$ cat t.py 
a = 'some bytes'
b = 'some unicode string'
c = b'some bytes too'

print(a)
print(b)
print(c)
```

**Comment by perkinslr** [comment]
> Are you running pyupgrade with one of the `--py3*` switches?
> 
> ```
>   --py3-plus, --py3-only
>   --py36-plus
>   --py37-plus
>   --py38-plus
> ```
> 
> They will produce Python 3 code and remove Python 2 stuff.
> 
> When I run pyupgrade on the initial code with no switches, nothing is changed.
> 
> See https://github.com/asottile/pyupgrade#unicode-literals.

Yes, sorry, should have specified the switches used (I assumed that would be obvious given the talk of python2 to python3, but explicit is better than implicit, so here goes).

Here's a simple program which exhibits the wrong behavior.  Convert it via `python3.8 -m pyupgrade --py38-plus temperature.py` (or any of the `--py3*` switches).  Then try to run the result on python3 (any version).

    #!/usr/bin/python2
    from __future__ import print_function

    import socket
    import sys
    import random

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(('', int(sys.argv[1])))
    s.listen(5)
    while True:
        c = s.accept()[0]
        c.send("Temperature in Kelvin: %.2f\n" % random.random())
        c.close()

When you connect to whatever port you specify via `sys.argv[1]`, it will crash with `TypeError: a bytes-like object is required, not 'str'`.  

As an aside, I did read the [unicode-literals](https://github.com/asottile/pyupgrade#unicode-literals) section, but it was the [format-specifiers](https://github.com/asottile/pyupgrade#python27-format-specifiers) which clued me in to the probable error.  The `unicode-literals` change is fine.  It's even required for python3 < python3.3 (as the `u'unicode'` prefix was invalid from 3.0 through 3.2.x).  

The "question" is, if a file does not use `from __future__ import unicode_literals`, why do the bytes literals in the file not get the `b'bytes'` prefix in the modified file?

**Comment by asottile** [comment]
the `--py3*` switches are "I already run on python3 and I don't care about old things" not "please port me to python3"

**Comment by perkinslr** [comment]
Ah, apologies.  I misunderstood the purpose of this tool.  It is simply to "prettify" the code once lifting is complete.  Might be worth mentioning that those flags assume the *source* language version is python3, rather than the *destination* language version.

**Comment by asottile** [comment]
if you read the upgrades it should be blatantly obvious that it's removing compatibility (removing `u`, new `super()`, removing `six`, f-strings, etc.)
