### ISSUE TITLE
not catching %-formatting in function argument

### ISSUE THREAD

**Issue by paulhfischer** [asottile/pyupgrade#367]
when running `pyupgrade --py37-plus` on a file containing
```python
myfun('info: %s' % info))
```
it doesn't change it to the f-string variant
```python
myfun(f'info: {info}')
```

is there a specific reason for this?

**Comment by rkm** [comment]
Seems to be a duplicate of #256 and #78

**Comment by paulhfischer** [comment]
thanks, just searched for "%" in the issue tracker and not for "Percent"
