### ISSUE TITLE
replace `typing.Text` with `str` for `--py3-plus`

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#374]
Perhaps another example of the same idea, replace `typing.Text` with `str` for `--py3-plus`.

Example input:

```py
if False:
    from typing import Text


def f():
    # type: () -> Text
    return "hello"
```

Example diff:

```diff
--- before.py
+++ after.py
@@ -3,5 +3,5 @@
 
 
 def f():
-    # type: () -> Text
+    # type: () -> str
     return "hello"

```

_Originally posted by @jdufresne in https://github.com/asottile/pyupgrade/issues/343#issuecomment-750930060_

**Comment by MarcoGorelli** [comment]
Nice - I'm having a go at this, should have a PR ready tomorrow

**Comment by asottile** [comment]
actually, please wait a day or two -- I'm in the middle of rewriting (it'll be 10000x easier afterwards)

**Comment by asottile** [comment]
if you want, base off of `origin/split`

**Comment by MarcoGorelli** [comment]
Glad I commented now - and sure, will do, thanks!

**Comment by asottile** [comment]
ok have at it!

I'd probably base it on https://github.com/asottile/pyupgrade/blob/75df9db53c944b493c070172d714c4d70b397bd6/pyupgrade/_plugins/typing_pep585.py

for the tests, they can go in `tests/features/...` (I forgot to move the existing tests into there, will be doing that soon)
