### ISSUE TITLE
%-formatting not fixed if the operator is on a subsequent line

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#377]
```python
a = 1
b = (
    "a=%s"
    % (a,)
)
c = (
    "a=%s" % (a,)
)
```

While `b` and `c` are equivalent, only the latter is converted by `pyupgrade --py36-plus`.  We do (or did) have many of these in Hypothesis, arising from formatting long error messages and so on... I've fixed them by hand, but thought you might want it reported.

**Comment by asottile** [comment]
yep, this is known -- along with some other cases documented here: https://github.com/asottile/pyupgrade/blob/d9e1f0886099fdb2d11e11f3d4fc1f4f11ef5fdf/tests/percent_format_test.py#L276

some are particularly difficult to tokenize properly so they've been deferred to later

**Comment by Zac-HD** [comment]
All good.  Thanks again for `pyupgrade` 😀
