### ISSUE TITLE
[Feature Request] os -> pathlib

### ISSUE THREAD

**Issue by MartinThoma** [asottile/pyupgrade#379]
Hi,

Thank you for this awesome project! I love it 😍 

One extension you might want to consider is moving os to [pathlib](https://docs.python.org/3/library/pathlib.html). It's available since Python 3.4, but people (including myself) don't use it because they are just so used to `os`.

**Comment by asottile** [comment]
this isn't possible without solving the halting problem

plus I personally think pathlib is a fad

**Comment by MartinThoma** [comment]
I've just remembered https://pypi.org/project/flake8-pathlib/ - why do you think one needs to solve the halting problem?

> I personally think pathlib is a fad

Oh, why that?

**Comment by asottile** [comment]
> why do you think one needs to solve the halting problem?

_finding_ problems is almost always trivial, replacing them without introducing bugs is impossible to do safely

consider this:

```diff
 from ext_lib import g
 def f(x):
-    return g(os.path.join(x, 'mydir'))
+    return g(Path(x) / 'mydir')
```

this could be unsafe for a number of reasons:

- it cannot be determined statically whether `g` takes `Path`s
- `join` can act differently in some cases than `Path`
- sure you could wrap it in `str(...)` but I'd argue that's worse

> Oh, why that?

- the overload of the `/` operator is gross
- the absolute fanboyism that's developed around it
- slower than os.path
- it's toxic (not unlike async) -- want to use pathlib? now you have to rewrite every one of your apis and every one of your dependencies apis to support it
