### ISSUE TITLE
Support translating TypedDict's with 'total' option

### ISSUE THREAD

**Issue by neiljp** [asottile/pyupgrade#381]
Currently pyupgrade skips converting a TypedDict to python 3.6 format if there is a `total` option.

https://www.python.org/dev/peps/pep-0589/#totality

**Comment by asottile** [comment]
appears to be worse than that, `pyupgrade` produces incorrect results:

```diff
 from typing import TypedDict
 
-C = TypedDict('C', x=int, total=False)
+class C(TypedDict):
+    x: int
+    total: False
```

**Comment by asottile** [comment]
oh actually, hmm mypy rejects that so maybe that's not a problem:

```console
$ mypy t.py
t.py:3: error: Unexpected arguments to TypedDict()
```

**Comment by neiljp** [comment]
That looks like incorrect `TypedDict` format, did you mean `dict(x=int)` or `{'x':int}` in there?

**Comment by asottile** [comment]
nah typeddict has two syntaxes:

```python
D = TypedDict('D', x=int)
```

and

```python
D = TypedDict('D', {'x': int})
```

**Comment by neiljp** [comment]
The former is not mentioned at all in https://www.python.org/dev/peps/pep-0589/#alternative-syntax, but is present in the python 3 library docs at https://docs.python.org/3/library/typing.html#typing.TypedDict . Was there another PEP?

**Comment by asottile** [comment]
PEPs are just the proposal documents and not living documentation.  often as things are being implemented the implementation differs slightly from the specification.  PEP 484 is maybe an exception to this though it is still "in progress" via status

**Comment by neiljp** [comment]
For reference, my code had the second form (dict of name/type mappings) with total=False and it didn't translate it.
If the non-dict form is valid but is badly transformed - even if mypy does not validate it - isn't this a bug?

**Comment by asottile** [comment]
the non-dict form with `total=...` is not valid, but without `total` it is valid
