### ISSUE TITLE
Consider not applying PEP 604 by presence of __future__ 

### ISSUE THREAD

**Issue by hannseman** [asottile/pyupgrade#387]
Applying PEP 604 on non 3.10 code will crash on libraries depending on introspection of type hints using `typing.get_type_hints`. This should apply for libraries like https://github.com/samuelcolvin/pydantic  and https://github.com/konradhalas/dacite.

Example:
```python
>>> from __future__ import annotations
>>> import typing
>>> class Snake(typing.NamedTuple):
...     name: str | None
...
>>> typing.get_type_hints(Snake)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1410, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 277, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 533, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
class Snake(typing.NamedTuple):
    name: str | None
```

My proposal is to only rewrite to PEP 604 when the minimum version is 3.10.

**Comment by asottile** [comment]
I'd rather use this in python3.7 so I'm gong to reject this proposal

**Comment by antonagestam** [comment]
@asottile Would you consider enabling/disabling of this with a feature flag in non-3.10 Python? This will introduce breaking code changes for all essentially any runtime usage of type hints.

... and if not, would you consider a "documentation fix" saying e.g. "this project introduces changes that break runtime introspection of type hints"?

**Comment by asottile** [comment]
runtime types should use `Annotated` anyway, I don't consider their current implementation valid

**Comment by antonagestam** [comment]
@asottile So would you consider a patch that documents the breakage?

Also, this isn't in regard to runtime types that differ from static types. How do you propose using `Annotated` with `Optional[int]`? Are you saying one should use something like `Annotated[Optional[int], "What here?"]`?

**Comment by asottile** [comment]
#389 probably does what you want

**Comment by antonagestam** [comment]
@asottile Hey, thanks for reconsidering and fixing! 🙏
