### ISSUE TITLE
PyUpgrade should remove unused import 

### ISSUE THREAD

**Issue by Czaki** [asottile/pyupgrade#391]
In my case PyUpgrade when the update signature makes one import unused. I think that it also should be fixed. 

Here example: [`2420566` (#182)](https://github.com/4DNucleome/PartSeg/pull/182/commits/2420566529df842cbadd7a48b44e7454eef5c7c8)

**Comment by mondeja** [comment]
The same happens for `io.open`: when removed `io`, `import io` statements raises flake8 F401 rule break.

**Comment by asottile** [comment]
there is insufficient knowledge of symbol use to remove unused imports -- I'd suggest using autoflake to accomplish such goals (and even that is imperfect)

pyupgrade aims to not break your code

**Comment by provinzkraut** [comment]
Currently pyupgrade *is* removing some imports, ("Remove unnecessary py3-compat imports" and "remove six compatibility code") so what's the reason for not doing it here? I'm not sure about the "insufficient knowledge of symbol use" in this case. If pyugrade will replace every instance of a `List` annotation with `list` then it has sufficient knowledge of the usage of `List`: It's not used. Or am I missing something here?

**Comment by asottile** [comment]
because they are guaranteed to be unused

**Comment by asottile** [comment]
because pyupgrade cannot verify all usages
