### ISSUE TITLE
how to run this tool on multiple files without git?

### ISSUE THREAD

**Issue by thelittlebug** [asottile/pyupgrade#396]
hi,

the topic explains the issue. we are not able to switch to git. 

1. we are not able to use pre-commit.
2. shopt is not usable inside tox.ini

**Comment by asottile** [comment]
> shopt is not usable inside tox.ini

tox is just a command runner, you can `bash -c '...'` or you can `python -c '...'`

**Comment by hugovk** [comment]
I use `pyupgrade **/*.py`
