### ISSUE TITLE
PEP604 rewrites inside typing.cast()

### ISSUE THREAD

**Issue by wwuck** [asottile/pyupgrade#399]
I noticed that pyupgrade doesn't change any PEP604 rewrites for `Optional` hints inside `typing.cast()`. Is this not supported by the implementations of PEP604?

eg.
```python
cast(Optional[str], mystring)
```
Doesn't seem possible to write it as
```python
cast(str | None, mystring)
```

I tested with a py38 venv and `from __future__ import annotations` with `pyupgrade --py310-plus`.

It doesn't seem to mind if the type hints are written as a string `cast('str | None', mystring)` although I should check if that is actually casting properly for mypy.

**Comment by asottile** [comment]
```pycon
>>> from typing import cast
>>> cast(int | None, 'foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by asottile** [comment]
mypy doesn't support it outside of annotations yet and python3.10 isn't finalized
