### ISSUE TITLE
Support for converting type comments into annotations

### ISSUE THREAD

**Issue by PeterJCLaw** [asottile/pyupgrade#403]
Thanks for this tool, it's really handy.

It would be great if type comments (like `x = foo() # type: str`) could be converted to inline annotations (`x: str = foo()`). Is this something you'd be interested in adding/is it possible to add?

**Comment by asottile** [comment]
[`com2ann`](https://github.com/ilevkivskyi/com2ann) is probably what you're looking for

**Comment by gdementen** [comment]
Even though the functionality exists elsewhere, it would be a lot more useful IMO if it was integrated into a single tool like pyupgrade. Both the disoverability and the ease of use would be higher.
