### ISSUE TITLE
ENH replace string literals in type annotations if Python3.7+ and annotations is imported

### ISSUE THREAD

**Issue by MarcoGorelli** [asottile/pyupgrade#404]
From [PEP 563](https://www.python.org/dev/peps/pep-0563/)

> The use of string literals will no longer be required in this case. However, there are APIs in the typing module that use other syntactic constructs of the language, and those will still require working around forward references with string literals. The list includes:
> 
> 
>     type definitions:
> 
>     aliases:
> 
>     casting:
> 
>     base classes:

Would this be a welcome addition to pyupgrade?

**Comment by asottile** [comment]
dupe #255
