### ISSUE TITLE
Dropping str() for functions taking os.PathLike (PEP 519)

### ISSUE THREAD

**Issue by The-Compiler** [asottile/pyupgrade#405]
Python 3.6 [introduced](https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol) an `__fspath__` method ([PEP 519](https://www.python.org/dev/peps/pep-0519/)), which allows functions like the `open` builtin to directly take `pathlib.Path` objects.

In other words, with Python 3.4/3.5, `open(str(path))` was required, while with 3.6+, `open(path)` works. The same goes for any other function taking `os.PathLike` and any other object defining `__fspath__`.

Not sure how feasible this is to do automatically, though.

**Comment by asottile** [comment]
it's impossible to do statically (you need type information)
