### ISSUE TITLE
Suggestion: Convert `a = 1  # type: int`  type annotations to `a: int = 1`  for python >= 3.6

### ISSUE THREAD

**Issue by klieret** [asottile/pyupgrade#410]
If you use `mypy` or just want to help your IDE understand your types better, you often want to explicitly set the types of your variables (especially if you start with an empty list but already want to specify the type of the content).

In python < 3.6 you do that with comments of the form `# type: int`, e.g.

```python
a = 1  # type: int
```

whereas python >= 3.6 has

```python
a: int = 1
```

cf eg [the mypy cheatsheet](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

It would be very cool to do this conversion automagically with pyupgrade :)

**Comment by MarcoGorelli** [comment]
Hey @klieret 

Dupe of #403 ?

**Comment by klieret** [comment]
Oh thanks! Must have forgotten to search the closed issues...

Great to also learn about [com2ann](https://github.com/ilevkivskyi/com2ann), but I'd still vote for including this functionality in `pyupgrade` as well.
