### ISSUE TITLE
Inconsistent behavior when collapsing Optional and Union

### ISSUE THREAD

**Issue by cdce8p** [asottile/pyupgrade#411]
I noticed a small issue when collapsing Optional and Union over multiple lines.
In case this is intended behavior, please ignore the issue.

In the example, the annotations for `var_1` and `var_2` are equivalent. However, after running `pyupgrade --py38-plus` the one for `var_1` has an extra set of parentheses.
I've seen this example in black formatted code, where `int` and `str` where long class / exception names that caused the line break for `var_1`.

Tested with version `2.10.1`.

```py
from __future__ import annotations
from typing import Optional, Union

def func(
    var_1: Optional[
        Union[int, str]
    ] = None,
    var_2: Optional[Union[int, str]] = None,
) -> None:
    pass
```

```py
from __future__ import annotations

def func(
    var_1: None | (
        int | str
    ) = None,
    var_2: int | str | None = None,
) -> None:
    pass
```

**Comment by asottile** [comment]
when the annotation spans multiple lines the only safe thing we can do is insert parentheses

otherwise it can cause `SyntaxError`s

**Comment by cdce8p** [comment]
> when the annotation spans multiple lines the only safe thing we can do is insert parentheses
> 
> otherwise it can cause `SyntaxError`s

Of cause. The issue was more to suggest a general replacement. Unions don't support `and`, so the multiline example could be safely converted to `int | str | None`.

**Comment by asottile** [comment]
like I said, it can't safely be transformed in all cases so pyupgrade does the only possible sane thing it can do and uses parentheses.  A human or other formatting tool can fix the rest if desired

```python
Union[
    # what
    a, b
    # now?
]
```
