### ISSUE TITLE
Replacing if/elif with pattern matching

### ISSUE THREAD

**Issue by ewjoachim** [asottile/pyupgrade#413]
I wondered if you'd be interested in a contribution that replaces `if/elif` constructs with [PEP 622 pattern matching](https://www.python.org/dev/peps/pep-0622/) when it's sensible.

E.g.
```python
There's a continuum of things that we could implement depending on how far we want to go.
# simple replacement:
if foo == "bar":
	a()
elif foo == "baz":
	b()
else:
	c()

# becomes
match foo:
	case "bar":
		a()
	case "baz":
		b()
	case _:
		c()

# more complex
if isinstance(foo, "Foo") and foo.bar == "bar":
	baz = foo.baz
elif ...

# may become
match:
	case Foo(bar="bar", baz=baz):
	...
```

I'd be tempted to say that match/case only starts to shine when you have to use `elif`, so it wouldn't replace if statements even if they have a corresponding match/case.

Finally I admit I'm suggesting this as a way to have fun developing, I know it's not actually solving a real world problems and "if it ain't broken"...

Idea credit: @mgu

**Comment by asottile** [comment]
not going to happen, I think match is bad
