### ISSUE TITLE
pep 604 typing rewrites: incompatible with Pydantic objects.

### ISSUE THREAD

**Issue by sodul** [asottile/pyupgrade#415]
See https://github.com/samuelcolvin/pydantic/issues/2597 for details.

We use Python 3.9 with`from __future__ import annotations`. Pyupgrade will convert `Union[]` and `Optional[]` to the new pep 604 notation, which is very useful in the vast majority of our code but this conflicts with Pydantic which runs `eval()` on the types at runtime and where `pep 604` is not available, causing a `TypeError` during import time.

```
  File "/Users/stephane/my/module.py", line 45, in <module>
    class MyClass(pydantic.BaseModel):     # pylint: disable=no-member
  File "pydantic/main.py", line 247, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 218, in pydantic.typing.resolve_annotations
    params = new_params
  File "/Users/stephane/.pyenv/versions/3.9.2/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/stephane/.pyenv/versions/3.9.2/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

```py
from __future__ import annotations
import pydantic

class User(pydantic.BaseModel):     # pylint: disable=no-member
    first_name: str | None = None
    last_name: str | None = None
```

Would it be possible to disable the rewrite for Pydantic classes? At the moment we have to be careful about using Pyupgrade and undo typing rewrites on these classes.

Thank you!

**Comment by asottile** [comment]
not to say RTFM but [RTFM](https://github.com/asottile/pyupgrade#pep-604-typing-rewrites)

**Comment by sodul** [comment]
@asottile do you mean the `--keep-runtime-typing` option? It disables the new annotation for the entire file, not just the pydantic lines.

The request here is that this code:
```py
from __future__ import annotations
import pydantic

FOO: Optional[str] = None

class User(pydantic.BaseModel):
    first_name: Optional[str] = None
```

Would become:
```py
from __future__ import annotations
import pydantic

FOO: str | None = None

class User(pydantic.BaseModel):
    first_name: Optional[str] = None
```

We are looking into making pyupgrade part of our development workflow and since 99.9% of our type declarations are compatible with the new typing notation, we would like to be able to not worry about the 0.1% of the lines that are breaking because of pedantic. So we would like to be able to upgrade the syntax on the 99.9% of the lines that will be fine while keeping the 0.1% safe.

If that's beyond the scope of pyupgrade, I do understand completely. This is mostly a pydantic problem and we have filed a separate bug report on the pydantic project.

Sorry of my original bug report want not clear enough. No need to reopen we are following up on the pydantic side.

**Comment by asottile** [comment]
correct, that flag is for if you're using runtime typing such as with pydantic

**Comment by lafrech** [comment]
For the record, same issue with SQLAlchemy. See https://github.com/sqlalchemy/sqlalchemy/issues/9110.

Same "fix": use `--keep-runtime-typing`.
