### ISSUE TITLE
Remove unnecessary `__future__` imports

### ISSUE THREAD

**Issue by JelleZijlstra** [asottile/pyupgrade#42]
Could pyupgrade remove `__future__` imports that are no longer necessary? For example, `absolute_import` when running in Python 3 mode.

**Comment by asottile** [comment]
I'm currently handing that through https://github.com/asottile/reorder_python_imports

**Comment by asottile** [comment]
Thanks for the issue -- closing given the above comment -- if you have additional followup please comment and I'll be happy to reopen :)

**Comment by jdufresne** [comment]
Thanks, but that alternative tool comes with a lot additional side effects that one may not want when simply upgrading to a Python 3 only codebase. Would you be willing to reconsider?

**Comment by asottile** [comment]
could you clarify what negative side-effects? it just sorts your imports

**Comment by jdufresne** [comment]
The side effects aren't negative, just additional. It just seems like an opinionated, unrelated format change to lump in with Python 3 only syntax change. If I'm creating a commit to upgrade to Python 3, I don't want to also mix in import sorting at the same time.

**Comment by asottile** [comment]
easy to split up though:

commit 1: sort imports
commit 2: to python 3.x

if you don't like the particular sorting it imposes you can always run another sorter afterwards

**Comment by jdufresne** [comment]
I agree that one can work around the additional formatting, but that seems like having the user do work for the tool instead of having the tool work for the user.

It was only a suggestion. No worries.

**Comment by asottile** [comment]
the main reason it's _hard_ is the work to remove the imports requires almost all of the work necessary to sort it -- and having two tools do the same thing when one does it already very well seems not the most maintainable solution :man_shrugging:

**Comment by hugovk** [comment]
Was just about to report this, some redundant `from __future__ import division` were left behind.

Shall we make a `pyupgrade2` wrapper around `reorder_python_imports` and `pyupgrade`?

Although some projects don't want any automatic import sorting.

It seems a bit of a daft question, but is it possible to run `reorder_python_imports` without reordering?

I see the [`# noreorder`](https://github.com/asottile/reorder_python_imports#using--noreorder) comment, but perhaps a `--no-reorder` switch?

**Comment by asottile** [comment]
`# noreorder` stops processing from that point onwards, `--noreorder` would just be a noop on the whole file.

as far as I'm concerned there's already a wrapper around both: [pre-commit makes it trivial to compose linters / formatters](https://github.com/asottile/pyupgrade/blob/bf9aa8f3fdabcd34542ba1de829759b6addb4bef/.pre-commit-config.yaml#L17-L24)

**Comment by asottile** [comment]
I had a change of heart, #202 implements this
