### ISSUE TITLE
Some format-to-fstring involving arithmetics rewrites reduce readability

### ISSUE THREAD

**Issue by ThiefMaster** [asottile/pyupgrade#422]
Recently pyupgrade started being more aggressive when adding f-strings.

```py
$ cat /tmp/pyup.py
remaining = '{:02}:{:02}'.format(remaining_seconds // 60, remaining_seconds % 60)

$ pyupgrade --py39-plus /tmp/pyup.py
Rewriting /tmp/pyup.py

$ cat /tmp/pyup.py
remaining = f'{remaining_seconds // 60:02}:{remaining_seconds % 60:02}'
```

While readability is somewhat subjective, I find the new style terrible and much harder to read..

What about adding some parentheses for such cases?

```py
remaining = f'{(remaining_seconds // 60):02}:{(remaining_seconds % 60):02}'
```

Even though I still think that this is worse than what there was before.

Alternatively, what about some logic that either adds parentheses or skips the conversion altogether if it would result in code where you end up with spacing that doesn't match the semantics? In this case it would be "whenever the expression has top-level (outside parentheses) whitespace AND a `!` or `:` format modifier".

Another good example (probably not relevant for pyupgrade though) is with kwargs: `foo(bar=stuff or 'else', x=y)` looks very strange because one reads `bar=stuff` at first and only afterwards notices that there's more, while something like `foo(bar=(stuff or 'else'), x=y)` is much clearer

**Comment by asottile** [comment]
> While readability is somewhat subjective,

it's 100% subjective, there's nothing actionable here

feel free to add parentheses to your code yourself, it will not be rewritten
