### ISSUE TITLE
Heads up: Python 3.10 annotations need to be moved to 3.11

### ISSUE THREAD

**Issue by henryiii** [asottile/pyupgrade#425]
The steering council just bumped the PEP 585 change to 3.11, due to this thread: https://github.com/samuelcolvin/pydantic/issues/2678 - see https://mail.python.org/archives/list/python-dev@python.org/thread/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/ . Looks like some of the changes currently activated with `--py310-plus` need to be moved to `--py311-plus` before October hits.

**Comment by asottile** [comment]
yeah I already know -- turns out you can buy peps with twitter likes -- who knew!
