### ISSUE TITLE
get_type_hints breaks due to `object is not subscriptable`

### ISSUE THREAD

**Issue by Yoni-Mantzur** [asottile/pyupgrade#428]
Hey, I'm not sure if this "bug" should be here or in typing repo, but I'll give it a shot:

I have this module:

**foo.py**
```
from __future__ import annotations

from typing import List, get_type_hints


def func(a: List[str]) -> None:
    pass

print(get_type_hints(a))
```

Running this results with `{'a': typing.List[str], 'return': <class 'NoneType'>}`

Then I ran the following command `pyupgrade --py37-plus foo.py` and got the following:

**foo.py**
```
from __future__ import annotations

from typing import List, get_type_hints


def func(a: **list**[str]) -> None:
    pass


print(get_type_hints(a))
```

But know got the TypeErrorerror:

```
Traceback (most recent call last):
  File "foo.py", line 10, in <module>
    print(get_type_hints(func))
  File "/usr/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

I notice that `typing` using `eval` to evaluate nonforward types. But I wanted to believe that `__future__.annotations` will do the work. 
Hence, there are two options I can think of:

1. Open issue to typing
2. pyupgrade to update the typing to `'list[str]'` instead, so typing will recognize this as `ForwardRef`

WDYT?

**Comment by asottile** [comment]
> WDYT?

I think you didn't [search the issue tracker before creating an issue](https://github.com/asottile/pyupgrade/issues?q=is%3Aissue+get_type_hints+is%3Aclosed)
