### ISSUE TITLE
Use generator expressions in some built-in functions

### ISSUE THREAD

**Issue by MarcoGorelli** [asottile/pyupgrade#447]
From [PEP289](https://www.python.org/dev/peps/pep-0289/), in Python2.4+, some builtin functions could use generator expressions instead of list comprehensions, e.g.:

```diff
- sum([i for i in range(100)])
+ sum(i for i in range(100))
```
Likewise for `max` and `min`. Would this be a welcome addition?

**Comment by asottile** [comment]
yeah seems similar enough to #257
