### ISSUE TITLE
2.18.2 introduces incorrect syntax

### ISSUE THREAD

**Issue by gaborbernat** [asottile/pyupgrade#452]
See https://github.com/tox-dev/tox/pull/2068. By the looks of it, removes a list creation trying to replace it with a generator expression, but does not remove the trailing space to make it a valid generator expression...

**Comment by asottile** [comment]
@MarcoGorelli looks like this missed removing a trailing comma in the 1-arg case

**Comment by MarcoGorelli** [comment]
Ah, I see...for what it's worth, I'm _so_ sorry - I'd tried this out on the pandas repo before submitting and it worked fine there, for any future PRs I'll make sure to do a more extensive integration test

@asottile are you already working on fixing this or should I?

**Comment by asottile** [comment]
feel free to take a shot -- I'm busy at the moment!  don't worry about breaking stuff, sometimes it's difficult to know all possible cases :)
