### ISSUE TITLE
Replace ABCMeta with ABC

### ISSUE THREAD

**Issue by dannysepler** [asottile/pyupgrade#455]
Right now, pyupgrade replaces
```python
@six.add_metaclass(ABCMeta)
class MyClass:
    ...
```

with:
```python
class MyClass(metaclass=ABCMeta):
    ...
```

but what if we replaced both of these with
```python
class MyClass(ABC):
    ...
```

which feels easier to understand? And also according to the docs seems to accomplish the same thing https://docs.python.org/3/whatsnew/3.4.html#abc

**Comment by asottile** [comment]
it's not really within the spirit of the library which focuses on syntax -- it also functions slightly differently, plus it adds a level to the mro which can be undesirable
