### ISSUE TITLE
Is join with a generator less efficient?

### ISSUE THREAD

**Issue by TylerYep** [asottile/pyupgrade#456]
I noticed a recent change to pyupgrade converts all calls to `join([some list])` into `join(a generator)`.

But I also saw this discussion in flake8-comprehensions:
https://stackoverflow.com/questions/9060653/list-comprehension-without-in-python/9061024#9061024

Wondering if this answer in SO is correct or not?

**Comment by asottile** [comment]
🤷 easy to verify -- though I doubt this is a performance concern and more of a stylistic question

the answer was posted a very long time ago using python 2 code, it's unlikely it still has exactly the same performance concerns

**Comment by TylerYep** [comment]
Wait, so is there a legitimate performance concern? I'm not familiar enough with the Python implementation to verify join's behavior when using generators.

**Comment by asottile** [comment]
it's ever so slightly slower, like 3-5%

**Comment by MarcoGorelli** [comment]
> I noticed a recent change to pyupgrade converts all calls to `join([some list])` into `join(a generator)`.
> 
> But I also saw this discussion in flake8-comprehensions:
> https://stackoverflow.com/questions/9060653/list-comprehension-without-in-python/9061024#9061024
> 
> Wondering if this answer in SO is correct or not?

Apart from apologising for having introduced the feature, I'd like to thank you for having shared this link - interesting and useful info in there!
