### ISSUE TITLE
Replace list with tuple in for loops and comprehensions

### ISSUE THREAD

**Issue by cdce8p** [asottile/pyupgrade#458]
The last release added unpacking for list comprehensions: https://github.com/asottile/pyupgrade#unpacking-list-comprehensions

A related change could be to to replace lists with tuples inside for-loops and comprehensions where it's safe to do so.

```py
# old
[x**2 for x in [1, 4, 8, 9, 10]]

for x in [1, 4, 8, 9, 10]:
    print(x**2)

# new
[x**2 for x in (1, 4, 8, 9, 10)]

for x in (1, 4, 8, 9, 10):
    print(x**2)
```

**Comment by asottile** [comment]
this isn't really in the spirit of pyupgrade
