### ISSUE TITLE
Recursive mode?

### ISSUE THREAD

**Issue by alok** [asottile/pyupgrade#46]
Currently I run pyupgrade with something like `find ... | xargs pyupgrade`. A recursive flag to drill down directories would be nice (and in line with a lot of other formatters like black, yapf, and isort).

**Comment by alok** [comment]
Oh that's neat! I didn't know about the `--all-files` option. That's perfect.

**Comment by impredicative** [comment]
To offer some contrast, I think using `pre-commit` opens a whole can of worms, and it's shameless to need to require it. The following is simple and works in Bash:

```bash
shopt -s globstar
pyupgrade ./**/*.py
```
