### ISSUE TITLE
Handle typing.Iterator -> from collections.abc.Iterator for Python 3.9

### ISSUE THREAD

**Issue by sidmitra** [asottile/pyupgrade#468]
Running pyupgrade with flags `--py39-plus --keep-runtime-typing` with Python 3.9 doesn't change typing.Iterator to collections.abc.Iterator yet.

>class typing.Iterator(Iterable[T_co])
>     A generic version of collections.abc.Iterator.
>
>Deprecated since version 3.9: collections.abc.Iterator now supports []. See PEP 585 and Generic Alias Type.

See [Iterator](https://docs.python.org/3/library/typing.html?highlight=iterator#typing.Iterator)

**Comment by asottile** [comment]
this requires potentially adding / removing imports which isn't necessarily a safe operation.  as such this and other similar rewrites have not been attempted

you can however (if they're all `from` imports) utilize this option in [reorder-python-imports](https://github.com/asottile/reorder_python_imports#rewriting-pep-585-typing-imports)
