### ISSUE TITLE
Syntax error from __metaclass__ = type

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#469]
pyupgrade==2.19.3
Python 3.9.5

```console
$ cat 1.py
__metaclass__ = type
__all__ = [
    '_b',
    'advance_iterator',
    'reraise',
    'unicode_output_stream',
    ]
$ pyupgrade 1.py --py3-plus
Rewriting 1.py
```
```diff
diff --git a/1.py b/1.py
index 2ded809..84dc844 100644
--- a/1.py
+++ b/1.py
@@ -1,5 +1,4 @@
-__metaclass__ = type
-__all__ = [
+= [
     '_b',
     'advance_iterator',
     'reraise',
```

This is something to do with the presence of `__metaclass__ = type`, it doesn't happen if it's removed.

Example taken from: https://github.com/testing-cabal/testtools/blob/f38af6765d4e412b7a7ed1c77ddc9d68320330aa/testtools/compat.py

Git bisect says cb84d8f3c2ce271ac4c6dadaabfba0a8658c8cbc is the first bad commit, from PR https://github.com/asottile/pyupgrade/pull/292, released in v2.3.0.

Confirmed reproducible in 2.3.0, not in 2.2.1.

**Comment by asottile** [comment]
heh bisect was not terribly helpful -- `__metaclass_ = type` rewriting did not exist before 2.3.0

**Comment by hugovk** [comment]
Ha! Thanks for the quick fix, confirmed working :)
