### ISSUE TITLE
Rewriting socket.error but not socket.timeout leads to non-ideal changes

### ISSUE THREAD

**Issue by foolip** [asottile/pyupgrade#471]
This happened in https://github.com/web-platform-tests/wpt/pull/29301/commits/46348737f15856b4c2841c860d7e7ef3d9a3a20c#r650906576, where the resulting code is `except (socket.timeout, OSError)`.

I'm not sure if it's always safe to rewrite this to `except OSError`, but that's what we'll do in WPT I think.

**Comment by asottile** [comment]
```pycon
$ python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.timeout
<class 'socket.timeout'>
>>> socket.error
<class 'OSError'>
```

**Comment by foolip** [comment]
In other words, pyupgrade only replaces aliases, and `socket.timeout` is a `OSError` subclass. That's what I realized and sent https://github.com/web-platform-tests/wpt/pull/29362.

**Comment by asottile** [comment]
correct, pyupgrade tries really hard to not break existing code and rewriting a strict subclass has the potential to do that
