### ISSUE TITLE
Some string formatting can be replaced with the argument itself.

### ISSUE THREAD

**Issue by jenstroeger** [asottile/pyupgrade#473]
While cleaning up repos, I came across the following `pyupgrade` change:
```diff
-                message = "{0}".format(message)
+                message = f"{message}"
 ```
which, I think, can be further simplified to
```python
        message = str(message)
```
It’s a very specific case, but I’ve seen it a few times now. Just a thought, great tool 🤓

**Comment by asottile** [comment]
technically I think the f-string is faster, but they're also the same number of characters

I don't really think this is in the spirit of the tool -- but it could possibly be rewritten -- thanks for the issue nonetheless

**Comment by jenstroeger** [comment]
> I think the f-string is faster

Hot diggity, I would not have thought so…
```python
>>> timeit.timeit(stmt="str(s)", setup="s='some random string'", number=10000000)
1.2258909749999987
>>> timeit.timeit(stmt="f'{s}'", setup="s='some random string'", number=10000000)
0.13362486700000886
```
