### ISSUE TITLE
Convert some type() uses to isinstance()

### ISSUE THREAD

**Issue by jenstroeger** [asottile/pyupgrade#474]
The following is a common [pylint](http://pylint.org/) message: [`unidiomatic-typecheck`](http://pylint.pycqa.org/en/latest/technical_reference/features.html). For example
```python
if type(bla) == dict:  # pylint catches this one
```
or
```python
if type(bla) in [dict]:  # pylint does not catch this one
```
should be written as:
```python
if isinstance(bla, dict):
```
Multiple types should also work:
```python
if type(bla) in [list, tuple]:  # isinstance(bla, (list, tuple))
```
This should be applied only to builtin types like `list` or `str` or some such.

**Comment by asottile** [comment]
I think you've misunderstood the purpose of this tool:

> A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
