### ISSUE TITLE
--py36-plus ditches format variable

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#48]
Python 3.7.0
pyupgrade==1.4.0

# Before

```python
bad = 1

print ("Test FAIL: ".format(bad))

```

# Run

```console
$ pyupgrade 1.py --py36-plus
Rewriting 1.py
```

# After

```python
bad = 1

print (f"Test FAIL: ")
```

**Comment by hugovk** [comment]
A similar bad conversion also from https://github.com/googlefonts/fontbakery/pull/1980/commits/c57ef710e00598d4cbb8839b0449744948cf5de4:

```python
print ("Test PASS: ".format(good))
```
 -> 
```python
print (f"Test PASS: ")
```

And more  good conversions like:

```python
print ("Test PASS with a good RIBBI font ({})...".format(fontfile)
```
 ->  
```python
print (f"Test PASS with a good RIBBI font ({fontfile})...")
```

**Comment by hugovk** [comment]
Sorry, false alarm. The original code was missing the `{}` and should be:
```python
print ("Test FAIL: {}".format(bad))
```

So pyupgrade worked correctly and helped us identify a bug. Fixing the code allows it to be pyupgraded properly.

**Comment by asottile** [comment]
Sweet! Finding bugs is great! I've been meaning to write a linter for "missing format vars" for both f strings and format calls
