### ISSUE TITLE
Some of the converted strings into fstrings are no longer processed by babel

### ISSUE THREAD

**Issue by iranzo** [asottile/pyupgrade#487]
I'm using babel via a custom function `_(string,language)` that outputs the translated version.

When running pyupgrade over the source files:

~~~diff
@@ -174,7 +173,7 @@ def irccommands(msgdetail):
                         )
                     else:
                         text = _(
-                            "Error opping users from chat %s: %s" % (chat_id, result),
+                            f"Error opping users from chat {chat_id}: {result}",
                             language=mylang,
                         )
 
~~~

It causes babel to segfault as per https://github.com/python-babel/babel/issues/715

I would expect pyupgrade not to touch the code in a way that makes it later fail.

**Comment by MarcoGorelli** [comment]
Hi @iranzo - are you sure this isn't a bug in babel? The conversion here looks correct, do you have a reproducible example of where it isn't?

**Comment by iranzo** [comment]
Hi @MarcoGorelli see the linked issue in babel https://github.com/python-babel/babel/issues/715 and the comment:

~~~
I understand that including f-strings inside the _() function is a mistake
~~~

Thanks

**Comment by MarcoGorelli** [comment]
what's the `_()` function?

**Comment by iranzo** [comment]
Hi Marco, "_()" is usually the function defined for translatting strings, so in your code, you add stuff like:

_("This code works")

This function is defined from gettext (https://docs.python.org/3/library/gettext.html#localizing-your-application) and the way it works is that from all the strings inside it, it will generate a "pot" file with `msgid` and `msgstr`


When you run your code in an Italian environment (LANG=it_IT@UTF-8), the code will try to locate the translation strings inside the folder you defined, usually a `locale/it/LC_MESSAGES/yourprogram.mo` which has been compiled from a text file, usually `locale/it/LC_MESSAGES/yourprogram.po`, generated out of the 'pot' file for each one of the languages you want to translate with `poedit`, or some online services.

This makes that the msgid is searched in that catalog, and the msgstr is returned instead

so:
print(_("This code works"))

Will return on English or unstranslated languages:
"This code works"
In Spanish:
"Este código funciona"
In Italian:
"Questo codice funziona"

And so on



The strings are grabbed from the python files by using pybabel via:

`pybabel extract -o myprogram.pot mycodefiles.py`

And that's what causes the traceback in issue 715, when pyupgrade gets fstrings inside that function

**Comment by hugovk** [comment]
Sounds like Babel doesn't support f-strings, which is a Babel bug, not pyupgrade.

But can you use the pyupgrade `--keep-percent-format` option?

**Comment by iranzo** [comment]
The workaround I'm using is to use instead the {} markers without defined vars that should be good to go, but as the issue arised when using pyupgrade, I raised this here for awareness

**Comment by asottile** [comment]
**you're misusing translation -- those strings aren't being translated**.  if anything babel should produce an error for accidentally using string formatting inside of a translation function

babel will scan those (incorrectly) as `"Error opping users from chat %s: %s"` -- then at runtime it will try and translate `"Error opping users from chat whatever1: whatever2"` which will not match any of your translated IDs so you will always end up with english text.  (we had a linter when I was at yelp which prevented this sort of translation misuse -- but I believe it was proprietary / lost to closed source)
