### ISSUE TITLE
Feature idea/question: cleanup conditionals on sys.version_info

### ISSUE THREAD

**Issue by neutrinoceros** [asottile/pyupgrade#488]
This is more of a question at this point: I wonder if it _would_ be possible to do this with pyupgrade.
If it is, I'll attempt to write a patch, otherwise you can just close this !

## input

assuming we run pyupgrade with the `--py39` flag
```python
import sys

if sys.version_info < (3, 9):
    print("this should be cleaned up")
else:
    print("this is the message we should keep (dedent)")

if sys.version_info > (3, 8):
    print("this is the message we should keep (dedent)")
else:
    print("this should be cleaned up")

if sys.version_info >= (3, 8):
    print("this is the message we should keep (dedent)")
else:
    print("this should be cleaned up")

if sys.version_info <= (3, 9):
    print("nothing to do here")
else:
    print("both branches are still valid")
```
## output
```python
import sys

print("this is the message we should keep (dedent)")

print("this is the message we should keep (dedent)")

print("this is the message we should keep (dedent)")

if sys.version_info <= (3, 9):
    print("nothing to do here")
else:
    print("both branches are still valid")
```

**Comment by asottile** [comment]
there already is some amount of this that's done for `--py3-plus` but it gets complicated quickly!  I think it's possible so I'll leave this open but I seem to remember it being very tricky

**Comment by neutrinoceros** [comment]
So I've started looking into this, until I stumbled upon `pyupgrade/_plugins/versioned_branches.py` which looks a lot like a what I think I'm trying to write ? Why was it moved to a plugin and btw how can I _use_ plugins in pyupgrade ? I see no mention of them in the documentation. In any case, do you confirm that it's a good place to start ? should I try to expand it or start a different plugin ?

**Comment by asottile** [comment]
the plugins are entirely internal -- but a way to speed up and split up the code to manageable pieces

and yeah I would recommend starting with what's happening in that file (probably  just extending it to support the additional use-cases)
