### ISSUE TITLE
Consider more complex format-string replacement.

### ISSUE THREAD

**Issue by madig** [asottile/pyupgrade#49]
I have the following piece of code:
```Python
            if preview_version_string:
                actions.append(
                    'ttfix --name-version="{v}" -o "{target}" "{target}"'.format(
                        target=target_path, v=preview_version_string
                    )
                )

            if kerntable_file:
                actions.append(
                    (
                        "kerntable --ufo {ufo} --glyphset {kerntable} "
                        '"{target}" "{target}"'
                    ).format(ufo=ufo_path, target=target_path, kerntable=kerntable_file)
                )
                file_deps.append(kerntable_file)
```
`pyupgrade --py36-plus` did not upgrade those to f-strings.

**Comment by asottile** [comment]
As stated in [the readme](https://github.com/asottile/pyupgrade#f-strings) pyupgrade avoids rewriting if it would make the line longer (as this could potentially trigger other linter). This essentially excludes all multi line format calls.

Thanks for the issue! Though this is currently working as intended - - don't want to make flake8 grumpy :)
