### ISSUE TITLE
Another async generator breakage

### ISSUE THREAD

**Issue by scop** [asottile/pyupgrade#492]
Here's another async generator breakage similar to #489 , still present in 2.21.1:

https://github.com/home-assistant/core/blob/da7b29285561d351d035e264911ff4d96b08799f/tests/components/vera/common.py#L102

```python
            controller_data=tuple(
                [
                    await self._configure_component(hass, controller_config)
                    for controller_config in configs
                ]
            )
```
Removing that list comprehension results in the same `TypeError: 'async_generator' object is not iterable`

**Comment by MarcoGorelli** [comment]
Thanks for raising another useful report!
