### ISSUE TITLE
six.iterkeys() returns an iterator, where as dict.keys() does not

### ISSUE THREAD

**Issue by dmendelsohn** [asottile/pyupgrade#496]
Replacing six.iterkeys(d) with d.keys() can cause code to fail if it tries to run `next` on the output.

Minimal reproduction:

```
import six
d = {"foo": "bar"}

next(six.iterkeys(d). # Okay: returns "foo"

next(d.keys()). # Raises TypeError: 'dict_keys' object is not an iterator
```

It'd be safer to replace `six.iterkeys(d)` with `iter(d.keys())`!

**Comment by asottile** [comment]
can't reproduce:

```console
$ cat t.py 
import six
next(six.iterkeys(d))
$ pyupgrade --py3-plus t.py
Rewriting t.py
$ cat t.py 
import six
next(iter(d.keys()))
```

**Comment by dannysepler** [comment]
it seems like you only add `iter()` when the parent is `next()`, but not if the next is called on a later line https://github.com/asottile/pyupgrade/blob/master/pyupgrade/_plugins/six_calls.py#L96

so a reproduction could be:

```bash
$ cat t.py 
six.iterkeys(d)
e = next(d)
$ pyupgrade --py3-plus t.py
Rewriting t.py
$ cat t.py 
d.keys()
e = next(d)
```

**Comment by asottile** [comment]
yeah, can't solve the halting problem -- and adding `iter(...)` 99.99% of the time is unnecessary, it's only these very edge-case edge-cases that you _might_ need to manually add `iter(...)`

like you would never write:

```python
for f in iter(d.keys()):
    ...
```
