### ISSUE TITLE
pyupgrade can eat comments on typing.NamedTuple

### ISSUE THREAD

**Issue by ethanhs** [asottile/pyupgrade#497]
With the given file:

```python
# test.py
from typing import NamedTuple, Optional

class TypeInfo:
    pass

DeferredNode = NamedTuple(
    'DeferredNode',
     [
        ('active_typeinfo', Optional[TypeInfo]),  # And its TypeInfo (for semantic analysis
                                                  # self type handling)
    ])
```

run:
```
$ pyupgrade --py36-plus test.py
```

And the result is:
```python
from typing import NamedTuple, Optional

class TypeInfo:
    pass

class DeferredNode(NamedTuple):
    active_typeinfo: Optional[TypeInfo]
```

EDIT: I should note this was found when running pyupgrade on mypy.

**Comment by ethanhs** [comment]
Okay this is bizarre - apparently if you delete the assignment *target* the comments don't get deleted... wat

**Comment by asottile** [comment]
yeah this isn't really possible to preserve -- the entire call to `NamedTuple` is removed and replaced

this is (sadly) one of the places where preserving comments isn't possible (another is some of the more advanced multi-line six calls)

**Comment by ethanhs** [comment]
Ah ok, didn't know!
