### ISSUE TITLE
remove calls to sys.setdefaultencoding("utf-8")

### ISSUE THREAD

**Issue by graingert** [asottile/pyupgrade#501]
somehow:

```python
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```

[became a py2 idiom ](https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script) and it needs to be removed

**Comment by graingert** [comment]
see also https://bugs.python.org/issue37715

**Comment by asottile** [comment]
this is unfortunately out of scope for pyupgrade -- pyupgrade assumes you're already successfully running python 3 (it's mostly a burn-the-bridges sort of tool rather than a prepare-for-upgrade tool)

**Comment by graingert** [comment]
Ah woops you're totally right this file was broken entirely and never imported 😳
