### ISSUE TITLE
Do f-strings slow down execution when logging?

### ISSUE THREAD

**Issue by cclauss** [asottile/pyupgrade#503]
openai/gym#2257 lays out the argument…. If this is actually slower, is there a way to configure pyupgrade to continue to allow lazy formatting when logging?

**Comment by MarcoGorelli** [comment]
I think the argument in the link is to write
```
logger.info("Writing new rollout file to %s", ROLLOUT_FILE)
```
not:
```
logger.info("Writing new rollout file to {}".format(ROLLOUT_FILE))
```
and not:
```
logger.info(f"Writing new rollout file to {ROLLOUT_FILE}")
```

It's not the f-string rewrite that's causing the slowdown, but the fact that you're not using lazy evaluation when logging

**Comment by hugovk** [comment]
And pyupgrade (`--py36-plus`) doesn't touch the one with two params:

# Before

```python
logger.info("Writing new rollout file to %s", ROLLOUT_FILE)
logger.info("Writing new rollout file to {}".format(ROLLOUT_FILE))
```

# After

```python
logger.info("Writing new rollout file to %s", ROLLOUT_FILE)
logger.info(f"Writing new rollout file to {ROLLOUT_FILE}")
```

**Comment by flyser** [comment]
Arguably pyupgrade should convert both lines to

    logger.info("Writing new rollout file to %s", ROLLOUT_FILE)

**Comment by asottile** [comment]
fstrings are faster than `%s` and `.format()` and pyupgrade will never take a lazy log line and change it (it will only change an already-incorrect eager formatting)

I forget where but I think it was a beazley post showed that eager f-strings are faster even than lazy logging formatting

> Arguably pyupgrade should convert both lines to

no it shouldn't, garbage in, garbage out

**Comment by asottile** [comment]
here's one post showing they're faster: https://github.com/PyCQA/pylint/issues/2395
