### ISSUE TITLE
Pyupgrade should not rewrite type hints just base on `from __future__ import annotations`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [asottile/pyupgrade#515]
A quick example that pyupgrade breaks, I'm using python 3.9:

```python
from __future__ import annotations

from typing import get_type_hints, Optional


def dodo(a: Optional[int]):
    pass

get_type_hints(dodo)
```

with python 3.9, this code runs fine.

```bash
pyupgrade --py39-plus trying_stuff.py
```

the file becomes

```python
from __future__ import annotations

from typing import get_type_hints, Optional


def dodo(a: int | None):
    pass

get_type_hints(dodo)
```

by running this code with python 3.9, we get

```
Traceback (most recent call last):
  File "/projects/work/scube/trying_stuff.py", line 9, in <module>
    get_type_hints(dodo)
  File "/opt/conda/lib/python3.9/typing.py", line 1449, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/opt/conda/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/opt/conda/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Process finished with exit code 1
```

My conclusion is that using `from __future__ import annotations` to decide if it's possible to rewrite type hints is not valid if the user at some point inpects the type hints in the code. So pyupgrade should not do it since it has no way of knowing.

Thanks for this great package :)

Edit: I made it work with `--keep-runtime-typing`. But I believe that pyupgrade should not take the risk of breaking user code without additional information. The safest option should be the default option. Maybe replace it with `--do-no-keep-runtime-typing`?

**Comment by asottile** [comment]
`--keep-runtime-typing`

**Comment by gabrieldemarmiesse** [comment]
I made it work with --keep-runtime-typing. But I believe that pyupgrade should not take the risk of breaking user code without additional information. The safest option should be the default option. Maybe replace it with --do-no-keep-runtime-typing?

**Comment by asottile** [comment]
the common option is the default option
