### ISSUE TITLE
Allow finer-grained control of the kinds of changes that are made

### ISSUE THREAD

**Issue by Kodiologist** [asottile/pyupgrade#516]
There are already some command-line options that can enable or disable certain types of changes, such as `--py36-plus` and `--keep-percent-format`, but most types can't be individually toggled; for example, you can't change list comprehensions to generator comprehensions without also removing "r" from `open` modes.

**Comment by asottile** [comment]
there are intentionally no configuration options unless there are breakages

**Comment by Kodiologist** [comment]
Dare I ask why? It feels a bit silly to have to `git merge --patch` everything when it seems like it wouldn't be hard to make the individual changes toggleable.

**Comment by asottile** [comment]
"it wouldn't be hard"

feel free to fork yourself

this is an opinionated tool and maintaining the combinatoric explosion of options is not something I'm interested in.  it also is not simple and even if it was I'm against it on principal
