### ISSUE TITLE
Further refactoring for unittest methods, like `teyit`

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#521]
As a followup to #519/#520, it would be neat to rewrite `assertTrue` or `assertFalse` methods to use semantically richer assertion helpers.  Conveniently, [`teyit` has already implemented this](https://github.com/isidentical/teyit/blob/master/teyit.py) - and has illustrative examples:

```diff
-        self.assertTrue(len(x) > 0)
-        self.assertFalse(err == "")
+        self.assertGreater(len(x), 0)
+        self.assertNotEqual(err, '')

-        self.assertFalse(isinstance(b, A))
-        self.assertTrue(isinstance(b, A))
+        self.assertNotIsInstance(b, A)
+        self.assertIsInstance(b, A)

-        self.assertTrue(SUBSTR in s)
-        self.assertFalse(SUBSTR * 2 in s)
+        self.assertIn(SUBSTR, s)
+        self.assertNotIn(SUBSTR * 2, s)
```

I'm not sure that this fits with `pyupgrade`'s purpose, though it's more common in old projects, but thought it was worth writing up a quick issue - please just close if it's out of scope.  cc @isidentical, @adamchainz FYI.

**Comment by asottile** [comment]
yeah that's out of scope, tbh the rewrites in #519 were borderline as-is

**Comment by adamchainz** [comment]
It's nice there's already a separate tool for this, I will give it a try.
