### ISSUE TITLE
TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by christianbundy** [asottile/pyupgrade#522]
Hi there. I have an edge-case where pyupgrade suggested breaking changes to my code, which I _think_ is because it assumes that any usage of `**` implies that it's a dictionary and can be `|`'d with other dictionaries. I'm running pyupgrade with `--py39-plus`.

```python3
from collections.abc import Mapping


class A(Mapping):
    proxy = {"foo": 1}

    def __getitem__(self, k):
        return self.proxy.__getitem__(k)

    def __len__(self):
        return self.proxy.__len__()

    def __iter__(self):
        return self.proxy.__iter__()

a = A()
b = {"bar": 2}

# Basic assumption holds.
assert {**a} == {"foo": 1}

# Original code works.
assert {**a, **b} == {"foo": 1, "bar": 2}

# Pyupgrade suggestion
assert a | b == {"foo": 1, "bar": 2}
# TypeError: unsupported operand type(s) for |: 'A' and 'dict'
```

Is this an edge-case that Pyupgrade should handle, or is it safe to assume that any class that uses `**` needs to implement compatibility with a dictionary union?

**Comment by MarcoGorelli** [comment]
> > which I think is because it assumes that any usage of ** implies that it's a dictionary
> 
> the code that deals with this is here
> 
> https://github.com/asottile/pyupgrade/blob/aaad686b5f7851dd1b269f87cb5832ed132f4631/pyupgrade/_plugins/pep584.py
> 
> If it thinks it's a dictionary, it's because that's what's detected by the inbuilt `ast` module

I woke up in the middle of the night thinking "you know, I think I'd misunderstood that bug report on pyupgrade..." :laughing:  

Maybe it's OK to keep this exclusively for the case when there's
```python
{**{'a': 1}, **{'b': 2}}
```
?

**Comment by MarcoGorelli** [comment]
> Maybe it's OK to keep this exclusively for the case when there's
> 
> ```python
> {**{'a': 1}, **{'b': 2}}
> ```
> 
> ?

Though that wouldn't be much of a syntax upgrade...meh, maybe it's OK to just remove the rewrite

**Comment by christianbundy** [comment]
> > keep this exclusively
>
> > remove the rewrite

I think either would be fine, and I appreciate the quick fix! I think an `--maybe-dangerous` flag, or similar, would also do the trick, but that adds complexity to the API.

**Comment by spookylukey** [comment]
I agree that it's shame this can't be used when it's useful probably 99.9% of the time. [Flynt](https://github.com/ikamensh/flynt) has an `--aggressive` flag for changes that aren't 100% guaranteed correct, the same might be useful here.

**Comment by asottile** [comment]
@spookylukey please don't mention that project here -- the maintainer is not a kind member of open source and I do not want to give them free advertising
