### ISSUE TITLE
Re-write IOError outside except statements

### ISSUE THREAD

**Issue by twoertwein** [asottile/pyupgrade#525]
It seems that pyupgrade re-writes `IOError` only in the context of `except`.

See https://github.com/pandas-dev/pandas/pull/43366 for a few cases that are not re-written by `pyupgrade --py38-plus`.

**Comment by asottile** [comment]
[it only rewrites it in `raise` and `except`](https://github.com/asottile/pyupgrade#oserror-aliases)
