### ISSUE TITLE
pyupgrade is aggressively converting everything to f-strings

### ISSUE THREAD

**Issue by Dreamsorcerer** [asottile/pyupgrade#526]
We've just got a pre-commit auto-update, which has bumped pyupgrade to the latest release.

It seems that pyupgrade is now aggressively reformatting anything it can to an f-string, which is not what the documentation says it should do.

> note: pyupgrade is intentionally timid and will not create an f-string if it would make the expression longer or if the substitution parameters are anything but simple names or dotted names (as this can decrease readability).

As one example, where it's pushed practically an entire line of code into a string:
https://github.com/aio-libs/aiohttp/pull/5985/files#diff-8d8821e084bea8fa7388131b9aa226100488108387b49090d7982e0fb96fa6ffR77

I'd also appreciate on option to disable f-string conversion entirely, as it's not a universally accepted best-practice (for example, it's disallowed in wemake-style-guide).

**Comment by asottile** [comment]
[you've configured `--py36-plus` mode so you've opted into this](https://github.com/aio-libs/aiohttp/blob/a1158c5389854f9885c30e08b0020e2d7d8a290f/.pre-commit-config.yaml#L66)

**Comment by Dreamsorcerer** [comment]
Firstly, let me repeat the documentation:
> note: pyupgrade is intentionally timid and will not create an f-string if it would make the expression longer or if the substitution parameters are anything but simple names or dotted names (as this can decrease readability).

Secondly, the option is declaring that we only need to support python 3.6+, not that we specifically want to use f-strings everywhere.

I realise that all your projects are very opinionated and you probably won't add an option to disable the feature, but I do expect you to honour the documentation which says that it avoids trying to decrease readability, which it is clearly not doing.

**Comment by Dreamsorcerer** [comment]
So, unless `fm_size(sum(j) if j else 0)` looks like a simple name or dotted name to you, something is clearly wrong.

**Comment by asottile** [comment]
ah right, things changed in #298 -- I've clarified in 6b2d0d8b2

**Comment by Dreamsorcerer** [comment]
OK, I think that example and a couple of others are too complex for my liking.

Again, it would be nice to have an option to opt-out of f-strings, without having to opt out of all other (non-controversial) 3.6+ features.

**Comment by asottile** [comment]
options in pyupgrade are only for breakages

you're also free to assign local variables to simplify your expressions (though I'd argue the `.format(...)` code was the same complexity and probably should have been refactored anyway)
