### ISSUE TITLE
f-string conversion with advanced string formatting & None

### ISSUE THREAD

**Issue by peterjc** [asottile/pyupgrade#528]
Failing test case using pyupgrade 2.25.0:

```
$ echo 'a=b=c=None; print("Query:%8s %s %s" % (a, b, c))'  > test.py ; pyupgrade --py36-plus test.py ; cat test.py
Rewriting test.py
a=b=c=None; print(f"Query:{a:>8} {b} {c}")
```

```pycon
>>> a=b=c=None; print("Query:%8s %s %s" % (a, b, c))
Query:    None None None
>>> a=b=c=None; print(f"Query:{a:>8} {b} {c}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to NoneType.__format__
```

The problem is while ``f"{None}"`` works, advanced string format arguments do not:

```pycon
>>> "%8s" % None
'    None'
```

```pycon
>>> f"{None:>8}"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to NoneType.__format__
```

Possible workaround:

```python
>>> a=b=c=None; print(f"Query:{str(a):>8} {b} {c}")
Query:    None None None
```

This issue was found in https://github.com/biopython/biopython/pull/3724

**Comment by peterjc** [comment]
For comparison, flynt does not change this by default:

```
$ echo 'a=b=c=None; print("Query:%8s %s %s" % (a, b, c))'  > test.py ;  flynt --quiet test.py ; cat test.py 
Running flynt v.0.69
a=b=c=None; print("Query:%8s %s %s" % (a, b, c))
```

It will change it under aggressive mode:

```
$ echo 'a=b=c=None; print("Query:%8s %s %s" % (a, b, c))'  > test.py ;  flynt --quiet --aggressive test.py ; cat test.py 
Running flynt v.0.69
a=b=c=None; print(f"Query:{a:8} {b} {c}")
```

As an aside (do you want this logged as a separate issue?), I note that ":8" seems more concise than ":>8" for the formatting argument:

```
>>> a=123
>>> f"{a:8}"
'     123'
>>> f"{a:>8}"
'     123'
>>> f"{a:<8}"
'123     '
```

**Comment by asottile** [comment]
sadly I think this is unfixable -- there would need to be type analysis to properly know that "None" is buggy -- the only other option is disabling all alignment conversions

arguably this is a bug in python itself, I see no reason that the padding formatters shouldn't work for `None`

I'm not sure what the best thing to do here is

`:8` is more concise but incorrect:

```pycon
>>> '{:8}'.format("a")
'a       '
>>> '{:8}'.format(1)
'       1'
>>> '%8s' % ('a',)
'       a'
>>> '%8s' % (1,)
'       1'
```

an aside, please don't mention flynt -- the author has ripped me off in the past and has generally been an uncooperative and unethical open source maintainer

**Comment by asottile** [comment]
I guess the only safe approach is skipping -- #529 implements that

**Comment by peterjc** [comment]
I was also wondering if this was a Python bug too, I had a quick look but didn't find anything on their tracker.

I agree that unless a future version of Python changes this, disabling any conversion with an alignment is safest.
