### ISSUE TITLE
[bug] --py37-plus makes a change to optional type view like in python 3.10

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [asottile/pyupgrade#531]
pyupgrade version 2.25.1

input
```python3
    def __init__(
        self,
        driver: Optional[WebDriver] = None,
        hook_wait_failure: Optional[Callable[[TimeoutException], Exception]] = None
    )
```
run command
```bash
pyupgrade filename --py37-plus
```
actual output
```python3
    def __init__(
        self,
        driver: WebDriver | None = None,
        hook_wait_failure: Callable[[TimeoutException], Exception] | None = None,
    )
```
expected output for python 3.7 upgrade
```python3
    def __init__(
        self,
        driver: Optional[WebDriver] = None,
        hook_wait_failure: Optional[Callable[[TimeoutException], Exception]] = None
    )
```

P.S. If I am wrong with expected result and actual result is the right one - then i have a question: How to upgrade from lower python versions to python 3.7 only? Not 3.8 or higher.

**Comment by MarcoGorelli** [comment]
hey @aleksandr-kotlyar - you should pass [`--keep-runtime-typing`](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites)

**Comment by MarcoGorelli** [comment]
> input

Tip for the future - show your complete input. Your file probably has `from __future__ import annotations` which you've not shown

**Comment by aleksandr-kotlyar** [comment]
> > input
> 
> Tip for the future - show your complete input. Your file probably has `from __future__ import annotations` which you've not shown

You are right! It has! :( What to do then?

**Comment by aleksandr-kotlyar** [comment]
> hey @aleksandr-kotlyar - you should pass [`--keep-runtime-typing`](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites)

Thank you!
