### ISSUE TITLE
PEP584 revert is not reflected in pip installed version 2.26.0

### ISSUE THREAD

**Issue by spookylukey** [asottile/pyupgrade#536]
If you do a `pip install pyupgrade==2.26.0` and run it on some files, you find that it still does the transform that was supposed to have been removed in https://github.com/asottile/pyupgrade/pull/523/commits/1cf9acaa31b362bf87765177a9f4c73aca91b02f

It looks like a bug in your release process that is causing old files to stay in. Specifically, if you look at the downloads: https://pypi.org/project/pyupgrade/#files you'll see that for the tarball, pep584.py is absent as it should be, but in the wheel it is present.

This caused quite a bit of confusion for me today!

I have had issues with this kind of thing in the past - I always have a release script that starts something like:
```shell
rm -rf build dist
```

**Comment by MarcoGorelli** [comment]
👍  can reproduce:
```console
% cat t.py 
x = {"a":1}
y = {"b":2}
z = {**x, **y}

% cat .pre-commit-config.yaml 
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.26.0
  hooks:
  - id: pyupgrade
    args: [--py39-plus]
% pre-commit run pyupgrade --files t.py 
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
pyupgrade................................................................Passed
% pyupgrade t.py --py39-plus
Rewriting t.py
% cat t.py 
x = {"a":1}
y = {"b":2}
z = x | y
```

**Comment by asottile** [comment]
I've reuploaded the current source as 2.26.0.post1
