### ISSUE TITLE
Rewriting `for i in ...: yield i` to `yield from ...` discards comment in loop body

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#539]
```python
def f():
    for i in range(10):
        # comment
        yield i
```
`pyupgrade --py3-plus` rewrites this as expected, but discards the comment in the process:
```python
def f():
    yield from range(10)
```

Ideally, we would instead preserve the comment, moving it to immediately before the `yield from` (if before `yield`) and/or after (respectively).

(and thanks again for `pyupgrade`!  It continues to be one of the most valuable refactoring tools in my kit 😃)

**Comment by asottile** [comment]
there's a duplicate somewhere -- this is one of the places where pyupgrade deletes comments and there's not really much that can be done

**Comment by Zac-HD** [comment]
Fair enough! Do you have a list of other cases anywhere? I'm working on some libcst codemods and could handle them before running pyupgrade.
