### ISSUE TITLE
Incorrect mock upgrade

### ISSUE THREAD

**Issue by vivster7** [asottile/pyupgrade#549]
I think I found a bug in the mock transforms.

`pyugrade --py3-plus` will change the transform the line:
`from mock import mock` -> `from unittest.mock import mock`

I believe the correct transform would be:
`from mock import mock` -> `from unittest import mock`

The `from unittest.mock import mock` line raises the following error:
```
  File "test.py", line 1, in <module>
    from unittest.mock import mock
ImportError: cannot import name 'mock'
```

I'd be happy to submit a patch for this if it will get accepted.

**Comment by asottile** [comment]
the original import is incorrect, it should be `import mock`

**Comment by vivster7** [comment]
Agreed that `import mock` should be preferred -- but `from mock import mock` does work as well without an import error. And since it works, people use it. https://grep.app/search?q=from%20mock%20import%20mock&case=true&words=true

**Comment by asottile** [comment]
if you want to poke at the code it's here: https://github.com/asottile/pyupgrade/blob/master/pyupgrade/_plugins/mock.py
