### ISSUE TITLE
multiline strings don't get fstringified

### ISSUE THREAD

**Issue by anntzer** [asottile/pyupgrade#55]
on 1.5.1
```
do("foo {}".format(bar))
do("foo {}"
   .format(bar))
```
the first line gets fstringified, not the second one.
(imagine very long strings, such that it made sense to break a line before the method call)

**Comment by anntzer** [comment]
But pyupgrade is already making lines longer when upgrading %-formatting to .format-formatting (say, when using complex arguments that do not qualify for an f-string)...

**Comment by asottile** [comment]
I guess that is true, but the delta is usually bounded by `len('.format') - len(' % ')`  (4) (and often lower if format specifiers are dropped or dicts are converted). But with f strings it's much much higher.

Anyway, it's not a permanent hard and fast rule, I'm just explaining the current documented design :)

**Comment by anntzer** [comment]
No worries, just suggesting it; in my view I'll need to manually pass through the result to cleanup the fallout of %-conversions anyways so I may as well manually fix the overly long f-strings too...

**Comment by asottile** [comment]
Makes sense, in the future I do plan to make the fstring rewriter slightly more clever -- probably a lot of work and edge cases to consider though 😆!
