### ISSUE TITLE
Remove unnecessary walrus operator

### ISSUE THREAD

**Issue by christianbundy** [asottile/pyupgrade#556]
I want to convert:

```python3
if a := b:
    print(a)
```

Into:

```python3
a = b
if a:
    print(a)
```

Is this a plugin that would be accepted in pyupgrade, or would that be a different project (pydowngrade?)?

**Comment by jenstroeger** [comment]
I’m curious about the purpose of _removing_ such assignment expressions when `pylint` has an optional checker that suggests the opposite ([docs](https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html#code-style-checker-messages))? Pure style preference?
