### ISSUE TITLE
Feature proposal: replacing deprecated typing imports with collections.abc

### ISSUE THREAD

**Issue by antonagestam** [asottile/pyupgrade#558]
A bunch of types in typing were deprecated in 3.9 in favor of their `collections.abc` equivalents.

It would be nice to have `from typing import Sequence` be replaced with `from collections.abc import Sequence` when `--py39-plus` is given.

**Comment by antonagestam** [comment]
@asottile Would you be amenable to accepting a PR porting or re-implementing this feature in this project?

**Comment by asottile** [comment]
this has been handled by #661 #663 #664 #665 #666 #667 #668 #669 #670 #671
