### ISSUE TITLE
Disable rule for specific line?

### ISSUE THREAD

**Issue by chrisspen** [asottile/pyupgrade#559]
I generally like Pyupgrade's rules, but in one class, I need to disable the rule that remove the `super()` arguments to ensure my class inherits from a specific parent.

Overall, I want to continue using the rule. I just want to disable the rule for that one line in the class. Is there a way to do that?

**Comment by asottile** [comment]
I suspect you're on a version which is not the latest -- that rule was removed

**Comment by asottile** [comment]
(but I can only guess because you have not provided a complete bug report -- here is a [framework I'd suggest using](https://youtu.be/ritp4gAqNMI) for making a good bug report)

**Comment by chrisspen** [comment]
When was it removed? I'm using 2.26.0, which was only released last month.
