### ISSUE TITLE
Replace `six.StringIO` and `six.BytesIO` with `--py3-plus`

### ISSUE THREAD

**Issue by nsoranzo** [asottile/pyupgrade#560]
Another suggestion for `--py3-plus`:

```diff
1,3c1,3
< import six
< s = six.StringIO()
< b = six.BytesIO()
---
> import io
> s = io.StringIO()
> b = io.BytesIO()
```

> `six.StringIO`
>
> This is an fake file object for textual data. It’s an alias for `StringIO.StringIO` in Python 2 and `io.StringIO` in Python 3.
>
> `six.BytesIO`
> This is a fake file object for binary data. In Python 2, it’s an alias for `StringIO.StringIO`, but in Python 3, it’s an alias for `io.BytesIO`.

https://pythonhosted.org/six/#six.StringIO

_Originally posted by @hugovk in https://github.com/asottile/pyupgrade/issues/59#issuecomment-466640621_

**Comment by asottile** [comment]
this is a dupe, there isn't a safe way to do symbol replacements for added it removed imports
