### ISSUE TITLE
Do not upgrade string annotations types wrapped in `Optional` to new Union | formatting

### ISSUE THREAD

**Issue by wakemaster39** [asottile/pyupgrade#567]
Simplistic python code:

```python
qqq: "int" | None = 0
```

Output:

```
python qqq.py
Traceback (most recent call last):
  File "qqq.py", line 2, in <module>
    qqq: "int" | None = 0
TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'
```

When running pyupgrade a segment of code was updated to use the `|` notation and caused this explosion. I worked around it, but I am sure others might run into similar issues.

**Comment by asottile** [comment]
you've either opted into a python version that's newer than the one you're running or something else you're not showing -- pyupgrade only does this if it's safe

**Comment by wakemaster39** [comment]
@asottile i am running latest python 3.10

**Comment by asottile** [comment]
well then there's something you're not showing me -- watch this video and try again: https://youtu.be/ritp4gAqNMI

**Comment by wakemaster39** [comment]
you are right,  I didn't finish the bug report. Sorry mac pressed submit. Not use to a github repo getting such quick attention, which is awesome btw. Here is the rest you need to replicate the issue fully.

```python
from typing import Optional

from sqlalchemy.orm import Mapped, relationship

qqq: Mapped[Optional["WorkspaceModel"]]
```

After running pyupgrade, the output I am getting is:

```
from sqlalchemy.orm import Mapped

qqq: Mapped["WorkspaceModel" | None]
```

**Comment by asottile** [comment]
pyupgrade does not change that for for me, please watch the video and follow what it asks you to do

**Comment by wakemaster39** [comment]
1. I am running pyupgrade using pre-commit hooks to keep my code based with the latest syntax
2. I have the following in my pre-commit hooks file:

```
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
```

When running a `pre-commt run --all` on a file (qqq.py) with a file containing the content of:

```python
from typing import Optional

from sqlalchemy.orm import Mapped

qqq: Mapped[Optional["WorkspaceModel"]]
```

3. I would expect the file to have no changes written to it.

4. What is happening is that a file with the following content is written:

```python
from sqlalchemy.orm import Mapped

qqq: Mapped["WorkspaceModel" | None]
````

As an additional note, the output does not change if I use `pyupgrade qqq.py` instead of using the pre-commit hook.

**Comment by asottile** [comment]
there were go, that's much more helpful and now I can reproduce

you can likely work around this with `from __future__ import annotations` until this is fixed
