### ISSUE TITLE
question: print_statements not handled by pyupgrade ?

### ISSUE THREAD

**Issue by kratsg** [asottile/pyupgrade#569]
```bash
$ cat test.py 
print "hello"
$ pyupgrade --py3-only --py38-plus test.py 
$ cat test.py 
print "hello"
```

```bash
$ python --version
Python 3.6.8
$ pip list | grep pyupgrade
pyupgrade          2.29.1
```

**Comment by asottile** [comment]
pyupgrade is not a 2-to-3 porting utility but more of a "I'm done with python 2" utility

**Comment by kratsg** [comment]
What's the difference between 2-to-3 porting and the `--py3-plus` option? Isn't `print "test"` not valid in python3+ code?

**Comment by asottile** [comment]
`--py3-plus` is "remove any python 2.x-compatibility constructs"
