### ISSUE TITLE
--py39-plus argument is applying PEP604

### ISSUE THREAD

**Issue by dreinon** [asottile/pyupgrade#575]
This is happening in a `class` which `__init__` method has a property of type hint
```py
dict[str, Optional[dict[str, Optional[int]]]]
```

When the pre-commit hooks are triggered, `pyupgrade --py39-plus` fails and modifies this to
```py
dict[str, dict[str, int | None] | None]
```
I tried installing pyupgrade itself and running it from its CLI and working in the same way, and also autoupdated pre-commit hooks.

**Pyupgrade version:** v2.29.1

**Comment by asottile** [comment]
[watch this](https://youtu.be/ritp4gAqNMI) and [read this](https://github.com/asottile/pyupgrade#pep-604-typing-rewrites)
