### ISSUE TITLE
six: burn the bridges

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#59]
Let's try and automatically un-six python source.  Here's a quick audit of what six does and how to undo it in python 3:

From [the docs](https://six.readthedocs.io/):

### trivial replacements
- [x] `six.text_type` => `str`
- [x] `six.binary_type` => `bytes`
- [x] `six.class_types` => `(type,)`
- [x] `six.string_types` => `(str,)`
- [x] `six.integer_types` => `(int,)`
- [x] `six.unichr` => `chr`
- [x] `six.iterbytes` => `iter`
- [x] `six.print_(...)` => `print(...)`
- [x] `six.exec_(c, g, l)` => `exec(c, g, l)`
- [x] `six.advance_iterator(it)` => `next(it)`
- [x] `six.next(it)` => `next(it)`
- [x] `six.callable(x)` => `callable(x)`

### trivial removals:
- [x] `python_2_unicode_compatible` (remove decorator)

   ```python
   @six.python_2_unicode_compatible
   class C: pass
   ```

### requires parsing a function call
- [x] `six.u('foo')` => `'foo'`
- [x] `six.byte2int(bs)` => `bs[0]`
- [x] `six.indexbytes(bs, i)` => `bs[i]`
- [x] `six.iteritems(dct)` => `dct.items()  # also {iter,view}{items,keys,values}`
- [x] `six.create_unbound_method(fn, cls)` => `fn`
- [x] `six.get_unbound_method(meth)` => `meth`
- [x] `six.get_method_function(meth)` => `meth.__func__`
- [x] `six.get_method_self(meth)` => `meth.__self__`
- [x] `six.get_function_closure(fn)` => `fn.__closure__`
- [x] `six.get_function_code(fn)` => `fn.__code__`
- [x] `six.get_function_defaults(fn)` => `fn.__defaults__`
- [x] `six.get_function_globals(fn)` => `fn.__globals__`
- [x] `six.assertCountEqual(self, arg1, arg2)` => `self.assertCountEqual(arg1, arg2)`
- [x] `six.assertRaisesRegex(self, fn, *a, **k)` => `self.assertRaisesRegex(fn, *a, **k)`
- [x] `six.assertRegex(self, *a)` => `self.assertRegex(*a)`

### maybe replace with literal?
- [x] `six.b` => replace with bytes literal?

### need to know that you're not in a place where a `raise` statement is invalid
- [x] `six.raise_from(exc, exc_from)` => `raise exc from exc_from`
- [x] `six.reraise(tp, exc, tb)` => `raise exc.with_traceback(tb)`

### probably can reuse the "new style class" logic
- [x] `class C(six.Iterator):` => `class C:`

### requires multiple function call parses, probably hard
- [x] `class C(six.with_metaclass(Meta, Base)):` => `class C(Base, metaclass=Meta):`
- [x] (rewriting `add_metaclass`)

   ```python
   @six.add_metaclass(mcs)
   class C(...): pass
   ```

   to

   ```python
   class C(..., metaclass=mcs): pass
   ```

### probably can't do (requires introducing an import)
- [x] six.wraps(fn) => functools.wraps(fn): https://github.com/asottile/reorder_python_imports/pull/59

Note that for `six.moves` I'm planning on handling that in [reorder-python-imports](https://github.com/asottile/reorder_python_imports/pull/50)

**Comment by nicoddemus** [comment]
Was looking for a tool to automatically remove `six` from our code base. Anthony to the rescue! 😁

**Comment by asottile** [comment]
:tada: let me know how it goes, there's still a few things left to finish and the imports aren't handled (yet?)

**Comment by nicoddemus** [comment]
Sure, will do!

**Comment by hugovk** [comment]
Is it possible to clean up `six.PY2` and `six.PY3` when running with `--py3-plus`?

```diff
1,4c1
< if six.PY2:
<     python2stuff()
< else:
<     python3stuff()
---
> python3stuff()
```

```diff
1,4c1
< if six.PY3:
<     python3stuff()
< else:
<     python2stuff()
---
> python3stuff()
```

**Comment by asottile** [comment]
yeah, should be possible -- though pretty difficult

**Comment by hugovk** [comment]
Another suggestion for `--py3-plus`:

```diff
1,3c1,3
< import six
< s = six.StringIO()
< b = six.BytesIO()
---
> import io
> s = io.StringIO()
> b = io.BytesIO()
```

> `six.StringIO`
>
> This is an fake file object for textual data. It’s an alias for `StringIO.StringIO` in Python 2 and `io.StringIO` in Python 3.
>
> `six.BytesIO`
> This is a fake file object for binary data. In Python 2, it’s an alias for `StringIO.StringIO`, but in Python 3, it’s an alias for `io.BytesIO`.




https://pythonhosted.org/six/#six.StringIO

**Comment by asottile** [comment]
with #149 I think I'm finally calling this done!

I'm planning to try and do something clever with version-guarded blocks later

**Comment by hugovk** [comment]
Good work!
