### ISSUE TITLE
`--keep-runtime-typing --py39-plus` breaks tests inspecting backwards compatible type hints

### ISSUE THREAD

**Issue by JacobHayes** [asottile/pyupgrade#592]
Pulling out from https://github.com/asottile/pyupgrade/issues/574#issuecomment-1009622119:

> I'm working with code that explicitly inspects (user defined) type hints. In tests I confirm `tuple[int]` and `Tuple[int]` are both handled properly. [...] running `pyupgrade --keep-runtime-typing --py39-plus` changed both to `tuple[int]`, triggering a test failure + reduced coverage.

@asottile said `--keep-runtime-typing` [should fix things](https://github.com/asottile/pyupgrade/issues/574#issuecomment-1009968833), but that still changes `Tuple` to `tuple` when used with `--py39-plus`.

I don't mean to be a pest, but just wanted to see if there was a supported workaround for type hinting code. If this is too edgecase-y to warrant a fix, that's ok but wanted to know the limitation.

Thanks for the great library!

**Comment by asottile** [comment]
if you're targetting python3.9+ there's no difference between Tuple and tuple

**Comment by JacobHayes** [comment]
If you're using _runtime_ type hints (ie: `--keep-runtime-typing`), there are:

```python
Python 3.9.7 (default, Nov 15 2021, 13:16:09)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> issubclass(tuple[int], tuple)
False
>>> from typing import Tuple
>>> issubclass(Tuple[int], tuple)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
```

I'm getting `Tuple[...]` from _user_ code I don't control (that is otherwise 3.9+) and _my_ code is trying to handle (and test) such issues. `typing` is anything but standard across python version. 😁

--

Regardless, I'll consider this closed and continue with my `Tuple = getattr(typing, "Tuple")` workaround in tests. Thanks for the quick responses!
