### ISSUE TITLE
Support for custom plugins?

### ISSUE THREAD

**Issue by cdce8p** [asottile/pyupgrade#594]
I would like to write custom / project dependent plugins for pyupgrade. `pyupgrade` already has a plugin structure in-place. It's limited to the `pyupgrade/_plugins` folder though. Would it be possible to add an option to allow additional modules / packages being loaded?

https://github.com/asottile/pyupgrade/blob/fd230e8c64cfd990e1e9231522ed3e4c4e08cb58/pyupgrade/_data.py#L118-L122

Without a builtin option, I imaging the only possibility would be to use a path configuration file.

**Comment by asottile** [comment]
I have no intention of supporting external plugins at this time

the plugin system is purely for organizational purposes

**Comment by youtux** [comment]
It would be nice to support external plugins.

The use case for me is that I'm [changing the signature of a function](https://github.com/pytest-dev/pytest-factoryboy/pull/150) in pytest-factoryboy, and it would be exteremly handy to be able to provide a pyupgrade plugin to help users migrate to the new function calls.

**Comment by asottile** [comment]
write your own formatter -- here's a tutorial (pyupgrade doesn't really add anything): https://youtu.be/G1omxo5pphw
