### ISSUE TITLE
Add a --check option which checks but doesn't modify files

### ISSUE THREAD

**Issue by barisione** [asottile/pyupgrade#595]
Both black and isort have options to run the tools without actually modifying it.
That's useful to have the tool as part of a CI pipeline and fail if the files are not formatted correctly.

I'd like to use pyupgrade in the same way but it's not currently possible.

black's option:
```
  --check                         Don't write the files back, just return the
                                  status. Return code 0 means nothing would
                                  change. Return code 1 means some files would
                                  be reformatted. Return code 123 means there
                                  was an internal error.
```

isort's option:
```
  -c, --check-only, --check
                        Checks the file for unsorted / unformatted imports and prints
                        them to the command line without modifying the file. Returns 0
                        when nothing would change and returns 1 when the file would be
                        reformatted.
```

**Comment by nschonni** [comment]
Duplicate of a bunch of issues https://github.com/asottile/pyupgrade/issues?q=is%3Aissue+--check+is%3Aclosed

**Comment by MarcoGorelli** [comment]
Just out of interest - why would you want/need this option? pyupgrade already exits `1` if it modifies your files https://github.com/asottile/pyupgrade/issues/310#issuecomment-630282643

**Comment by barisione** [comment]
> Just out of interest - why would you want/need this option? pyupgrade already exits `1` if it modifies your files [#310 (comment)](https://github.com/asottile/pyupgrade/issues/310#issuecomment-630282643)

To run it inside a CI system where other tools (isort, black, pylint, mypy) are accessing the same files at the same time.

So far we have been running pyupgrade manually every time we update our Python minimum version but it looks like some older idioms can always sneak back in, despite reviews.
Instead of doing this we could just run pyupgrade in our CI to detect this (without modifying the source code) and run it as part of a pre-commit hook (which modifies the code). The CI step detects people who are not running the hook.

**Comment by asottile** [comment]
just run `pre-commit run --all-files` in CI or use https://pre-commit.ci

a patch will not be accepted please read the duplicate issues
