### ISSUE TITLE
Option to prevent creating new f-strings

### ISSUE THREAD

**Issue by collinanderson** [asottile/pyupgrade#597]
Hi All,

Thanks so much for pyupgrade. It's awesome.

I'm personally still pretty skeptical of f-strings myself, and even just seeing some of the f-string issues here, I'm wondering if would make sense to add a command line flag to disable creating new f-strings?

Thanks,
Collin

**Comment by DmytroLitvinov** [comment]
Hi @asottile ,

Is there any option how we can disable specific line formatting to f-string?
Let me explain a bit more about my example and why I asked it.

I have a Django project with Python 3.8 and in `pre-commit` tool I integrated `pyupgrade` with `--py38-plus` argument. So it converted all strings to f-strings. 

Django does not support f-strings in internalization.
> Since string extraction is done by the xgettext command, only syntaxes supported by gettext are supported by Django. In particular, Python [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) are not yet supported by xgettext, and JavaScript template strings need gettext 0.21+

(c) https://docs.djangoproject.com/en/4.0/topics/i18n/translation/

![Selection_1222](https://user-images.githubusercontent.com/16066485/152929783-fcb7c03d-d5a3-4db6-9ed6-bd4c9808b302.png)

**Comment by asottile** [comment]
format strings aren't supported there either, the message id you're looking up won't exist

**Comment by ppoilbarbe** [comment]
If you want it correctly translated, write (change place of the bracket):
 `_('The invitation for {} was already accepted.').format(invitation.user.email))`
 Then the gettext function '_' gets the format as the untranslated string, and then values are inserted.
