### ISSUE TITLE
More robust conversion of % strings to f-strings please :-)

### ISSUE THREAD

**Issue by eteran** [asottile/pyupgrade#600]
First off, this tool is fantastic! It has saved me countless hours in my efforts to refactor our multi-million line codebase from py2 to py3.

Anyway, I'd love it if the tool could handle a few more cases of % string conversions, specifically:

First the easier one. It seems that the tool will only convert % based formatting if the second parameter is a tuple, so it catches this:

```
var = "hello"
print("Some String: %s" % (var,))
```

But not this:

```
var = "hello"
print("Some String: %s" % var)
```

I find myself going through the code base, manually making things into tuples just to make the converter trigger!

Second, logger composed strings (I know this is hard because now you need to be super careful that you're actually dealing with a logger since there's no `%` operator being used to indicate the substitution is happening... But maybe a flag to try to do it when it sees the standard logger function names?

```
var = "hello"
logger.info("Some String: %s", var)
```

into:

```
logger.info(f"Some String: {var}")
```

Neither of these are a show-stopper, just on my wishlist!

**Comment by asottile** [comment]
`'%s' % var` is unknowable without knowing the type of `var` -- so your suggestion of "improved robustness" is actually backwards -- it would introduce an unsoundness:

```pycon
>>> '%s' % var
'1'
>>> '{}'.format(var)
'1'
>>> var = (1,)
>>> '%s' % var
'1'
>>> '{}'.format(var)
'(1,)'
```


there are many duplicates in the issue tracker, please search for them next time
