### ISSUE TITLE
feature request: Upgrade to use assignment expression (PEP-0572)

### ISSUE THREAD

**Issue by yoursvivek** [asottile/pyupgrade#601]
Python 3.8 or higher support [assignment expression][feature] as described in [PEP-0572]. If would be great if this tool could upgrade those.

[feature]: https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions
[PEP-0572]: https://www.python.org/dev/peps/pep-0572/

example:
```python
value = some_expression
if value:
    ...
```
to
```python
if value := some_expression:
   ...
```

**Comment by asottile** [comment]
I don't bother with close reasons and this is a duplicate
