### ISSUE TITLE
universal_newlines conversion can lead to doubled "text"

### ISSUE THREAD

**Issue by MichaIng** [asottile/pyupgrade#610]
If for some reason `universal_newlines` and `text` are both passed to a `subprocess.run()`, replacing the first with the latter causes `text` to be doubled. I suggest to in such case remove `universal_newlines`, if `text` has priority anyway with Python 3.6 and later.

**Comment by asottile** [comment]
can you provide more information? example inputs outputs and program version?

**Comment by MichaIng** [comment]
Here is the related commit based on what `pyupgrade --py37-plus` v2.31.0 produced: https://github.com/motioneye-project/motioneye/commit/94e63f1#diff-4e98d8ae5ebf19f5f90280ddf3865c4e51d4f39332a15a1477f19e0149307683L608-R607
