### ISSUE TITLE
`typing_extensions` upgrades

### ISSUE THREAD

**Issue by JeppeKlitgaard** [asottile/pyupgrade#616]
I think a super neat addition to `pyupgrade` would be to move imports that use backported typing functionality from `typing_extensions` into the `typing` equivalent when the appropriate minimum version is satisfied.

There is a good overview of which `typing` features are supported by which Python version at: https://github.com/python/typing/blob/master/typing_extensions/README.rst

Example:
```diff
# When using --py311-plus
- from typing_extensions import Unpack
+ from typing import Unpack
```

**Comment by asottile** [comment]
this has been handled by #661 #663 #664 #665 #666 #667 #668 #669 #670 #671
