### ISSUE TITLE
Add an option to automatically add `from __future__ import annotations` when needed

### ISSUE THREAD

**Issue by abey79** [asottile/pyupgrade#618]
I recently realised how `from __future__ import annotations` enables modern type hint while retaining compatibility with older Python version (I currently target 3.8+ with my project). Using `pyupgrade` helped a great deal to bring everything up to date, but I still had to manually add `from __future__ import annotations` in every file. It would be great if `pyugrade` had an option to do the work for me.

**Comment by asottile** [comment]
that's outside the scope of pyupgrade -- it can't know when that's safe to do and it isn't in the spirit of the tool

I'd recommend [reorder-python-imports --add-import 'from __future__ import annotations'](https://github.com/asottile/reorder_python_imports) though -- that's [how I do this](https://github.com/asottile/pyupgrade/blob/1c4dbbf0781e41c4e4a2018d206a01083b3fffe5/.pre-commit-config.yaml#L26-L30)
