### ISSUE TITLE
Add the ability to disable specific upgrades

### ISSUE THREAD

**Issue by vmarkovtsev** [asottile/pyupgrade#63]
E.g. our style guide forces printf-like syntax (we switch to C-like languages often and cut the corners) and we have to revert the corresponding upgrades as in https://github.com/src-d/ml/pull/322#pullrequestreview-162382042

So would be nice to enable/disable features besides the master switch by Python version.

**Comment by asottile** [comment]
I'd suggest letting go of the times.  printf-style formatting has been replaced (twice now! first with `.format()` and next with f-strings).

pyupgrade is an opinionated tool and will not be enabling opt-out of features except by language version.

**Comment by asottile** [comment]
If you're not convinced, I'd suggest reading through https://pyformat.info -- and perhaps [this list of oddities](https://twitter.com/codewithanthony/status/970182992885817344)

**Comment by vmarkovtsev** [comment]
@asottile No need to convince me since I mentioned the reason which has nothing to do with Python at all. Let me troll you some more: we also use double quotes hehe.

No worries. I will fork the project for our org and will maintain it under a different package name.
Thanks for pyupgrade btw! :heart:

**Comment by hugovk** [comment]
That was my PR, and the `.format()` change is the most common criticism in pyupgrade PRs to other projects too.

[One](https://github.com/pytoolz/toolz/pull/417#issuecomment-427505275) is that `.format()` is slower than `%` formatting (eg. 367 nsec v. 243 nsec),  even if that probably is premature optimisation. At least I find `.format()` clearer, and clearer code is usually better than ever so slightly faster code.

Another is that `%` formatting isn't deprecated so there's no point changing it, or that there's nothing wrong with `%` formatting so it's not worth the code churn.

Some just prefer the old style, especially for those switching between languages (like @vmarkovtsev).

@vmarkovtsev Please let me know when the fork is ready, it'd be useful for those cases when needing to revert and redo. Thanks!

**Comment by asottile** [comment]
Without conversion there's no direct conversion to f-strings which _are_ faster.

If you're worried about performance differences between % formatting and .format() you're using the wrong language, python is slow.

**Comment by asottile** [comment]
This is available in 1.8.0.

**Comment by vmarkovtsev** [comment]
LOL

I knew your nerves would not bare this :laughing: That's a pity - I have just [passed through the CI checks](https://github.com/vmarkovtsev/pyupgrade-opt/pull/1) and prepared the fork for pypi.

**Comment by nonchris** [comment]
Hi. It's been some time.
But I'd love to hop in and ask for the same disable feature for the "redundant open" correction.
Yeah, I know. It's redundant, we could let it go.
But as the second sentence of the zen of python says:
> Explicit is better than implicit.
Just make it possible for us to state explicitly that this is just a read-operation. It makes the code better readable.

Thanks for considering my request!

**Comment by asottile** [comment]
no means no
