### ISSUE TITLE
Feature Proposal: Rewrite `unittest.makeSuite|getTestCaseNames|findTestCases`.

### ISSUE THREAD

**Issue by sallner** [asottile/pyupgrade#631]
With the patch [bpo-5846](https://github.com/python/cpython/pull/28382) three methods from the `unittest` module have been deprecated. It can be substituted by `unittest.defaultTestLoader.loadTestsFromTestCase|getTestCaseNames|findTestCases`. (https://github.com/zopefoundation/zope.security/pull/84)

Would it be an option to include this fix in `pyupgrade` and would you accept such a fixer? This would help a lot with the whole range of `zope.*` packages.

**Comment by asottile** [comment]
there's already a unit test rewriter, it would just need to learn about these functions, would you like to contribute a patch?

**Comment by sallner** [comment]
Thank you for the hint. I can try that.

**Comment by cj81499** [comment]
Hey @asottile and @sallner. I took a shot at implementing this. Take a look when you get a chance :)
