### ISSUE TITLE
Document meaning of version flags

### ISSUE THREAD

**Issue by natknightwgu** [asottile/pyupgrade#635]
While adopting this package it wasn't clear to me whether `--py3X-plus` means "this will add features from Python 3.X plus" or "this assumes you're running Python 3.X plus". On reflection, I think only the latter makes sense, but it would be nice to have that confirmed in the documentation.

**Comment by asottile** [comment]
both of those interpretations are the same so I don't think this needs clarification

**Comment by natknightwgu** [comment]
Sorry, obviously I didn't express that very well 😅

What I was looking for when adopting the package was whether setting `pyupgrade` to run automatically might break my code by adding features from a Python that I haven't adopted yet. My understanding is that `--py38-plus` means "running `pyupgrade` on your code won't break you if you're running Python 3.8 or greater" not "running `pyupgrade` on your code will add all features from Python 3.8 or greater, breaking your code if it grabs a Python 3.10 feature while you're on Python 3.9". In retrospect, I think only the first meaning makes sense, but I couldn't find any indication.

If a PR would be clearer I'd be happy to put one together.

**Comment by asottile** [comment]
no thanks, I think it's pretty obvious what it means and the docs are fairly clear on which features are enabled when

**Comment by natknightwgu** [comment]
Fair enough. Thanks for the swift reply, and the very useful package :+1:
