### ISSUE TITLE
`--py311-plus` should not unquote annotations

### ISSUE THREAD

**Issue by JelleZijlstra** [asottile/pyupgrade#637]
https://github.com/asottile/pyupgrade#remove-quoted-annotations says that `--py311-plus` will remove quoted annotations. I suppose that was done under the assumption that PEP 563 (`from __future__ import annotations`) would become the default in 3.11, but that's not happening. (And probably not in the future either.)

**Comment by JelleZijlstra** [comment]
Happy to contribute a PR for this if you agree.

**Comment by asottile** [comment]
ah yes, that was supposed to be cleaned up with the other revert but looks like it got missed: https://github.com/asottile/pyupgrade/blob/cada1f22b4132d6f2c97846b7985a28ac040d554/pyupgrade/_plugins/typing_pep563.py#L20

**Comment by Molkree** [comment]
> PEP 563 (`from __future__ import annotations`) would become the default in 3.11, but that's not happening

@JelleZijlstra, where can I read about this? [Doc](https://github.com/python/cpython/blob/f0614ca9801d0768094570b784d2b26936bcca34/Doc/library/__future__.rst) for `__future__` still mentions 3.11.

**Comment by JelleZijlstra** [comment]
> > PEP 563 (`from __future__ import annotations`) would become the default in 3.11, but that's not happening
> 
> @JelleZijlstra, where can I read about this? [Doc](https://github.com/python/cpython/blob/f0614ca9801d0768094570b784d2b26936bcca34/Doc/library/__future__.rst) for `__future__` still mentions 3.11.

Right, I filed an issue for that too :) https://github.com/python/cpython/issues/92436

https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/ is the announcement for delaying it from 3.11.

My sense (based on discussions at PyCon) is that we'll end up with some form of PEP 649 behavior in 3.12, but that's not yet decided.
