### ISSUE TITLE
Fix multiple isinstance six types

### ISSUE THREAD

**Issue by vyahello** [asottile/pyupgrade#640]
The issue is partly related to https://github.com/asottile/pyupgrade/issues/502

Input code snippet (with pyupgrade --py38-plus option):
```python
isinstance(var, (dict, list, tuple, six.integer_types, float, bool, six.string_types))
```

Actual output:
```python
isinstance(var, (dict, list, tuple, (int,), float, bool, (str,)))
```

Expected output:
```python
isinstance(var, (dict, list, tuple, int, float, bool, str))
```

**Comment by asottile** [comment]
this isn't broken, nested tuples work fine there (that's what the original code did)
