### ISSUE TITLE
Replace typing imports with collections.abc imports where possible

### ISSUE THREAD

**Issue by NeilGirdhar** [asottile/pyupgrade#660]
In Python 3.9, ABC type annotations imported from typing should be replaced with annotations from `collections.abc`.  For example,
```python
from typing import Sequence
```
is supplanted by
```python
from collection.abc import Sequence
```

I believe the list of supplanted classes is: `AsyncGenerator`, `AsyncIterable`, `AsyncIterator`, `Awaitable`, `ByteString`, `Callable`, `Collection`, `Container`, `Coroutine`, `Generator`, `Hashable`, `ItemsView`, `Iterable`, `Iterator`, `KeysView`, `Mapping`, `MappingView`, `MutableMapping`, `MutableSequence`, `MutableSet`, `Reversible`, `Sequence`, `Set`, `Sized`, and `ValuesView`.

This is related to #606 and https://github.com/PyCQA/isort/issues/1914.

**Comment by asottile** [comment]
please search the issue tracker next time!  #558
