### ISSUE TITLE
Possible branch elimination with ImportError traps

### ISSUE THREAD

**Issue by sirosen** [asottile/pyupgrade#682]
I found an interesting case which could *maybe* be handled by `pyupgrade`. If so, I'd be happy to give it a shot! But before I start, I want to confirm that it's desirable and get any pointers on how to approach it.

Code which does an `except ImportError` trap to handle moved modules or module contents may find that pyupgrade produces two identical documents. e.g.
```diff
 try:
+    from collections.abc import Sequence
-    from collections import Sequence
 except ImportError:
     from collections.abc import Sequence
```

I think that if we see a tree like `try(<ast-tree1>)-except(<ast-tree2>)` with no finally or else clause, then as long as `<ast-tree1>` and `<ast-tree2>` are the same, we can eliminate the try-except.

Is this interesting and worthwhile? Is it too hard to do reliably?

---

Aside: I don't know if runs of `pyupgrade` on really old codebases are interesting to mine for details or not, but I just ran `pyupgrade --py36-plus` on `nose2` as one of my first stages of work on a python3-only version: https://github.com/nose-devs/nose2/commit/65ee88b9b3446f0e140f30c9172c88dec208e28b

So far, this is the only thing I've found which I think could be handled even better by `pyupgrade`. Keep up the awesome work!

**Comment by asottile** [comment]
you should write those as `if sys.version_info` (it's more correct and less error prone) and then pyupgrade will do the right thing
