### ISSUE TITLE
Auto-detect minimal Python version

### ISSUE THREAD

**Issue by kdeldycke** [asottile/pyupgrade#688]
My proposition is to have `pyupgrade` auto detect the minimal Python version targeted by a project and set by itself the `--py3-plus` /  `--py36-plus` / `(...)` / `--py311-plus` option flags.

I [hacked this autodetection feature in my GitHub workflows](https://github.com/kdeldycke/workflows/blob/main/.github/workflows/autofix.yaml#L61-L89) by inspecting the `pyproject.toml`.

Note this [feature is also considered by `black`](https://github.com/psf/black/issues/3124) and [discussed for `mypy`](https://github.com/python/mypy/issues/13294).

**Comment by SamirPS** [comment]
If a new version of python is out you will need to modify the file no ? Can we erase the check <= 11 ?

**Comment by kdeldycke** [comment]
Oh I see. I initially added that upper limit to make sure I'll not feed `pyupgrade` with options not recognized yet. Like in the time frame between new major Python versions and `pyupgrade` releases.

But I'm OK with removing that limit. I might be helpful to have it fail in this time-frame, as a reminder to have `pyupgrade` updated! :)

Just fixed this in https://github.com/kdeldycke/workflows/commit/211f3a4626a717cf119825e034da607d77d11156

**Comment by SamirPS** [comment]
Does PyUpgrade have a error if I enter --py-314-plus ?

**Comment by kdeldycke** [comment]
It does:
```shell-session
❯ pyupgrade --py34-plus ./meta_package_manager/tests/test_cli_installed.py
usage: pyupgrade [-h] [--exit-zero-even-if-changed] [--keep-percent-format] [--keep-mock]
                 [--keep-runtime-typing] [--py3-plus] [--py36-plus] [--py37-plus] [--py38-plus]
                 [--py39-plus] [--py310-plus] [--py311-plus]
                 [filenames ...]
pyupgrade: error: unrecognized arguments: --py34-plus
```

**Comment by SamirPS** [comment]
I thinks you change need to add your code here : https://github.com/asottile/pyupgrade/blob/main/pyupgrade/_main.py

**Comment by asottile** [comment]
no thanks -- that would involve reading configuration files of which I don't want anything to do with that complexity

**Comment by kdeldycke** [comment]
OK no worries, I understand the policy of keeping `pyupgrade` to the essentials. I'll keep my hack confined to my GitHub workflows then.

**Comment by kdeldycke** [comment]
Oh, and thanks @asottile for `pyupgrade` it's a really cool project. Love it!
