### ISSUE TITLE
Rewrite `re.Match.group(x)` to `re.Match.__getitem__(x)`

### ISSUE THREAD

**Issue by ngnpope** [asottile/pyupgrade#689]
Python 3.6 added [`Match.__getitem__()`](https://docs.python.org/3/library/re.html#re.Match.__getitem__) which can be used in place of [`Match.group()`](https://docs.python.org/3/library/re.html#re.Match.group):

```diff
 m = re.match(r"(\w+) (\w+)", "Isaac Newton, physicist")
-m.group(2) == "Newton"
+m[2] == "Newton"
```

It might be nice to rewrite these.

**Comment by asottile** [comment]
this is not possible without type analysis
