### ISSUE TITLE
Preserve comments when rewriting NamedTuples to class style

### ISSUE THREAD

**Issue by PeterJCLaw** [asottile/pyupgrade#697]
``` diff
 from typing import NamedTuple
 
-Thing = NamedTuple('Thing', (
-    ('value', int),  # comment
-))
+class Thing(NamedTuple):
+    value: int
```
Ideally the comment should be preserved.

**Comment by asottile** [comment]
this isn't feasible -- for instance what should it do for

```python
Thing = NamedTuple('Thing', (  # comment1
    # comment2
    ('value', int),  # comment3
    # comment4
))  # comment5
```

**Comment by asottile** [comment]
also please search the issue tracker next time, there are several duplicates

**Comment by PeterJCLaw** [comment]
> this isn't feasible -- for instance what should it do for
> 
> ```python
> Thing = NamedTuple('Thing', (  # comment1
>     # comment2
>     ('value', int),  # comment3
>     # comment4
> ))  # comment5
> ```

I suggest either rejecting the block or doing this:

```python
class Thing(NamedTuple):  # comment1
    # comment2
    value: int  # comment3
    # comment4
  # comment5
```

This may not be the prettiest, but avoids throwing away information. Yes, most users _probably_ are using version control, however I suspect some aren't. Even those using version control are likely to miss this sort of thing if making changes to a non-trivial codebase -- I don't particularity fancy reviewing automated changes to projects over about 1k LOC, do you?

> also please search the issue tracker next time, there are several duplicates

Apologies, however does the repeated reporting of this not suggest it's worth doing something about? Even just rejecting the block would be preferable IMO.
