### ISSUE TITLE
Remove unused `Optional`, `Union`, etc. imports when targeting 3.10

### ISSUE THREAD

**Issue by mattholden** [asottile/pyupgrade#698]
In our precommit process, we use both `pyupgrade` and `flake`, which runs on some code that is auto-generated from yet another library. Unfortunately, we can't currently get that library to write the `type | null` or `type | othertype` syntax; it still writes `Optional[type]` or `Union[type, othertype]`. The `pyupgrade` tool nicely replaces those for us, but it doesn't then detect that the `from typing import Optional, Union` statement is no longer needed, and leaves it in -- which `flake` then flags and prevents the build from completing. 

It would be awesome if targeting 3.10 could remove the newly-unused imports where they are detected.

**Comment by asottile** [comment]
search the tracker next time https://github.com/asottile/pyupgrade/issues?q=is%3Aissue+unused+import+is%3Aclosed
