### ISSUE TITLE
`pyupgrade` is not idempotent: upgrading %-formatting to f-strings takes two passes.

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#703]
```
$ echo '"%s, %r" % (x, y)' > example.py

$ pyupgrade --py36-plus example.py 
Rewriting example.py

$ cat example.py 
"{}, {!r}".format(x, y)

$ pyupgrade --py36-plus example.py
Rewriting example.py

$ cat example.py
f"{x}, {y!r}"
```

I think this is probably just a matter of pass ordering, and would be fixed if the percent-formatting fixer ran before the f-strings fixer?

**Comment by asottile** [comment]
it _is_ idempotent -- it just needs two passes

there isn't really too much that can be done about this (there's a few other multi-pass things as well)

patches welcome, but it's unlikely to happen

**Comment by Zac-HD** [comment]
Fair enough, running a second pass is not a big deal for `shed` but we have looser perf targets than you do 🙂

**Comment by asottile** [comment]
shed's also in unsupported territory :P

**Comment by Zac-HD** [comment]
I should hope so!  Wouldn't have even reported it if I couldn't reproduce via your actual interface 😁

**Comment by asottile** [comment]
fwiw you're also missing the MIT license attribution for the bits lifted from blacken-docs

**Comment by Zac-HD** [comment]
Ah, I hadn't considered it a 'substantial portion' since it's really just some regex patterns and the textwrap logic, both rewritten, and there *are* notes in the readme and code comments.  If you have a suggested form of attribution I'd be very happy to add it though!
