### ISSUE TITLE
pyupgrade not listed at official "Supported hooks" page?

### ISSUE THREAD

**Issue by hartwork** [asottile/pyupgrade#71]
Hi!

Nice tool! I noticed that it's not listed at https://pre-commit.com/hooks.html although I suppose it should be? I didn't find the pre-commit website as a repository on GitHub so I thought I'd report here for a start. Any ideas how to get it listed?

Best, Sebastian

**Comment by asottile** [comment]
Seems there to me :)

The website is hosted from https://github.com/pre-commit/pre-commit.github.io

[Here's the line for pyupgrade](https://github.com/pre-commit/pre-commit.github.io/blob/d74edadf34f6edb3f36fe34564179fa4bef911c7/all-repos.yaml#L22)

**Comment by hartwork** [comment]
You're right! Turns out I had "Whole words" activated when searching for it in the browser, by mistake. Sorry for the noise!

**Comment by asottile** [comment]
:+1: no problem!
