### ISSUE TITLE
Mypy conflicts resolving types inside a class namespace

### ISSUE THREAD

**Issue by taoufik07** [asottile/pyupgrade#713]
Hello Anthony,

When upgrading to python 3.10, we faced this [issure](https://github.com/python/mypy/issues/12570) about mypy not being able to properly resolve types inside a namespace.

This breaks the type checking and can sometimes fail silently if the shadowing attribute is `Any` or if it's compatible with the shadowed type e.g. parent/child class.

For now the only safe workaround is to pass `--38-plus` as the the `3.9` comes with PEP 585.

I know we're not going to be missing much (PEP 604 and no quoted annotations) if we pass `--38-plus` to pyupgrade, but do you think it would be possible to add a flag to ignore typing rewrites (probably extend the keep runtime typing flag to support >=3.9?) ? Or we just add some notes and wait for mypy to fix it?

**Comment by asottile** [comment]
that isn't a mypy bug, that's just how namespace resolution works. I'd recommend you rename your variables or use type aliases
