### ISSUE TITLE
Feature request:  mechanism to enable/disable per-feature fixes

### ISSUE THREAD

**Issue by mkillianey** [asottile/pyupgrade#720]
I have a large codebase that I am upgrading from Python3.6 to 3.8, and I would love to use `pyupgrade` on it.  However, running it on our codebase creates so many changes that is difficult to review.

Ideally, I would love to use `pyupgrade` to fix the code incrementally, one category at a time.  (For example I might start with a repo-wide change that fixes _just_ the `is / is not` comparison to constant literals, since it's straightforward to understand that this will be a warning in 3.8 and easy to review.)

Would you be willing to support some kind of configuration file that lets you enable/disable individual upgrades?

**Comment by asottile** [comment]
please search the issue tracker

**Comment by mkillianey** [comment]
Ah, I see in https://github.com/asottile/pyupgrade/issues/516
