### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by EwoutH** [asottile/pyupgrade#722]
A changelog would be a great way to keep track of new features, depreciations, bug fixes and other changes to pyupgrade. The changelog can have different forms, [keep a changelog](https://keepachangelog.com/) provides a nice starting place.

Semi-automated changelog generation is also possible, for example using GitHub's [Automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).

**Comment by asottile** [comment]
https://github.com/asottile/pyupgrade/issues?q=is%3Aissue+changelog+is%3Aclosed
