### ISSUE TITLE
NamedTuple backward-compatible usage and pre PEP-585 types is converted fully only in two passes

### ISSUE THREAD

**Issue by rominf** [asottile/pyupgrade#730]
# Steps to reproduce

1. Create file with `NamedTuple` backward-compatible usage and pre PEP-585 types:
```python
# /tmp/test.py
from typing import NamedTuple, List


T = NamedTuple("T", [("f", List[int])])
```
2. Run pyupgrade once:
```shell
pyupgrade --py310-plus /tmp/test.py
```
3. Observe `List` not touched:
```python
# /tmp/test.py
from typing import NamedTuple, List


class T(NamedTuple):
    f: List[int]
```
4. Run pyupgrade again:
```shell
pyupgrade --py310-plus /tmp/test.py
```
5. Observe `List` converted to `list`:
```python
# /tmp/test.py
from typing import NamedTuple, List


class T(NamedTuple):
    f: list[int]
```

# Expected behaviour
Observation from step (5) on step (3).

# Environment
pyupgrade 3.0.0
Python 3.11.0rc2

**Comment by asottile** [comment]
yeah there's a handful of things which take two passes

there's not too much that can be done about most of them
