### ISSUE TITLE
Breaking in v3.0.0?

### ISSUE THREAD

**Issue by WhyNotHugo** [asottile/pyupgrade#732]
Any hints on what breaks backwards compat for [v3.0.0](https://github.com/asottile/pyupgrade/releases/tag/v3.0.0)?

**Comment by WhyNotHugo** [comment]
Ah, I guess this? https://github.com/asottile/pyupgrade/commit/57eb8ab065eac794deebfb91f20768b3b8455eef

**Comment by sadikkuzu** [comment]
@WhyNotHugo https://youtu.be/ybdqWH3jPq0
