### ISSUE TITLE
PEP585: `typing.Type` within a namespace that defines `type` should not be translated

### ISSUE THREAD

**Issue by akx** [asottile/pyupgrade#735]
```python
from typing import Type

class BaseObject:
    pass


class Example:
    type = "foo"

    def get_object_cls(self) -> Type[BaseObject]:
        raise NotImplementedError('...')
```

is translated into

```python
class BaseObject:
    pass


class Example:
    type = "foo"

    def get_object_cls(self) -> type[BaseObject]:
        raise NotImplementedError('...')
```

which naturally fails at runtime with

```
Traceback (most recent call last):
  File "/Users/akx/build/pyupgrade/ex.py", line 7, in <module>
    class Example:
  File "/Users/akx/build/pyupgrade/ex.py", line 10, in Example
    def get_object_cls(self) -> type[BaseObject]:
TypeError: string indices must be integers
```

since `type` in that namespace is a string.

(My concrete use case is a Django model that defines `type = models.CharField(...)` and so I get "CharField is not subscriptable".)

The workaround is naturally to add `from __future__ import annotations` to affected files and deal with whatever possible semantic issues that causes elsewhere.

**Comment by asottile** [comment]
this doesn't really seem worth fixing, I'd recommend `annotations` or really just renaming `type` to something that doesn't clobber builtins

**Comment by akx** [comment]
I don't think having to rename `type` is an option in the general case. E.g. for an `Event` dataclass, you'd want to be able to do `event.type`, not `event.event_type` or similar.

`annotations` as a workaround does work, sure.

**Comment by asottile** [comment]
it's more that reassigning builtins is sorta garbage in garbage out more than anything
