### ISSUE TITLE
Using syntax of future releases when __future__ is imported

### ISSUE THREAD

**Issue by bossenti** [asottile/pyupgrade#737]
I stumbled about the following behavior of `pyupgrade`  (using version `3.1.0`).
For the given class
```
from typing import List, Optional

class Test:
    a: List[str]
    b: Optional[int]
```

running pyugrade with `pyupgrade --py39 test.py ` delivers the expected result:
```
from typing import Optional

class Test:
    a: list[str]
    b: Optional[int]
```

However, having the following import statement additionally `from __future__ import annotations` the same command results in
```
from __future__ import annotations

class Test:
    a: list[str]
    b: int | None
```
The output already uses syntax of Python 3.10 which should not happen imho.
I would assume that this traces back to the usage of `__future__`.
Nevertheless, I would expect this behavior only when using `--py39-plus` as argument for `pyupgrade`.

**Comment by asottile** [comment]
read the README
