### ISSUE TITLE
Run 'extraneous parens in print(...)' only

### ISSUE THREAD

**Issue by dyollb** [asottile/pyupgrade#740]
Hi,

We have a python codebase that still has to be py27 compatible. That causes issues with qa tools that use the AST to analyze/fix. 

As referenced in your readme *2to3* creates 'extraneous parens in print(...)'. py3-plus fixes those nicely but does other transformations, like removing `from __future__ import print_function`.

Is there a way to run only the extra bracket removal? Or could this be a new option `--py2-py3` (feature request)?

**Comment by asottile** [comment]
the python 2.x compatible mode was removed in pyupgrade 3.x

it's 2022, it's time to move on -- if you want support for the old mode I'd recommend your company sponsor the work and I can maintain a custom version for you
