### ISSUE TITLE
Have an option to only print differences

### ISSUE THREAD

**Issue by 0ssigeno** [asottile/pyupgrade#742]
Hi!
Is it possible to have an option to only check the files and print the differences, without actually change anything? 
Use case: having pyupgrade as a step in the CI that fails if the code syntax is upgradable (like flake, black, autoflake, bandit, isort supports)

**Comment by 0ssigeno** [comment]
After posting this, I saw that there are other closed issues about the same thing (I know, I should have checked beforehand).
If you think that the feature could benefit other people, I could work on this; otherwise, fell free to close this

**Comment by asottile** [comment]
search the tracker next time, thanks!
