### ISSUE TITLE
--py311-plus: G[Unpack[T]] => G[*T]

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#744]
part of https://peps.python.org/pep-0646/

**Comment by MarcoGorelli** [comment]
I could give this a go, just a bit confused from reading the PEP:
```
# Unpacking using ``Unpack`` in older versions of Python
class Array(Generic[Unpack[Shape]]): ...
```
How does one access `"Unpack"` in older versions? `from typing import Unpack` only seems to work in `python 3.11`.

**Comment by asottile** [comment]
`typing_extensions` has an `Unpack` -- @tusharsadhwani might also be working on this one too

**Comment by tusharsadhwani** [comment]
I'm working on it :D
