### ISSUE TITLE
Get minimal python version from `.python-version` file

### ISSUE THREAD

**Issue by herrbenesch** [asottile/pyupgrade#746]
Hi,

thanks for the great project! It adds real value to our work.
I would appreciate your opinion on the proposal I'm making here:
---
### Our issue:
When we upgrade our python version, the e.g. `--py310-plus` flag oftentimes will be forgotten.
We are using pipenv and the tools on our stack get the python version from either our Pipfile or the `.python-version` file.

### My proposal to solve our issue:
I had a command line argument in mind that would tell `pyupgrade` to get the minimal python version from the application-specific `.python-version` file.
Something in the realms of `pyupgrade file.py --local-python-version-plus`
If it would not find that file, it would raise an error.

This would solve our case specifically but also could be expanded to look for a local python version in other places.

---
I you think this would be a useful addition and also something that sounds doable for this project, let me know and I'll make sure to open a PR.

**Comment by asottile** [comment]
no thanks
