### ISSUE TITLE
pre-commit fails

### ISSUE THREAD

**Issue by scarrazza** [asottile/pyupgrade#748]
Dear developers, since the 3.x release series, we are getting errors with github's pre-commit bot when including pyugrade, see [this report](https://results.pre-commit.ci/run/github/241307936/1667290058.iiBn8IzBQPq-jKv_13fRuA), while with versions < 3.x, all tests pass. Looks like pyupgrade is not rewriting files and I can reproduce locally using [this configuration](https://github.com/qiboteam/qibo/blob/9a688a1e4557032ee1b632d743d861aafa6411eb/.pre-commit-config.yaml).

**Comment by asottile** [comment]
you have two conflicting hooks -- try running either one by themselves

**Comment by asottile** [comment]
pyupgrade is py3+ only now -- you can remove `fix-encoding-pragma` entirely

**Comment by scarrazza** [comment]
Thank you very much for the information.
