### ISSUE TITLE
Replace ISO 8601 date parsing hack in Python 3.11

### ISSUE THREAD

**Issue by Sinclert** [asottile/pyupgrade#753]
Python 3.11 introduced support for ISO 8601 date strings ([reference](https://docs.python.org/3/whatsnew/3.11.html#datetime)) in functions:

- `datetime.datetime.fromisoformat()`.
- `datetime.date.fromisoformat()`.
- `datetime.time.fromisoformat()`.

A common hack prior to Python 3.11 was to replace the possible `Z` character at the end of a date string for `+00:00` or `-00:00`, so it could be parsed. AFAIK, this is no longer needed, which means the following simplification could be added to this project:

```diff
- datetime.fromisoformat(date_string.replace("Z", "+00:00"))
+ datetime.fromisoformat(date_string)

- datetime.fromisoformat(date_string.replace("Z", "-00:00"))
+ datetime.fromisoformat(date_string)
```

```diff
- time.fromisoformat(date_string.replace("Z", "+00:00"))
+ time.fromisoformat(date_string)

- time.fromisoformat(date_string.replace("Z", "-00:00"))
+ time.fromisoformat(date_string)
```

👆🏻 Please note that these examples use `date_string` as an example name, final implementation must consider any name.

**Comment by asottile** [comment]
without knowing the exact type and value of `date_string` this _could_ change behaviour -- so while this is _usually_ safe I don't think we can do it here
