### ISSUE TITLE
Providing a folder name to pyupgrade shows misleading error message

### ISSUE THREAD

**Issue by ArneBachmannDLR** [asottile/pyupgrade#754]
Using `pyupgrade --py3x-plus mypackagefolder` returns a `PermissionError: [Errno 13] Permission denied: 'mypackagefolder'` on Windows. It took me a while to interpret this as a user error, not a permission error.

The correct use seems to be `for %f in (mypackagefolder\*.py) do pyupgrade --py3x-plus %f`, which is pretty cumbersome, makes many calls, and is non-recursive.

Could you extend the command-line logic to automatically detect if the argument is a (package) folder and iterate over its Python source files?

**Comment by asottile** [comment]
please search the issue tracker next time, there are many duplicates

**Comment by ArneBachmannDLR** [comment]
Well yeah I checked the open issues, obviously.

I only found https://github.com/asottile/pyupgrade/issues/40 which was closed as out of scope, but I think implementing a simple glob on a folder might very well be a commonly expected and useful feature.
Many similar tools provide a `-m` option to pass a package name, mimicking the `python -m` option.

Let me know how I can help.

**Comment by asottile** [comment]
#40 is a very clear NO

**Comment by ArneBachmannDLR** [comment]
It's your decision and you seem firm on it, but I think using pre-commit hooks is not very popular under Windows development systems due to the reduced user experience in the batch shell. Therefore the argument *just use pre-commit - it solves most problems anyway* is simply not applicable for me as a on-Windows dev.

**Comment by asottile** [comment]
`pre-commit run pyupgrade --all-files` works just fine on windows
