### ISSUE TITLE
Add the ability to disable pyupgrade for a file

### ISSUE THREAD

**Issue by mambelli** [asottile/pyupgrade#757]
I have a big project in python and shell.
One directory contains scripts that must be compatible with both python 3 and python 2.
I'm running pyupgrade via pre-commit and it is breaking the python 2 compatibility for the directory mentioned above.
Currently, I see only the possibility to disable pyupgrade for the whole project. I'd like to keep it for the other files.
I did not find a way to solve this.

I'd like to have the possibility to disable pyupgrade for a file, either via a pragma in the comments or via a command line argument to add in pre-commit config.
Thank you

**Comment by asottile** [comment]
try reading up on how to configure `pre-commit` -- part of the point of pre-commit is that every tool doesn't need to implement this -- if you're still stuck after reading that I can give you the answer but teach a man to fish

**Comment by mambelli** [comment]
I did not know of the per-hook file patterns independent from tool options. `pre-commit` is more powerful than I thought. Thanks.
