### ISSUE TITLE
Update the documentation for the lack of recursive directories.

### ISSUE THREAD

**Issue by tatarize** [asottile/pyupgrade#776]
Recursive directories takes 1 rather small function to work exactly like black, flake8, flynt, etc. It might be reasonable to, if nothing else, avoid people trying to patch this glaring deficiency, to add some documentation as note this is not and cannot be used as a standalone tool. 

See #775, #509, #440 #395, #344, #150, #46, #40.

At a certain point you should document a multi-year crusade against adding a simple function and working like the rest of the python tools ecosystem. And demanding a complete change to your workflow to run the tool one time.
 
It seems reasonable to at least note this tool is not useful as a stand alone tool because adding 20 lines of a PR is too extreme but using an entirely different workflow is preferred, rather than the using the same use case as literally every other tool out there. It just looks like you somehow wrote this and never thought to make it work like every other tool.

If nothing else, you could stop the PRs.

**Comment by asottile** [comment]
it's not "one simple function" -- I maintain flake8 and it's one of the most complicated parts.  rather than every tool implementing `xargs` poorly just use `xargs`

also adjust your attitude, it's not appreciated
