### ISSUE TITLE
Support for user defined import transforms?

### ISSUE THREAD

**Issue by jenshnielsen** [asottile/pyupgrade#777]
I have been performing a number of refactoring on a library of mine. In order to update examples and give users an easy way to update their code it would be cool to be able to do something along the lines of the import updates that pyupgrade does. Now I don't imagine that my library is in anyway big enough to include these transforms directly into pyupgrade but I was wondering if you would be interested in a way for the user to supply additional transforms to perform. 
I imagine that could be done with a command line flag taking a file as input, these transforms would then be appended to [REPLACE_EXACT](https://github.com/asottile/pyupgrade/blob/main/pyupgrade/_plugins/imports.py#L43)

Before proposing such a pull request I wanted to know if there is any interest or if that would be considered out of scope for pyupgrade?

**Comment by asottile** [comment]
use reorder-python-imports
