### ISSUE TITLE
Upgrade Enum str Mixin to StrEnum in Python 3.11

### ISSUE THREAD

**Issue by atugushev** [asottile/pyupgrade#779]
Given that Python 3.11 [introduced](https://blog.pecar.me/python-enum) breaking change for Enum with str/int Mixin wouldn't it make sense to auto-upgrade this to `StrEnum/IntEnum`? For example `pyupgrade --py311-plus`: 

Input:
```
class MyEnum(str, enum.Enum):
    FOO = "foo"
    BAR = "bar"
```

Output:
```
class MyEnum(enum.StrEnum):
    FOO = "foo"
    BAR = "bar"
```

**Comment by asottile** [comment]
I don't really think it's pyupgrade's responsibility to fix cpython's mistakes here

**Comment by asottile** [comment]
and afaict they aren't identical behaviour so it's not a safe upgrade
