### ISSUE TITLE
Percent printf not rewritten

### ISSUE THREAD

**Issue by alok** [asottile/pyupgrade#78]
A file containing
```python
a = 2
b = "%s" % a
```

is not rewritten to use `.format()` unless I wrap the `a` into a one-element tuple like `b = "%s" % (a,)`.

**Comment by asottile** [comment]
The expression alone cannot safely be rewritten, consider:

```
a = (1,)
print('%s' % a)
```

this is part of the reason that %-formatting is sketch

**Comment by asottile** [comment]
Here's the test case which covers this exact case:

https://github.com/asottile/pyupgrade/blob/f6d8d20a4fde83b4090d7910503b82e102a85a33/tests/pyupgrade_test.py#L554-L555

**Comment by jedie** [comment]
Whats about to use flynt for this? maybe include it in pyupgrade?

**Comment by asottile** [comment]
@jedie please read the dupe, it's unsafe

**Comment by asottile** [comment]
that flynt does this is incorrect and **breaks code**
