### ISSUE TITLE
RFE: configparser deprecations/removals

### ISSUE THREAD

**Issue by scop** [asottile/pyupgrade#780]
[configparser](https://github.com/python/cpython/blob/v3.11.1/Lib/configparser.py) contains some deprecated items, some of which will start causing failures as of 3.12. I suppose pyupgrade could fix these up:

- `ParsingError.filename` -> `ParsingError.source`
- `RawConfigParser.readfp` -> `RawConfigParser.read_file`
- `SafeConfigParser` -> `ConfigParser`

All these replacements are available as of 3.2, so I suppose py36plus would be the target.

**Comment by asottile** [comment]
only the last one can be safely rewritten without type information

**Comment by asottile** [comment]
actually looking at this closer there isn't a mechanism for replacing symbols safely so I'm going to decline this
