### ISSUE TITLE
Collecting a definitive answer on no dry run option

### ISSUE THREAD

**Issue by mastercoms** [asottile/pyupgrade#781]
Hi, first off, I want to thank you for this amazingly useful and robust tool. And second, I want to clarify that I mean no ill will by this issue and I just want a greater understanding of the situation. Looking through all the user requests for this feature, the reasons for closing are as follows:

1. Duplicate. (several issues which did not search the issue tracker, but also including the first issue ever reported on this, #210)
2. Can use `git checkout -- .`. (https://github.com/asottile/pyupgrade/issues/258#issuecomment-841595699)
3. Already exits non-zero when modifying files.
4. Use precommit.
5. No interest to add it. (was added non-intrusively in a PR #370)

Forgive me, but I really don't understand why this use case is not being fully addressed, despite the issues with the alternative suggestions and the clear user interest. I mean no disrespect, I don't want to cause a situation like I saw in the other issues.

There are many other integration systems besides precommit, and in local working spaces, it can be hard to run a test suite which destructively changes files in your local copy. Yes, we can git stash including index, and such, then restore afterwards, but this seems convoluted and prone to failure to support this one very useful tool.

I really do appreciate your work, and I just really want to know exactly why the dry run option isn't being included. Is it on principle to encourage use of other tools? Is it maintenance overhead? Are you against dry run tools in general? I don't understand the reasoning or alternatives provided for this use case, please forgive me if I'm being stupid.

And yes, I did read every single issue on this, I went through every single closed issue on the tracker just to make sure I did not miss a search result, just so you know I did my best to not bother you, and I'm sorry for not understanding still: #210 #258 #310 #370 #396 #460 #578 #595 And also I apologize for the spam and abuse you have endured regarding this and other issues, I really do appreciate your work, I just didn't understand the response to this.

**Comment by asottile** [comment]
"I know this is a duplicate but I'm going to ask once more"

imagine if everyone did this. oh wait they do as you can see and yet you chose to pile on one more despite finding a consistent no.
