### ISSUE TITLE
RFE: convert to PEP 584 dict union operators

### ISSUE THREAD

**Issue by scop** [asottile/pyupgrade#783]
Would be nice if `--py39-plus` knew to convert applicable cases to [PEP 584](https://peps.python.org/pep-0584/) dict union operators.

There are quite a few possible eligible constructs, but starting small with "simple" cases would be already useful, for example
- `{**x, **y}` -> `x | y` (for unions of >= 2; `{**x, **y, **z}` etc too)
- `x = {**x, **y}` -> `x |= y` (similarly taking care of >= 1 joined; `x = {**x, **y, **z}` too)

**Comment by nschonni** [comment]
https://github.com/asottile/pyupgrade/issues/321
