### ISSUE TITLE
Rewrite call to importlib.resources to use new API

### ISSUE THREAD

**Issue by Tolker-KU** [asottile/pyupgrade#786]
[importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources) introduced a new API in Python 3.9 and depreacted the old API in Python 3.11. Translations from calls to the old API to calls to the new API is outlined in the docs.

Is it within scope for this project to automatically rewrite these calls? Would be happy to take a stab at it, but want to know what you think about the idea first.

**Comment by asottile** [comment]
it's not in scope
