### ISSUE TITLE
Request for documentation example of running pyupgrade as CLI app

### ISSUE THREAD

**Issue by owenlamont** [asottile/pyupgrade#789]
Before setting up pyupgrade as a pre-commit I wanted to try running it on all the source files in my repo but it wasn't clear from the documentation how to do that, or whether running it as a regular CLI app was supported.

I was hoping both ways might be supported like the [refurb app](https://github.com/dosisod/refurb).

Is there a way to pass pyupgrade a root directory and have it glob and run on all Python files below that?

**Comment by asottile** [comment]
as with any command line tool, run `--help`
