### ISSUE TITLE
Option to disable `Unpacking list comprehensions`

### ISSUE THREAD

**Issue by Skylion007** [asottile/pyupgrade#794]
I wanted to apply this tool to pytorch, but the unpacking list comprehensions may cause issue with codebase as torch.jit.script doesn't have full generator support and the compiler may complain. There doesn't appear to be a way to turn off this fixit either, adding an option to do so would be helpful: https://github.com/pytorch/pytorch/issues/94040

**Comment by asottile** [comment]
you're free to fork -- I'm not going to break my tool to work around a bug in theirs
