### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'builtin_function_or_method' and 'type'

### ISSUE THREAD

**Issue by andreagrandi** [asottile/pyupgrade#796]
Hi, we recently switched the Python runtime to `3.10.9` and we are running into an issue with `pyupgrade`

I had this code:
```python
def initialize(*, transport: Optional[Union[callable, str]] = None):
```
and after I use the `--py310-plus` with `pyupgrade` the code is changed to:
```python
def initialize(*, transport: callable | str | None = None):
```
but after this change, my code (tests) is failing with this error:
```python
TypeError: unsupported operand type(s) for |: 'builtin_function_or_method' and 'type'
```
what am I missing? Thanks

**Comment by asottile** [comment]
callable is not a valid type
