### ISSUE TITLE
PEP585: rewrite generic abstract class imports from `collections.abc` for `--py3{7,8}-plus` when `from __future__ import annotations` is on

### ISSUE THREAD

**Issue by XuehaiPan** [asottile/pyupgrade#799]
Currently, the imports for generic abstract classes from `typing` will be rewritten to import from `collections.abc` only when option `--py39-plus` is on.

https://github.com/asottile/pyupgrade/blob/ddb39ad37166dbc938d853cc77606526a0b1622a/pyupgrade/_plugins/imports.py#L122-L155

When `pyupgrade` is run with `--py3{7,8}-plus` and the source contains `from __future__ import annotations`, it will only rewrite builtin types:

https://github.com/asottile/pyupgrade/blob/ddb39ad37166dbc938d853cc77606526a0b1622a/pyupgrade/_plugins/typing_pep585.py#L15-L17

Since the type annotations are postponed evaluated when `from __future__ import annotations` is on, it is safe to rewrite generic abstract class imports from `typing` to `collections.abc`.

------

A minimal reproduction script:

```python
# test.py

from __future__ import annotations

from typing import Sequence

def foo() -> Sequence[int]:
    return [1, 2, 3]

print(foo())
```

Run `pyupgrade` v3.3.1 with `pyupgrade --py37-plus test.py`:

Unchanged:

```python
# test.py

from __future__ import annotations

from typing import Sequence

def foo() -> Sequence[int]:
    return [1, 2, 3]

print(foo())
```

Run `pyupgrade` v3.3.1 with `pyupgrade --py39-plus test.py`:

```python
# test.py

from __future__ import annotations

from collections.abc import Sequence

def foo() -> Sequence[int]:
    return [1, 2, 3]

print(foo())
```

Run with `python3.7`, no errors with `collections.abc.Sequence`:

```console
$ cat test.py
# test.py

from __future__ import annotations

from collections.abc import Sequence

def foo() -> Sequence[int]:
    return [1, 2, 3]

print(foo())

$ python3.7 test.py
[1, 2, 3]
```

**Comment by asottile** [comment]
it is not generally safe to do so, for example with type aliases
