### ISSUE TITLE
Known future manual upgrades

### ISSUE THREAD

**Issue by jamesmyatt** [asottile/pyupgrade#800]
I have a situation where I know that the syntax can be upgraded (manually) in the future once support for earlier Python versions has been removed. Specifically, I'd like to use `zip(..., equal=True)` from [PEP 618](https://peps.python.org/pep-0618/) once I'm using `--py310-plus`.

This upgrade can't be done automatically, so I think this is out-of-scope for this tool (maybe not), but I would like to record this so that, once the relevant settings have been changed, some tool will automatically flag it, but I can't think of a good approach.

It kind of fits with pyupgrade since that has a notion of target syntax version, but not of identifying manual fixes. What do you suggest?

**Comment by asottile** [comment]
the tool is entirely automatic so this idea is out of scope -- but you're free to write yourself a TODO comment -- I usually grep around for the versions I'm dropping

**Comment by jamesmyatt** [comment]
That's what I thought. Thanks
