### ISSUE TITLE
Type hints are not updated (python 3.10) when using typing module alias

### ISSUE THREAD

**Issue by vyahello** [asottile/pyupgrade#803]
I want to upgrade my codebase type annotations from **python 3.8** to **python 3.10** style to comply with the following peps: 
  - https://peps.python.org/pep-0604
  - https://peps.python.org/pep-0634
  - https://peps.python.org/pep-0635
  - https://peps.python.org/pep-0636

Here is a code snippet:
```python
# foo.py
import typing as tp


def bar(n: tp.List[str]) -> tp.List[str]:
    return n * 2
```

**Expected result**
```bash
➜ pyupgrade --py310-plus foo.py
Rewriting foo.py
```
```python
# foo.py
import typing as tp


def bar(n: list[str]) -> list[str]:
    return n * 2
```

**Actual result**
No changes applied. The above code snippet will be updated when typing module import is used without alias.

**Comment by asottile** [comment]
indeed -- if you don't follow the convention you don't receive the benefits

**Comment by asottile** [comment]
there's at least two duplicates as well -- please search the tracker next time
