### ISSUE TITLE
f-string replacement failing with multiline .format

### ISSUE THREAD

**Issue by egeres** [asottile/pyupgrade#808]
Hey @asottile, thank you a lot for all the hard work you put into this library, it's really helping me to migrate oldish Python code. I've looked through the issues and I haven't seen this one, I hope I'm not missing anything!

So pyupgrade has no issue with this:
```python
# This line
"some text {}".format(5)

# Is turned into this line (as expected)
f"some text {5}"
```

But it seems it doesn't work with:
```python
"some text {}".format(
5)

# Which should be converted to
f"some text {5}"
```
Is this intentional or is it a bug?

**Comment by asottile** [comment]
there's a few dupes -- and a section in the README for this -- please check those first next time!
