### ISSUE TITLE
Feature Request: Exclude lines from conversion with a comment

### ISSUE THREAD

**Issue by BranislavBajuzik** [asottile/pyupgrade#809]
A continuation of a closed and locked issue, https://github.com/asottile/pyupgrade/issues/574

I do understand that pyupgrade is an opinionated tool. It is, however, not a perfect one. There are cases where the fix introduces a bug. 

My options then are:
1. Not use the tool at all, even tho 99.9% of the time it works perfectly
2. If I'm lucky, and there is a flag to disable a fix, I can then disable it across the whole project ([`--keep-mock`](https://github.com/asottile/pyupgrade/issues/314), `--keep-runtime-typing`, and `--keep-percent-format`)
    * This is curious, because configuration is allowed despite the opinionated nature 
4. I can blacklist the problematic file

I would love a 4th option that allows me to disable a single line.

In my case, I have a dataclass that uses `slots=True`. There is a problem with super in there, as described in [this SO answer](https://stackoverflow.com/a/73269092/5712042) so I need to explicitly call `super(MyClass, self)` and it works.

The problem is that pyupgrade then comes along and removes it, assuming that it is always safe to do so (this assumption is wrong, as this is Python, where things can change during runtime, not C)
All of the widely used tools, even opinionated black allow for exceptions for this reason. A simple `# nopyupgrade` and possibly `# pyupgrade: off`+`# pyupgrade: on` would fix this.

Thank you

**Comment by asottile** [comment]
no means no
