### ISSUE TITLE
Bug: super() call in @dataclass(slots=True) causes TypeError

### ISSUE THREAD

**Issue by Gumminess** [asottile/pyupgrade#810]
When running this example you will get `TypeError: super(type, obj): obj must be an instance or subtype of type`

```python
from dataclasses import dataclass
@dataclass(slots=True)
class Base:
    def method(self):
        print("hello")

@dataclass(slots=True)
class Derived(Base):
    def method(self):
        super().method()
        print("world")

Derived().method()
```

The solution is to call `super(Derived, self)` instead of `super()`, as explained [here](https://stackoverflow.com/a/73269092/5712042)

The problem is that pyupgrade simplifies this to just plain `super()`, which is ok in most cases, but not here. As this is a standard behavior of a standard library, there should be a special case for this in pyupgrade.

**Comment by asottile** [comment]
there's a few duplicates. this isn't a pyupgrade problem but a problem with dataclasses

**Comment by bhperry** [comment]
This is a pyupgrade problem. Dataclass with slots creates a new class, because it's required for slots to work. Pyupgrade breaks the required format for datalass super with slots.

**Comment by asottile** [comment]
bet. https://github.com/python/cpython/issues/90562
