### ISSUE TITLE
Replace pipes.quote with shlex.quote

### ISSUE THREAD

**Issue by jooola** [asottile/pyupgrade#812]
The `pipes` module is deprecated starting with python 3.11 and will be removed in python 3.13 https://peps.python.org/pep-0594/#deprecated-modules

I propose to automatically replace the `pipes.quote` function with the `shlex.quote` function starting with python 3.11.

According to https://docs.python.org/3/library/shlex.html#shlex.quote we might event be able to replace this for python >= 3.3. (https://github.com/python/cpython/commit/9bce311ea4f58ec04cab356a748e173ecfea381c)

I am happy to try implementing this  after it is accepted.

**Comment by asottile** [comment]
fun fact you don't need to because it already does
