### ISSUE TITLE
Disable `pyuprade` for a line ❓ 

### ISSUE THREAD

**Issue by aaarrti** [asottile/pyupgrade#814]
Hi, 
thanks for this great pre commit hook, works mostly like a charm!
Is there any possibility to disable substitution for a specific line? Something similar to `# type: ignore` or `# noqa`?
More precisely, I have a codebase, which depends heavily on `functools.singledispatch`, e.g., 
```python
@singledispatch
def func(model: MyOwnType, x_batch: np.ndarray, y_batch: np.ndarray, **kwargs) -> np.ndarray: ...
 
@func.register
def _(model: MyOtherCustomType, x_batch: Union[List[str], np.ndarray, y_batch: np.ndarray, **kwargs): ...
```
Before every commit, it will be re-written into 

```python
@func.register
def _(model: MyOtherCustomType, x_batch: list[str] | np.ndarray, y_batch: np.ndarray, **kwargs): ...
```

Which then results into 

```
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'
```

As a result, rendering the whole library unusable. Is there any way to tell `pyupgrade` to ignore a specific line of code?

**Comment by asottile** [comment]
search the issue tracker

**Comment by rkulinski** [comment]
Maybe that's obvious to you, but where I can find this issue tracker @asottile?
