### ISSUE TITLE
Feature Request: `--py3X-plus` compatibility checking

### ISSUE THREAD

**Issue by jamesbraza** [asottile/pyupgrade#816]
## Motivation

```python
"""file.py"""

def func(arg: list[float]) -> None:  # Signature uses a Python 3.9+ feature
    pass
```

Let's say one runs `pyupgrade --py38-plus file.py` on this `file.py`.  Currently with `pyupgrade==3.3.1`, nothing is output.

Because one passed `--py38-plus`, it's implied `file.py` should support Python 3.8.  However, a Python 3.9+ typing feature was used, so `file.py` is actually incompatible with Python 3.8.

## Request

I know `pyupgrade` is about automatically upgrading to new language features, and there is no `pydowngrade`.  To be clear, this request is not asking for that.

I am wondering if it's tenable to have `pyupgrade` simply report incompatible language features.  So for example:

```bash
> pyupgrade --py38-plus file.py
file.py:3:15: Generic aliasing was added in Python 3.9 (py39-plus)
```

**Comment by asottile** [comment]
what you're asking for has nothing to do with the goals of the tool
