### ISSUE TITLE
visit_Name changes don't seem to modify f-strings

### ISSUE THREAD

**Issue by christianbundy** [asottile/pyupgrade#822]
Hi. I'm working on a plugin and realized that when I make changes with `visit_Name` they aren't reflected in f-strings. Any idea why this might be happening? Here's a reproduction with the PEP 585 rewrite, though it probably goes without saying that this is a contrived example:

## Input

`pyupgrade --py311-plus example.py`

```python3
from typing import List

x: typing.List[int] = [f"{typing.List}"]
```

## Expected

```python3
x: list[int] = [f"{list}"]
```

## Actual

```python3
from typing import List

x: list[int] = [f"{list}"]
```

**Comment by asottile** [comment]
please search the issue tracker for duplicates -- thanks!
