### ISSUE TITLE
Behaviour change after upgrading '%9s' to '{:9}'

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#83]
This pyupgrade change (https://github.com/hugovk/yamllint/commit/25e8e9be0838bff930b3b204360fc24385b6edbf) fails indentation-related unit tests which previously passed:

```diff
-            output += '%9s %s\n' % (token_type,
+            output += '{:9} {}\n'.format(token_type,
                                     self.format_stack(context['stack']))
```

https://travis-ci.org/hugovk/yamllint/jobs/459076859#L860

Small example:

```python
Python 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> '%9s %s\n' % ("abc", "def")
'      abc def\n'
>>> '{:9} {}\n'.format("abc", "def")
'abc       def\n'
```

It would have worked if they were integers:
```python
>>> '%9s %s\n' % (123, 456)
'      123 456\n'
>>> '{:9} {}\n'.format(123, 456)
'      123 456\n'
```

---

Another issue with this example, it'd be nice if the indentation of the second line was adjusted, as this often causes flake8 errors. But I understand if this is out of scope of pyupgrade.

For example, instead of this:

```diff
-            output += '%9s %s\n' % (token_type,
+            output += '{:9} {}\n'.format(token_type,
                                     self.format_stack(context['stack']))
```

Do this:

```diff
-            output += '%9s %s\n' % (token_type,
-                                    self.format_stack(context['stack']))
+            output += '{:9} {}\n'.format(token_type,
+                                         self.format_stack(context['stack']))
```

**Comment by asottile** [comment]
yeah the latter is a bit of an [open problem / known issue](https://github.com/asottile/pyupgrade/blob/bbe34c45db1fa1c54969f590fc35571a636132b4/tests/pyupgrade_test.py#L189) -- the current suggestion is to run through some other pep8 formatter after running

The first problem seems pretty bad though!  I wonder if there's a safe equivalent between the two for this case or if `pyupgrade` needs to timidly drop that formatting like it does with [these other cases](https://github.com/asottile/pyupgrade/blob/bbe34c45db1fa1c54969f590fc35571a636132b4/pyupgrade.py#L559-L581)

**Comment by asottile** [comment]
Seems like `%9s` can safely be rewritten as `{:>9}' -- let me make a PR for this, sorry about that!

**Comment by hugovk** [comment]
Confirmed tests now pass with pyupgrade 1.11.0:

```diff
-            output += '%9s %s\n' % (token_type,
+            output += '{:>9} {}\n'.format(token_type,
                                     self.format_stack(context['stack']))
```
Thanks!
