### ISSUE TITLE
Support ignoring lines

### ISSUE THREAD

**Issue by danielgafni** [asottile/pyupgrade#833]
First of all, I've searched the issue tracker! 

However, I would like to raise this issue again, because the existing answers don't work with my case.

I'm writing library code which behavior is dependent on the type annotations provided by the library user later on. 

I would like to support both `Dict[str, ...]` and `dict[str, ...]`, because I want so support older Python versions. My code would fail if one of them gets removed. 

I don't see how to achieve this behavior without ignoring exactly the `dict[str, ...]` line (I'm running `pyupgrade` with `--py38-plus`).

I think this is a valid concern considering the increasing popularity of the type annotations and their role in runtime logic.

**Comment by asottile** [comment]
the README is short and addresses this exact question

also this is not a charitable approach to open source:

> However, I would like to raise this issue again

it's exhausting to receive the same _already resolved_ queries repeatedly as you can imagine

**Comment by karolzlot** [comment]
One solution is to exclude file from pyupgrade hook
