### ISSUE TITLE
Some `typing_extensions` rewrites are perhaps overly aggressive

### ISSUE THREAD

**Issue by AlexWaygood** [asottile/pyupgrade#842]
Hi, thanks so much for pyupgrade -- I think it's a fantastic tool.

When run with e.g. the `--py39-plus` flag, pyupgrade will currently make the following changes, which are perhaps overly aggressive:

```diff
-from typing_extensions import Protocol
-from typing_extensions import SupportsIndex
-from typing_extensions import NewType
+from typing import Protocol
+from typing import SupportsIndex
+from typing import NewType
```

In the latest version of typing_extensions, several performance improvements (and several bugfixes) from Python 3.12 have been backported to `typing_extensions.Protocol`. The upshot of this is that `isinstance()` checks against runtime-checkable protocols may be 20x faster or more if you're using `typing_extensions.Protocol`. The same rationale applies for why a user might want to use `typing_extensions.SupportsIndex` rather than `typing.SupportsIndex`.

The latest version of `typing_extensions` also backports the implementation of `typing.NewType` from Python 3.10 to older Python versions. In Python 3.10, `NewType` is implemented as a class, which makes newtypes pickleable; on earlier versions of Python, newtypes were not pickleable. (This backport was done in response to [a request from a user](https://github.com/python/typing_extensions/issues/156) who was struggling to use `multiprocessing` with `typing.NewType` on older Python versions due to the fact that newtypes could not be pickled.)

**Comment by asottile** [comment]
if you want to update the symbols they're generated in https://github.com/asottile/reorder-python-imports -- there's already several carveouts for typing-extensions there as well so it's easy to add more
