### ISSUE TITLE
Add switch to avoid %s -> {} when the format strings contains braces

### ISSUE THREAD

**Issue by anntzer** [asottile/pyupgrade#86]
When the format string contains braces, converting %s to {} can be quite unwieldy:
```
$ echo '"{%s, %s}" % (x, y)' >! /tmp/test.py
$ pyupgrade --py36-plus test.py
$ cat test.py
f"{{{x}, {y}}}"
```
A real case (from the Matplotlib examples), involving the generation of TeX strings:
```
-        label = r'$%s_{_{\mathrm{%s}}}$' % (orig_label[0], orig_label[1:])
+        label = r'${}_{{_{{\mathrm{{{}}}}}}}$'.format(orig_label[0], orig_label[1:])
```
I would thus suggest adding a switch `--avoid-brace-brace` (name up to bikeshedding).

**Comment by asottile** [comment]
There's already `--keep-percent-format`, I'd suggest using that -- I don't really want more complexity around this especially that keeps the `%` formatting around :laughing:
