### ISSUE TITLE
Replace `typing.ContextManager` and `typing.AsyncContextManager` by those of `contextlib` on py39+

### ISSUE THREAD

**Issue by francis-clairicia** [asottile/pyupgrade#860]
[`typing.ContextManager`](https://docs.python.org/3.11/library/typing.html#typing.ContextManager) and [`typing.AsyncContextManager`](https://docs.python.org/3.11/library/typing.html#typing.AsyncContextManager) are deprecated since python 3.9, for the same reasons as `collections.abc` aliases

```diff
-from typing import AsyncContextManager, ContextManager
+from contextlib import AbstractAsyncContextManager, AbstractContextManager

-def context() -> ContextManager[None]:
+def context() -> AbstractContextManager[None]:
    ...

-def async_context() -> AsyncContextManager[None]:
+def async_context() -> AbstractAsyncContextManager[None]:
    ...
```

**Comment by asottile** [comment]
these cannot be done safely because the name changes

**Comment by francis-clairicia** [comment]
What about using `from contextlib import AbstractContextManager as ContextManager` ?

**Comment by asottile** [comment]
imo that's strictly worse

**Comment by francis-clairicia** [comment]
I tried 😂 But yes I see the point
