### ISSUE TITLE
Rewrite dependency definitions in config files?

### ISSUE THREAD

**Issue by kytta** [asottile/pyupgrade#863]
Please don't bash me for this one :D I know Anthony and others don't want to add complexity to this tool, and I'm fine with this. I also think that reading config files adds lots of unnecessary complexity, but...

...What about the idea of rewriting dependencies in `setup.py`, `setup.cfg`, and/or `pyproject.toml` that have the Python version constraint? A typical example would be `importlib_metadata`, which gets included on Python 3.7 and below for the sake of querying the version. Running `pyupgrade --py38-plus` could then remove not just the Python if-block, but also the dependency from the list.

**Comment by asottile** [comment]
this is out of scope
