### ISSUE TITLE
Add option to disable certain plugins

### ISSUE THREAD

**Issue by deepyaman** [asottile/pyupgrade#864]
I recently used `pyupgrade --py39-plus` for a project that dropped Python 3.8 support. Related to https://github.com/asottile/pyupgrade/issues/415, I can't (fully) accept the PEP 604 rewrites, because we depend on Pydantic in places. However, we have no problem with PEP 585, and I would like to make sure we're taking advantage of PEP 585 wherever possible; as such, I don't want to pass `--keep-runtime-typing`. I also still want to use `from __future__ import annotations`; otherwise, a lot of typing forward references stop working in our code.

Therefore, what I want to do is disable the PEP 604 plugin. I assume it would be fairly easily to support an option to disable certain plugins (e.g. `pyupgrade --py39-plus --disable=typing_pep604`), by just having the option modify plugin collection, but I wanted to see if this was something `pyupgrade` would consider supporting. For now, what I've done (that works well enough at this moment, but isn't ideal from a maintenance
perspective) is just deleted the plugin (see https://github.com/deepyaman/pyupgrade/tree/v3.9.0/pyupgrade/_plugins).

**Comment by asottile** [comment]
search the issue tracker
