### ISSUE TITLE
Please use f string instead of "".format()

### ISSUE THREAD

**Issue by jbleyel** [asottile/pyupgrade#876]
f string is faster and more readable.

**Comment by calumy** [comment]
See: https://github.com/asottile/pyupgrade/issues/808#issuecomment-1480488211

**Comment by jbleyel** [comment]
I have used this "--py311-plus" .. So why not using f string?
Is this version parameter not additiv?

**Comment by jbleyel** [comment]
I have overseen this:

`note: pyupgrade is intentionally timid and will not create an f-string if it would make the expression longer or if the substitution parameters are sufficiently complicated (as this can decrease readability).`

Can you please add an extra parameter to force f strings?
