### ISSUE TITLE
Class property Optional return typehint incorrectly substituted when targeting Python version <3.10

### ISSUE THREAD

**Issue by owenlamont** [asottile/pyupgrade#879]
I wanted to run pyupgrade on a new Python package repo that targets Python 3.9 as its maximum Python version but I found some _Optional[str]_ typehints were being incorrectly converted to _str | None_

I'm running pyupgrade from a pipx install, it's installed with a Python 3.11.4 environment on Windows:

![image](https://github.com/asottile/pyupgrade/assets/12672027/133709ee-30a6-4493-9024-52aa0699f9d6)

The relevant part of my pre-commit config is:

```
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]
```

I then ran:

```
pre-commit run --all-files
``` 

After adding pyupgrade to the new repo for the first time.

I expected all Optional typehints to be preserved (and most Optional typehints were correctly preserved) but I noticed property decorated functions that returned Optional types had their Optional type incorrectly substituted, e.g.:

Before:

```python
class SomeClass:
    @property
    def some_property(self) -> Optional[str]:
        return None
```

After:

```python
class SomeClass:
    @property
    def some_property(self) -> str | None:
        return None
```

I noticed even when I changed the pyupgrade arguments to _--py37-plus_ this substitution still happened. The Optional typehints on regular function returns were correctly preserved, this seems specific to property decorated methods.

**Comment by owenlamont** [comment]
Oh wait, I missed a:

_from __future__ import annotations_

This is a duplicate I think. I'll close it.

**Comment by oerp-odoo** [comment]
For me this is failing with this syntax (on 3.9):

pyupgrade converted `Optional` syntax to `str | None` etc and its failing even with `from __future__ import annotations`

For example:

```python
from __future__ import annotations

class MyClass(BaseModel):
    campaign: str | None = None
    medium: str | None = None
    source: str | None = None
    referred: str | None = None
```

**Comment by asottile** [comment]
search your error message and read the documentation
