### ISSUE TITLE
Avoid changes in one line or one file

### ISSUE THREAD

**Issue by gilcu2** [asottile/pyupgrade#882]
I am working on py311 but some libs like typer doesn't understand str|None typing so I am force to use Optional[str]
Can you implement some way to avoid changes on specific lines or files? Right I needed to disable the plugin

**Comment by asottile** [comment]
`--keep-runtime-typing` is intended for this

**Comment by gilcu2** [comment]
Hello, I don't want to avoid the changes in all my files, lines. Only in some special cases like files and lines

**Comment by asottile** [comment]
then use `exclude` / `files` to select what you want

**Comment by gilcu2** [comment]
I will check about, didn't saw it
thanks
