### ISSUE TITLE
Rewriting `for/yield` to `yield from` breaks sending

### ISSUE THREAD

**Issue by maxbachmann** [asottile/pyupgrade#884]
We use something like the following:
```python
class Task:
    def execute(self):
        return 1

def func():
    tasks = [Task()]
    for task in tasks:
        yield task

generator = func()
task = next(generator)
generator.send(task.execute())
```

if we do not use the task result, `pyupgrade` will rewrite this to:
```python
def func():
    tasks = [Task()]
    yield from tasks
```
which will fail with:
```
AttributeError: 'list_iterator' object has no attribute 'send'
```

As a workaround it is possible to prevent `pyupgrade` from making this conversion by explicitly ignoring the result:
```python
def func():
    tasks = [Task()]
    for task in tasks:
        ignore = yield task
```

**Comment by asottile** [comment]
this is one of the unfortunately tiny unavoidable edge cases

you're not actually using a generator as a coroutine though so you can replace your calling code with a simple loop

**Comment by asottile** [comment]
pyupgrade does try very hard to not break code.  generator coroutines created from lists without using the send value is really exceedingly rare (and usually better serviced by true async)

I'd be interested in your actual example instead of your minimal one since it seems very very strange to `.send(...)` without actually using the value on the receiving side (and any amount of value use would prevent the rewrite in the first place).  the example given seems "garbage in garbage out" to me

**Comment by maxbachmann** [comment]
We use a generator for our main state machine and allow the use of futures (like Task) to wait for asynchronous operations without blocking the rendering.

In most cases we do use the result value of these futures, but there are cases where we do not care about the result. In this example the asynchronous function loads some settings files and already stores them.
```python
  async def load_settings(self) :
      settings = await self.read_settings()
      if settings:
          self.settings = settings
      else:
          self.settings = default_settings
       return self.settings
```

**Comment by asottile** [comment]
async for is already excluded from this rewrite.  can you show your actual problem?

**Comment by maxbachmann** [comment]
The list stores futures for these async functions. 
```python
class Task(Future):
    def __init__(self, coro):
        ...

class Settings:
    def __init__(self):
        self.settings = None

    async def load_settings(self) :
        settings = await self.read_settings()
        if settings:
            self.settings = settings
        else:
            self.settings = default_settings
        return self.settings

settings = Settings()

class State:
    def runState(self):
        # runState of the current state is called in each frame
        try:
            ...

            # value is the result of the future
            # self.frame is the current state of the self.run generator
            if self.value is not None:
                value, self.value = self.value, None
                return self.frame.send(value)

            return next(self.frame)
        except StopIteration:
            ...

class StartupState(State):
    def run():
        ...

        tasks = [Task(settings.load_settings()), Task(settings.load_settings2()), ...]
        for task in tasks:
            yield task

        yield self.switch(SecondState)
```

I guess there is not really any way to determine when the rewrite from `for/yield` to `yield from` is safe.

**Comment by asottile** [comment]
why is it not simply `return next(self.frame)` -- nothing is using the sent value

**Comment by maxbachmann** [comment]
Other states are using the results of the coroutines. Since there is no way to detect whether the value will be used (unless we would manually mark the futures), the implementation always passes in the result.
