### ISSUE TITLE
Upgrade `defaultdict` default_factory (simple lambdas)

### ISSUE THREAD

**Issue by UnknownPlatypus** [asottile/pyupgrade#899]
Hello!

It is quite common to see lambda expression used as `default_factory` in  `defaultdict`, however sometime there are some shorter / more idiomatic options, especially for builtin types. Some exemples:

```diff
-defaultdict(lambda: set())
+defaultdict(set)

-defaultdict(lambda: [])
+defaultdict(list)
-defaultdict(lambda: list())
+defaultdict(list)

-defaultdict(lambda: {})
+defaultdict(dict)

-defaultdict(lambda: 0)
+defaultdict(int)

-defaultdict(lambda: 0.0)
+defaultdict(float)

# Doesn't make much sense to use a tuple here thought
-defaultdict(lambda: ())
+defaultdict(tuple)
```
I was wondering if that kind of fixer would be in scope for pyupgrade ?

Checking open source python code, the lambda pattern seems quite common so I think this fixer could benefit many people: 
https://sourcegraph.com/search?q=context%3Aglobal+language%3Apython+defaultdict%5C%28%28lambda%3A+.*%29%5C%29&patternType=regexp&sm=1&groupBy=group&expanded=

If you find it's worth implementing, I'll be happy to work on it.

Thanks

**Comment by asottile** [comment]
seems like a useful improvement -- it's not exactly in line with pyupgrade but I guess one could argue "lambda didn't exist and then it did" so probably fits enough

let me know if you need pointers
