### ISSUE TITLE
Does not rewrite typing hints when typing imported as `import typing as tp`

### ISSUE THREAD

**Issue by rusmux** [asottile/pyupgrade#908]
For example:

```Python
import typing as tp


def main(param: tp.Dict[str, str]) -> None:
    ...
```

Running `pyupgrade --py39-plus main.py` does nothing, however it should replace `tp.Dict` with `dict`. It only works if types are imported directly from `typing`

**Comment by asottile** [comment]
correct, aliasing is intentionally not supported
