### ISSUE TITLE
Feature request: `--keep-format`

### ISSUE THREAD

**Issue by Rotzbua** [asottile/pyupgrade#910]
The option `--py36-plus` migrates strings with `.format` automatically to f-strings if possible. This means the code base may migrated two different methods for string formating.
For better migration experience it would be nice to have an option like the [`--keep-percent-format`](https://github.com/asottile/pyupgrade#printf-style-string-formatting) to keep the `.format`-style and only do the other useful migration. Furthermore then it is possible to separate steps.

**Comment by asottile** [comment]
options are only added for breakage.  the keep-percent-format will be removed at some point because it's no longer relevant in python 3

**Comment by Rotzbua** [comment]
Thanks for the clarification 👍
