### ISSUE TITLE
Rewriting to `yield from` may introduce type errors when using pyright

### ISSUE THREAD

**Issue by Popkornium18** [asottile/pyupgrade#917]
Consider the following snippet:

```
# pyright: strict
import subprocess


def _capture_process_output(command: list[str]):
    popen = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    for line in iter(popen.stdout.readline, ""):
        yield line

    popen.stdout.close()
    return_code = popen.wait()
    if return_code:
        raise Exception(f"Process failed with exit code {return_code}")
```

Pyright is fine with that function and reports its return type as `Generator[str, Any, None]`.

However, after reweriting it to `yield from iter(...` pyright complains about the return type being partially unknown and reports the return type as `Generator[str, Unknown, None]`.

**Comment by asottile** [comment]
report it to pyright then I don't know what you want me to do about it

**Comment by Popkornium18** [comment]
Ok, I'll do that, thanks
