### ISSUE TITLE
Remove imports for pep 585

### ISSUE THREAD

**Issue by Ezibenroc** [asottile/pyupgrade#928]
Related to the [pep 585 feature](https://github.com/asottile/pyupgrade?tab=readme-ov-file#pep-585-typing-rewrites).

Running pyupgrade on this input file:
```python
from typing import List

def f(x: List[str]) -> None:
    pass
```

It currently produces this file (changing `List` to `list`):
```python
from typing import List

def f(x: list[str]) -> None:
    pass
```

I think it would be nice to produce this file instead (removing the now unused import):
```python
def f(x: list[str]) -> None:
    pass
```

**Comment by asottile** [comment]
please search the issue tracker for duplicates
