### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by opk12** [asottile/pyupgrade#930]
I want to learn Python idiomatic constructs and lose bad habits, so I'd like to see a warning and fix it manually. The README seems to suggest that auto-fixing is the only mode of operation. I could fix, read the diff and undo the fix, but it would be handy to have a dedicated CLI option.

**Comment by asottile** [comment]
since you're learning:
- always start by searching the issue tracker for duplicates (there are many)
- use version control
