### ISSUE TITLE
Weird behaviour of multi-line using triple quotes notation f-string containing emoji

### ISSUE THREAD

**Issue by mboutet** [asottile/pyupgrade#957]
pyupgrade 3.17.0 transforms:

```python
f"""
😃{foo}
"""
```

into:

```python
f"""
😃{fo{foo}
"""
```

which is invalid Python syntax.

The above example has been simplified to the minimal working example I could come up with.

Python version is 3.12.4 if that matters.

Thank you!

**Comment by asottile** [comment]
please search for duplicates there are at least two
