### ISSUE TITLE
Ability to restrict changes to a specific type?

### ISSUE THREAD

**Issue by lightswitch05** [asottile/pyupgrade#963]

**Comment by asottile** [comment]
I have no idea what you want given just your vague title

**Comment by lightswitch05** [comment]
I accidentally hit enter before filling out to description and you were too fast for me to finish write it 😆 😢 - actual description in progress

**Comment by lightswitch05** [comment]
@asottile maybe you could have another glance now that I has a proper description?

**Comment by asottile** [comment]
I've already declined exactly this proposal many times

**Comment by lightswitch05** [comment]
Sorry for the duplicate!
