### ISSUE TITLE
pyupgrade39-plus breaks inspect.isclass for <= python3.10

### ISSUE THREAD

**Issue by commonism** [asottile/pyupgrade#967]
The following
```python
from typing import Dict
import inspect
assert inspect.isclass(Dict[str, str]) is False
```

is rewritten as

```python
import inspect
assert inspect.isclass(dict[str, str]) is False
```

which is broken for python3.10 (and 3.9 too I guess).

```
Traceback (most recent call last):
  File "/tmp/pyupgrade39.py", line 8, in <module>
    assert inspect.isclass(dict[str, str]) is False
AssertionError
```

it works for 3.11+

Same problem for list, tuple.

related issue: https://github.com/python/cpython/issues/88459
related pr: https://github.com/python/cpython/pull/93754

**Comment by asottile** [comment]
seems like a bug in python not here
