### ISSUE TITLE
Rewrite `typing.AbstractSet` to `collections.abc.Set`

### ISSUE THREAD

**Issue by oprypin** [asottile/pyupgrade#968]
There are rewrites defined for Python 3.9+ to use `collections.abc.Foo[Bar]` instead of `typing.Foo[Bar]`.
[Relevant code location](https://github.com/asottile/pyupgrade/blob/0f1d07c371ab18d8b17082bd5ddb3020659446b3/pyupgrade/_plugins/imports.py#L150)

However between these modules there is exactly one such recommended replacement where the name does not match.
**`collections.abc.Set`** should be used instead of **[`typing.AbstractSet`](https://docs.python.org/3/library/typing.html#typing.AbstractSet)**.

Currently pyupgrade does not touch `typing.AbstractSet`. It would be nice if it rewrote it to `collections.abc.Set`.

And thanks for this great tool.

**Comment by asottile** [comment]
names cannot be renamed safely
