### ISSUE TITLE
Versioned branch fixer removes comments after `if` block

### ISSUE THREAD

**Issue by adamchainz** [asottile/pyupgrade#970]
The 'versioned branch' fixer currently removes comments after a dropped `if` block:

```diff
 import sys
 
-if sys.version_info < (3, 2):
-    print("3.2")
-
-# let's go
 print("ok")
```

The comment is outside of the block and should be preserved.

(Just fixed a similar issue in django-upgrade: https://github.com/adamchainz/django-upgrade/issues/495 .)

**Comment by asottile** [comment]
there's a duplicate somewhere. this is relatively unfixable because there's no definitive end of a block

**Comment by adamchainz** [comment]
Isn't this sufficient? #971 . It seems to, at least.

**Comment by BonaFideIT** [comment]
This could be the duplicate issue which @asottile mentioned: https://github.com/asottile/pyupgrade/issues/931.

But I think @adamchainz is right, @asottile can you recheck this please?

**Comment by asottile** [comment]
there's a case that this creates a syntax error, I can't remember the exact one
