### ISSUE TITLE
Literals containing \N escapes

### ISSUE THREAD

**Issue by inikolaev** [asottile/pyupgrade#975]
After upgrading project to Python 3.12 `pyupgrade` started to break:

```
s = f"\N{EN DASH}"
```

is being changed into

```
s = f"\N{{EN DASH}}"
```

which is invalid.

I tested revering back to 3.11 and rerunning `pyupgrade` and everything looks good.

**Comment by asottile** [comment]
what version are you using?

**Comment by inikolaev** [comment]
Sorry, haven't noticed your comment earlier.
I was using 3.18.0, I'll try the fix you've just released, thank you!
