### ISSUE TITLE
pyupgrade may output opening braces at the start of an f-string expression

### ISSUE THREAD

**Issue by jnewbery** [asottile/pyupgrade#976]
The start of an f-string expression is indicated with a single opening brace `{`. If a double brace `{{` appears within an f-string, it is escaped as a single literal `{`. (see [f-string spec](https://peps.python.org/pep-0498/#specification)).

pyupgrade will change a `set([1,2])` expression to `{1,2}`, even if it is at the start of an f-string expression. This changes the semantic meaning of the preceding opening brace from "begin expression" to "literal `{`".

Minimal example:

```
→ cat test_pyupgrade.py
print(f"{set([1+1])}")
→ python test_pyupgrade.py
{2}                                              # {set([1+1])} evaluated as an f-string expression
→ pyupgrade test_pyupgrade.py
Rewriting test_pyupgrade.py
→ cat test_pyupgrade.py
print(f"{{1+1}}")
→ python test_pyupgrade.py
{1+1}                                            # {{1+1}} evaluated as string literal

```

The fix is to insert a space at the beginning of the f-string expression if it starts with a `{`, for example, instead of:

```diff
- print(f"{set([1+1])}")
+ print(f"{{1+1}}")
```

do the following substitution:

```diff
- print(f"{set([1+1])}")
+ print(f"{ {1+1}}")
```

The leading space does not impact the evaluation of the expression, since the [expression is enclosed by implicit parentheses when evaluating](https://peps.python.org/pep-0498/#expression-evaluation).

**Comment by asottile** [comment]
what version are you using?

**Comment by jnewbery** [comment]
> what version are you using?

```
→ pipx list
[...]
   package pyupgrade 3.18.0, installed using Python 3.12.7
    - pyupgrade
```
