### ISSUE TITLE
PEP 585 rewrites don't work

### ISSUE THREAD

**Issue by phormio** [asottile/pyupgrade#978]
```
bash$ cat -n experiment1.py
     1	from __future__ import annotations
     2	
     3	def f(x: List[str]) -> None
     4	    print(100)
bash$ python3 --version
Python 3.11.2
bash$ pipx run pyupgrade --py39-plus experiment1.py
bash$ cat -n experiment1.py
     1	from __future__ import annotations
     2	
     3	def f(x: List[str]) -> None
     4	    print(100)
bash$ 
```

`pyupgrade` should change `List[str]` to `list[str]`. In fact, it leaves the file unchanged.

**Comment by asottile** [comment]
garbage in garbage out.  your code has a NameError

**Comment by phormio** [comment]
It has a `SyntaxError`. When I fix it, there is no `NameError`.

Here is the corrected program:

```python
from __future__ import annotations

from typing import List

def f(x: List[str]) -> None:
    print(100)
```

The `pyupgrade` command in my previous comment now behaves according to the documentation.

I wrote the program to check whether `pyupgrade` requires all of the list items in the ["Availability"](https://github.com/asottile/pyupgrade/blob/v3.18.0/README.md#pep-585-typing-rewrites) section to be true or only one of them. The documentation is unclear on this point.

**Comment by asottile** [comment]
why would you expect a malformed input to produce a meaningful result 

I don't understand the mental gymnastics
