### ISSUE TITLE
Remove all future imports

### ISSUE THREAD

**Issue by cdeil** [asottile/pyupgrade#98]
I have projects that have this line at the start of every file, that I now want to upgrade to Python 3 only:
```
from __future__ import absolute_import, print_function, division
```
That's pretty common, everyone dropping Python 2 support from a codebase will want to do that cleanup, no?

It would be great if there was an option to just delete those lines (reviewing / adjusting the rest of the files would be up to me & automated tests to check).

#42 is related, but I thought I'd ask separately for this feature to remove any `__future__` import lines.

`2to3` can do it, but it leaves an empty line, doesn't delete the future line.
If you don't want to add something here, then maybe the `2to3` option could be mentioned in the README?

**Comment by asottile** [comment]
#42 is an exact duplicate. Please read the solutions there

**Comment by asottile** [comment]
I had a change of heart, #202 implements this
