### ISSUE TITLE
Rewrite future.utils.listvalues

### ISSUE THREAD

**Issue by m-aciek** [asottile/pyupgrade#984]
```python
from future.utils import listvalues

assert listvalues(a) == list(a.values())
```

`listvalues(a)` is a [Python 2/3 compatibility function](https://python-future.readthedocs.io/en/latest/compatible_idioms.html#dict-keys-values-items-as-a-list) and can (should) be rewritten to `list(a.values())` in Python 3+. Would such a rewrite be accepted?

**Comment by asottile** [comment]
`list(x values())` is usually a smell.  we didn't attempt anything from python-future because it has terribly leaky internals that make most of its rewrites unsafe

plus that ship sailed years ago.

so I'm probably going to decline saying python-future is out of scope
