### ISSUE TITLE
Union with double quotes is not updated

### ISSUE THREAD

**Issue by msterpa87** [asottile/pyupgrade#988]
I noticed that when a `Union` annotation has double quoted types inside it doesn't get updated, example:

```
class What:
    pass

def whatever(x: Union[int, "What", str]) -> None:
    pass
```

This is left unchanged, but if we do:

```
def whatever(x: Union[int, str]) -> None:
    pass
```

Then it is correctly converted to:

```
def whatever(x: int | str) -> None:
    pass
```

**Comment by asottile** [comment]
try it and find out why
