### ISSUE TITLE
py3.6+: Rewrite OrderedDict as dict literals

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#99]
Python 3.6 has an insertion order preserving dict. Python 3.7 has this defined as a language feature. 

This obviates `collections.OrderedDict` usage, so this tool could rewrite `OrderedDict` as dict literals when `--py36-plus` is passed.

**Comment by asottile** [comment]
this isn't a safe 1:1 replacement unfortunately, for instance this code would be broken:

```python
dct = OrderedDict(((1, 2), (3, 4), (5, 6)))
dct.move_to_end(3)
assert dct.popitem() == (3, 4)
```

so unfortunately I don't think this is actionable :(

**Comment by jdufresne** [comment]
Thanks, yeah I see and agree. While very close, there are edge cases that makes this rewrite dangerous. I'll close.

**Comment by asottile** [comment]
Thanks for the issue nonetheless 🎉
