### ISSUE TITLE
Simplify `try .. except ImportError` with stdlib imports

### ISSUE THREAD

**Issue by gsnedders** [asottile/pyupgrade#991]
With:

```python
try:
    from urllib.parse import urlparse
except ImportError:
    from urlparse import urlparse
```

We should be able to be certain that importing `urllib.parse.urlparse` will succeed on Python 3.0 and above, given it is part of the stdlib and isn't in any way optional, thus can be simplified to just `from urllib.parse import urlparse`.

**Comment by asottile** [comment]
there's a ton of duplicates. please search next time
